import { deriveDocumentLifecycle } from "./document-integrity";
import {
  isDocumentUsableForFinancialCalculations,
  isUsableLegacyImportedDocument,
} from "./document-integrity/legacy-import-attestation";
import { isAutoGeneratedReceipt } from "./receipts";
import { withDocumentFinancialIntegritySignals } from "./document-integrity/financial-documents";
import { hasAppIssuedRecoveryProtectionClaim } from "./document-integrity/app-issued-recovery-protection";
import type { Document } from "./types";
import { documentAmounts } from "./vat-regime";

function historicalDocumentTotal(document: Document): number {
  return documentAmounts(document, false).total;
}

function hasUsableDocumentIntegrity(doc: Document): boolean {
  return isDocumentUsableForFinancialCalculations(doc);
}

export function canMarkAsCollected(doc: Document): boolean {
  if (doc.type !== "factura" && doc.type !== "recibo") return false;
  if (hasAppIssuedRecoveryProtectionClaim(doc)) return false;
  if (!hasUsableDocumentIntegrity(doc)) return false;
  if (isUsableLegacyImportedDocument(doc)) return false;
  if (doc.status === "anulada" || doc.rectifiedById) return false;
  if (deriveDocumentLifecycle(doc) !== "issued") return false;
  return true;
}

export function canUnmarkAsCollected(doc: Document): boolean {
  if (doc.type !== "factura" && doc.type !== "recibo") return false;
  if (hasAppIssuedRecoveryProtectionClaim(doc)) return false;
  return doc.status === "pagado";
}

export function isCollectedDocument(doc: Document): boolean {
  if (doc.type !== "factura" && doc.type !== "recibo") return false;
  if (!hasUsableDocumentIntegrity(doc) || doc.status !== "pagado") return false;
  // Una rectificativa de anulacion liquida el ingreso de su original; no es
  // un cobro independiente. La clase fiscal congelada prevalece sobre cualquier
  // deriva viva posterior, igual que los importes usados en el cálculo.
  const rectificationType =
    doc.documentSnapshot?.rectification?.type ?? doc.rectification?.type;
  if (rectificationType === "anulacion") return false;
  if (doc.rectifiedById) return false;
  if (deriveDocumentLifecycle(doc) !== "issued") return false;
  if (isAutoGeneratedReceipt(doc)) return false;
  return true;
}

export function collectedIncome(documents: Document[]): number {
  const integrityCheckedDocuments =
    withDocumentFinancialIntegritySignals(documents);
  const linkedReceiptIds = new Set(
    integrityCheckedDocuments.flatMap((document) =>
      document.receiptDocumentId ? [document.receiptDocumentId] : [],
    ),
  );
  return integrityCheckedDocuments
    .filter(
      (document) =>
        !linkedReceiptIds.has(document.id) && isCollectedDocument(document),
    )
    .reduce((sum, doc) => sum + historicalDocumentTotal(doc), 0);
}

export function isPendingInvoicePayment(doc: Document): boolean {
  return (
    doc.type === "factura" &&
    hasUsableDocumentIntegrity(doc) &&
    doc.status !== "pagado" &&
    doc.status !== "anulada" &&
    doc.status !== "borrador" &&
    !doc.rectifiedById &&
    historicalDocumentTotal(doc) > 0
  );
}

export function pendingCollection(documents: Document[]): number {
  return withDocumentFinancialIntegritySignals(documents)
    .filter(isPendingInvoicePayment)
    .reduce((sum, doc) => sum + historicalDocumentTotal(doc), 0);
}

export function statusAfterUnmarkingCollection(
  doc: Document,
): Document["status"] {
  if (!canUnmarkAsCollected(doc)) return doc.status;
  return "enviado";
}
