import { documentTotals } from "./calculations";
import { isAutoGeneratedReceipt } from "./receipts";
import type { Document } from "./types";

export function canMarkAsCollected(doc: Document): boolean {
  if (doc.type !== "factura" && doc.type !== "recibo") return false;
  if (doc.status === "anulada" || doc.rectifiedById) return false;
  return true;
}

export function isCollectedDocument(doc: Document): boolean {
  if (!canMarkAsCollected(doc) || doc.status !== "pagado") return false;
  if (isAutoGeneratedReceipt(doc)) return false;
  return true;
}

export function collectedIncome(documents: Document[]): number {
  return documents
    .filter(isCollectedDocument)
    .reduce((sum, doc) => sum + documentTotals(doc).total, 0);
}

export function pendingCollection(documents: Document[]): number {
  return documents
    .filter(
      (doc) =>
        doc.type === "factura" &&
        doc.status !== "pagado" &&
        doc.status !== "anulada" &&
        doc.status !== "borrador" &&
        !doc.rectifiedById,
    )
    .reduce((sum, doc) => sum + documentTotals(doc).total, 0);
}

export function statusAfterUnmarkingCollection(doc: Document): Document["status"] {
  if (doc.status !== "pagado") return doc.status;
  return "enviado";
}
