import { describe, expect, it } from "vitest";
import {
  buildReceiptFromInvoice,
  isAutoGeneratedReceipt,
  unmarkInvoiceCollection,
} from "./receipts";
import { isCollectedDocument } from "./income";
import { issueDocument, markDocumentPaid } from "./document-integrity";
import { EMPTY_DATA } from "./types";
import type { Document } from "./types";

const invoice: Document = {
  id: "inv-1",
  type: "factura",
  number: "F-2026-0001",
  date: "2026-06-09",
  client: { name: "Ana López", firstName: "Ana", lastName: "López" },
  items: [
    {
      id: "l1",
      description: "Servicio",
      quantity: 2,
      unit: "m2",
      unitPrice: 100,
      ivaPercent: 21,
    },
  ],
  paymentTerms: "Transferencia bancaria",
  status: "enviado",
  createdAt: "2026-06-09",
  updatedAt: "2026-06-09",
};

describe("buildReceiptFromInvoice", () => {
  it("crea recibo pagado vinculado a la factura", () => {
    const receipt = buildReceiptFromInvoice(invoice);
    expect(receipt.type).toBe("recibo");
    expect(receipt.status).toBe("pagado");
    expect(receipt.sourceDocumentId).toBe("inv-1");
    expect(receipt.notes).toContain("F-2026-0001");
    expect(receipt.items).toHaveLength(1);
    expect(receipt.items[0].id).not.toBe("l1");
    expect(receipt.items[0].unit).toBe("m2");
    expect(receipt.items[0].quantity).toBe(2);
    expect(receipt.paymentTerms).toBe("Transferencia bancaria");
  });

  it("el recibo generado bajo petición puede emitirse como pagado", () => {
    const paidInvoice = markDocumentPaid(
      issueDocument(
        { ...invoice, status: "borrador" },
        EMPTY_DATA.profile,
        "2026-06-24T10:00:00.000Z",
      ),
      "2026-06-24T10:00:00.000Z",
    );
    const receiptDraft = {
      ...buildReceiptFromInvoice(invoice),
      id: "receipt-1",
      number: "R-2026-0001",
      createdAt: "2026-06-24T10:00:00.000Z",
      updatedAt: "2026-06-24T10:00:00.000Z",
    };
    const paidReceipt = markDocumentPaid(
      issueDocument(
        { ...receiptDraft, status: "borrador" },
        EMPTY_DATA.profile,
        "2026-06-24T10:00:00.000Z",
      ),
      "2026-06-24T10:00:00.000Z",
    );

    expect(paidInvoice.status).toBe("pagado");
    expect(paidReceipt.type).toBe("recibo");
    expect(paidReceipt.status).toBe("pagado");
    expect(paidReceipt.sourceDocumentId).toBe(invoice.id);
  });
});

describe("isAutoGeneratedReceipt", () => {
  it("excluye recibos automáticos del cómputo de ingresos", () => {
    const autoReceipt: Document = {
      ...invoice,
      id: "r1",
      type: "recibo",
      number: "R-2026-0001",
      status: "pagado",
      sourceDocumentId: "inv-1",
    };
    expect(isAutoGeneratedReceipt(autoReceipt)).toBe(true);
    expect(isCollectedDocument(autoReceipt)).toBe(false);
    expect(isCollectedDocument({ ...invoice, status: "pagado" })).toBe(true);
  });
});

describe("unmarkInvoiceCollection", () => {
  function paidInvoiceWithReceipt(receipt: Document): Document {
    return markDocumentPaid(
      issueDocument(
        {
          ...invoice,
          status: "borrador",
          receiptDocumentId: receipt.id,
        },
        EMPTY_DATA.profile,
        "2026-06-24T10:00:00.000Z",
      ),
      "2026-06-24T10:00:00.000Z",
    );
  }

  function draftReceipt(overrides: Partial<Document> = {}): Document {
    return {
      ...invoice,
      id: "receipt-draft",
      type: "recibo",
      number: "R-2026-0001",
      status: "borrador",
      sourceDocumentId: invoice.id,
      createdAt: "2026-06-24T09:00:00.000Z",
      updatedAt: "2026-06-24T09:00:00.000Z",
      ...overrides,
    };
  }

  function emittedReceipt(overrides: Partial<Document> = {}): Document {
    return markDocumentPaid(
      issueDocument(
        draftReceipt({
          id: "receipt-issued",
          number: "R-2026-0001",
          ...overrides,
        }),
        EMPTY_DATA.profile,
        "2026-06-24T10:00:00.000Z",
      ),
      "2026-06-24T10:05:00.000Z",
    );
  }

  it("desmarcar cobro con recibo borrador puede eliminarlo sin tocar emitidos", () => {
    const removableReceipt = draftReceipt();
    const protectedReceipt = emittedReceipt({
      id: "receipt-issued",
      number: "R-2026-0002",
      sourceDocumentId: "other-invoice",
    });
    const paidInvoice = paidInvoiceWithReceipt(removableReceipt);

    const result = unmarkInvoiceCollection(
      [paidInvoice, removableReceipt, protectedReceipt],
      paidInvoice.id,
      "enviado",
      "2026-06-24T11:00:00.000Z",
      EMPTY_DATA.profile.numbering,
    );

    expect(result.removedReceiptId).toBe(removableReceipt.id);
    expect(result.documents.some((doc) => doc.id === removableReceipt.id)).toBe(
      false,
    );
    expect(result.documents.find((doc) => doc.id === protectedReceipt.id)).toBe(
      protectedReceipt,
    );
    expect(result.documents.find((doc) => doc.id === paidInvoice.id)).toMatchObject({
      status: "enviado",
      paymentStatus: "pending",
      paidAt: undefined,
      receiptDocumentId: undefined,
    });
  });

  it("desmarcar cobro con recibo emitido no lo elimina ni renumera emitidos", () => {
    const receipt = emittedReceipt();
    const paidInvoice = paidInvoiceWithReceipt(receipt);
    const secondReceipt = emittedReceipt({
      id: "receipt-2",
      number: "R-2026-0003",
      sourceDocumentId: "other-invoice",
    });

    const result = unmarkInvoiceCollection(
      [paidInvoice, receipt, secondReceipt],
      paidInvoice.id,
      "enviado",
      "2026-06-24T11:00:00.000Z",
      EMPTY_DATA.profile.numbering,
    );

    expect(result.preservedReceiptId).toBe(receipt.id);
    expect(result.removedReceiptId).toBeUndefined();
    expect(result.documents.find((doc) => doc.id === receipt.id)).toBe(receipt);
    expect(result.documents.find((doc) => doc.id === secondReceipt.id)?.number).toBe(
      "R-2026-0003",
    );
    expect(result.documents.find((doc) => doc.id === paidInvoice.id)).toMatchObject({
      status: "enviado",
      paymentStatus: "pending",
      paidAt: undefined,
      receiptDocumentId: undefined,
    });
  });

  it("desmarcar cobro no altera snapshot/hash de factura", () => {
    const receipt = emittedReceipt();
    const paidInvoice = paidInvoiceWithReceipt(receipt);
    const snapshotHash = paidInvoice.documentSnapshot?.snapshotHash;
    const contentHash = paidInvoice.pdfSnapshot?.contentHash;

    const result = unmarkInvoiceCollection(
      [paidInvoice, receipt],
      paidInvoice.id,
      "enviado",
      "2026-06-24T11:00:00.000Z",
      EMPTY_DATA.profile.numbering,
    );
    const invoiceAfter = result.documents.find((doc) => doc.id === paidInvoice.id);

    expect(invoiceAfter?.documentSnapshot).toBe(paidInvoice.documentSnapshot);
    expect(invoiceAfter?.pdfSnapshot).toBe(paidInvoice.pdfSnapshot);
    expect(invoiceAfter?.documentSnapshot?.snapshotHash).toBe(snapshotHash);
    expect(invoiceAfter?.pdfSnapshot?.contentHash).toBe(contentHash);
  });

  it("desmarcar cobro no altera snapshot/hash de recibo emitido", () => {
    const receipt = emittedReceipt();
    const paidInvoice = paidInvoiceWithReceipt(receipt);
    const snapshotHash = receipt.documentSnapshot?.snapshotHash;
    const contentHash = receipt.pdfSnapshot?.contentHash;

    const result = unmarkInvoiceCollection(
      [paidInvoice, receipt],
      paidInvoice.id,
      "enviado",
      "2026-06-24T11:00:00.000Z",
      EMPTY_DATA.profile.numbering,
    );
    const receiptAfter = result.documents.find((doc) => doc.id === receipt.id);

    expect(receiptAfter).toBe(receipt);
    expect(receiptAfter?.documentSnapshot?.snapshotHash).toBe(snapshotHash);
    expect(receiptAfter?.pdfSnapshot?.contentHash).toBe(contentHash);
  });
});
