import { todayISO } from "./calculations";
import { canPhysicallyDeleteDocument } from "./document-integrity/deletion";
import { inspectDocumentSnapshotsIntegrity } from "./document-integrity";
import {
  getDocumentYear,
  renumberDocumentsForKindYear,
} from "./documents";
import type { Document, NumberingSettings } from "./types";

function paymentStatusAfterUnmark(
  status: Document["status"],
): Document["paymentStatus"] {
  return status === "vencido" ? "overdue" : "pending";
}

export function buildReceiptFromInvoice(
  invoice: Document,
): Omit<Document, "id" | "number" | "createdAt" | "updatedAt"> {
  return {
    type: "recibo",
    date: todayISO(),
    client: { ...invoice.client },
    items: invoice.items.map((item) => ({
      ...item,
      id: crypto.randomUUID(),
    })),
    notes: `Pago de la factura ${invoice.number}`,
    paymentTerms: invoice.paymentTerms,
    status: "pagado",
    sourceDocumentId: invoice.id,
  };
}

export function findReceiptForInvoice(
  documents: Document[],
  invoiceId: string,
  receiptDocumentId?: string,
): Document | undefined {
  if (receiptDocumentId) {
    const linked = documents.find((d) => d.id === receiptDocumentId);
    if (linked?.type === "recibo") return linked;
  }
  return documents.find(
    (d) => d.type === "recibo" && d.sourceDocumentId === invoiceId,
  );
}

export function isAutoGeneratedReceipt(doc: Document): boolean {
  // Clasificación conservadora para no duplicar ingresos: todo recibo que
  // reclame una factura de origen se trata como vinculado. La acreditación de
  // esa relación es una comprobación distinta y más estricta.
  return doc.type === "recibo" && Boolean(doc.sourceDocumentId);
}

export function hasFrozenAutoGeneratedReceiptOrigin(doc: Document): boolean {
  return Boolean(
    doc.type === "recibo" &&
      doc.sourceDocumentId &&
      doc.documentSnapshot?.sourceDocumentId === doc.sourceDocumentId &&
      Object.prototype.hasOwnProperty.call(
        doc.documentSnapshot,
        "sourceDocumentId",
      ) &&
      inspectDocumentSnapshotsIntegrity(doc, {
        requireDocumentSnapshot: true,
        requirePdfSnapshot: true,
        requireSnapshotSeal: true,
      }).ok,
  );
}

export function canDeleteAutoGeneratedReceiptOnUnmark(doc: Document): boolean {
  return (
    doc.type === "recibo" &&
    Boolean(doc.sourceDocumentId) &&
    canPhysicallyDeleteDocument(doc)
  );
}

export interface UnmarkInvoiceCollectionResult {
  documents: Document[];
  removedReceiptId?: string;
  preservedReceiptId?: string;
  renumberYear?: number;
}

export function unmarkInvoiceCollection(
  documents: Document[],
  invoiceId: string,
  nextStatus: Document["status"],
  updatedAt: string,
  numbering?: NumberingSettings,
): UnmarkInvoiceCollectionResult {
  const invoice = documents.find((doc) => doc.id === invoiceId);
  if (!invoice || invoice.type !== "factura") {
    return { documents };
  }

  const receipt = findReceiptForInvoice(
    documents,
    invoice.id,
    invoice.receiptDocumentId,
  );

  // Una vez emitido el recibo, deshacer solo el cobro rompería la relación
  // fiscal sellada. La pareja se conserva hasta disponer de un flujo explícito
  // de anulación/rectificación del recibo.
  if (
    receipt &&
    (receipt.sourceDocumentId !== invoice.id ||
      !canDeleteAutoGeneratedReceiptOnUnmark(receipt))
  ) {
    return {
      documents,
      preservedReceiptId: receipt.id,
    };
  }

  let nextDocuments = documents.map((doc) =>
    doc.id === invoice.id
      ? {
          ...doc,
          status: nextStatus,
          paymentStatus: paymentStatusAfterUnmark(nextStatus),
          paidAt: undefined,
          receiptDocumentId: undefined,
          updatedAt,
        }
      : doc,
  );

  if (!receipt) {
    return { documents: nextDocuments };
  }

  nextDocuments = nextDocuments.filter((doc) => doc.id !== receipt.id);
  const renumberYear = getDocumentYear(receipt, numbering);

  return {
    documents: renumberDocumentsForKindYear(
      nextDocuments,
      "recibo",
      renumberYear,
      numbering,
    ),
    removedReceiptId: receipt.id,
    renumberYear,
  };
}
