import { describe, expect, it } from "vitest";
import { buildReceiptFromInvoice, isAutoGeneratedReceipt } from "./receipts";
import { isCollectedDocument } from "./income";
import type { Document } from "./types";

const invoice: Document = {
  id: "inv-1",
  type: "factura",
  number: "F-2026-0001",
  date: "2026-06-09",
  client: { name: "Ana López", firstName: "Ana", lastName: "López" },
  items: [
    {
      id: "l1",
      description: "Servicio",
      quantity: 2,
      unit: "m2",
      unitPrice: 100,
      ivaPercent: 21,
    },
  ],
  paymentTerms: "Transferencia bancaria",
  status: "enviado",
  createdAt: "2026-06-09",
  updatedAt: "2026-06-09",
};

describe("buildReceiptFromInvoice", () => {
  it("crea recibo pagado vinculado a la factura", () => {
    const receipt = buildReceiptFromInvoice(invoice);
    expect(receipt.type).toBe("recibo");
    expect(receipt.status).toBe("pagado");
    expect(receipt.sourceDocumentId).toBe("inv-1");
    expect(receipt.notes).toContain("F-2026-0001");
    expect(receipt.items).toHaveLength(1);
    expect(receipt.items[0].id).not.toBe("l1");
    expect(receipt.items[0].unit).toBe("m2");
    expect(receipt.items[0].quantity).toBe(2);
    expect(receipt.paymentTerms).toBe("Transferencia bancaria");
  });
});

describe("isAutoGeneratedReceipt", () => {
  it("excluye recibos automáticos del cómputo de ingresos", () => {
    const autoReceipt: Document = {
      ...invoice,
      id: "r1",
      type: "recibo",
      number: "R-2026-0001",
      status: "pagado",
      sourceDocumentId: "inv-1",
    };
    expect(isAutoGeneratedReceipt(autoReceipt)).toBe(true);
    expect(isCollectedDocument(autoReceipt)).toBe(false);
    expect(isCollectedDocument({ ...invoice, status: "pagado" })).toBe(true);
  });
});
