import { todayISO } from "./calculations";
import { canPhysicallyDeleteDocument } from "./document-integrity/deletion";
import {
  getDocumentYear,
  renumberDocumentsForKindYear,
} from "./documents";
import type { Document, NumberingSettings } from "./types";

export function buildReceiptFromInvoice(
  invoice: Document,
): Omit<Document, "id" | "number" | "createdAt" | "updatedAt"> {
  return {
    type: "recibo",
    date: todayISO(),
    client: { ...invoice.client },
    items: invoice.items.map((item) => ({
      ...item,
      id: crypto.randomUUID(),
    })),
    notes: `Pago de la factura ${invoice.number}`,
    paymentTerms: invoice.paymentTerms,
    status: "pagado",
    sourceDocumentId: invoice.id,
  };
}

export function findReceiptForInvoice(
  documents: Document[],
  invoiceId: string,
  receiptDocumentId?: string,
): Document | undefined {
  if (receiptDocumentId) {
    const linked = documents.find((d) => d.id === receiptDocumentId);
    if (linked?.type === "recibo") return linked;
  }
  return documents.find(
    (d) => d.type === "recibo" && d.sourceDocumentId === invoiceId,
  );
}

export function isAutoGeneratedReceipt(doc: Document): boolean {
  return doc.type === "recibo" && Boolean(doc.sourceDocumentId);
}

export function canDeleteAutoGeneratedReceiptOnUnmark(doc: Document): boolean {
  return isAutoGeneratedReceipt(doc) && canPhysicallyDeleteDocument(doc);
}

export interface UnmarkInvoiceCollectionResult {
  documents: Document[];
  removedReceiptId?: string;
  preservedReceiptId?: string;
  renumberYear?: number;
}

export function unmarkInvoiceCollection(
  documents: Document[],
  invoiceId: string,
  nextStatus: Document["status"],
  updatedAt: string,
  numbering?: NumberingSettings,
): UnmarkInvoiceCollectionResult {
  const invoice = documents.find((doc) => doc.id === invoiceId);
  if (!invoice || invoice.type !== "factura") {
    return { documents };
  }

  const receipt = findReceiptForInvoice(
    documents,
    invoice.id,
    invoice.receiptDocumentId,
  );
  let nextDocuments = documents.map((doc) =>
    doc.id === invoice.id
      ? {
          ...doc,
          status: nextStatus,
          receiptDocumentId: undefined,
          updatedAt,
        }
      : doc,
  );

  if (receipt?.sourceDocumentId !== invoice.id) {
    return { documents: nextDocuments };
  }

  if (!canDeleteAutoGeneratedReceiptOnUnmark(receipt)) {
    return {
      documents: nextDocuments,
      preservedReceiptId: receipt.id,
    };
  }

  nextDocuments = nextDocuments.filter((doc) => doc.id !== receipt.id);
  const renumberYear = getDocumentYear(receipt, numbering);

  return {
    documents: renumberDocumentsForKindYear(
      nextDocuments,
      "recibo",
      renumberYear,
      numbering,
    ),
    removedReceiptId: receipt.id,
    renumberYear,
  };
}
