import { todayISO } from "./calculations";
import type { Document } from "./types";

export function buildReceiptFromInvoice(
  invoice: Document,
): Omit<Document, "id" | "number" | "createdAt" | "updatedAt"> {
  return {
    type: "recibo",
    date: todayISO(),
    client: { ...invoice.client },
    items: invoice.items.map((item) => ({
      ...item,
      id: crypto.randomUUID(),
    })),
    notes: `Pago de la factura ${invoice.number}`,
    status: "pagado",
    sourceDocumentId: invoice.id,
  };
}

export function findReceiptForInvoice(
  documents: Document[],
  invoiceId: string,
  receiptDocumentId?: string,
): Document | undefined {
  if (receiptDocumentId) {
    const linked = documents.find((d) => d.id === receiptDocumentId);
    if (linked?.type === "recibo") return linked;
  }
  return documents.find(
    (d) => d.type === "recibo" && d.sourceDocumentId === invoiceId,
  );
}

export function isAutoGeneratedReceipt(doc: Document): boolean {
  return doc.type === "recibo" && Boolean(doc.sourceDocumentId);
}
