import { describe, expect, it } from "vitest";
import {
  buildReceiptFromInvoice,
  findReceiptForInvoice,
  findUniqueReceiptSourceInvoice,
  hasFrozenAutoGeneratedReceiptOrigin,
  inspectReceiptGeneration,
  inspectReceiptGenerationForDisplay,
  isAutoGeneratedReceipt,
  prepareReceiptGeneration,
  unmarkInvoiceCollection,
} from "./receipts";
import { isCollectedDocument } from "./income";
import {
  buildDocumentPdfSnapshot,
  buildDocumentSnapshotSeal,
  inspectDocumentSnapshotsIntegrity,
  issueDocument,
  markDocumentPaid,
  markDocumentSent,
  stableStringifySnapshot,
} from "./document-integrity";
import { legacyFnv1a32 } from "./document-integrity/snapshot-hash";
import { withDocumentRelationshipIntegritySignals } from "./document-integrity/relationships";
import { EMPTY_DATA } from "./types";
import { documentAmounts } from "./vat-regime";
import type {
  AppData,
  Document,
  DocumentPdfSnapshot,
  DocumentSnapshot,
} from "./types";

const PROFILE = {
  ...EMPTY_DATA.profile,
  name: "Autónomo Test",
  nif: "12345678Z",
  address: "Calle Mayor 1",
  postalCode: "28001",
  city: "Madrid",
};

function legacyHash(value: unknown): string {
  return `fnv1a32:${legacyFnv1a32(stableStringifySnapshot(value))}`;
}

function asLegacyDocumentSnapshot(snapshot: DocumentSnapshot): DocumentSnapshot {
  const content = { ...snapshot } as Record<string, unknown>;
  delete content.capturedAt;
  delete content.source;
  delete content.snapshotHash;
  const issuerContent = { ...snapshot.issuer } as Record<string, unknown>;
  delete issuerContent.capturedAt;

  return {
    ...snapshot,
    snapshotHash: legacyHash({
      ...content,
      issuer: issuerContent,
      items: snapshot.items.map((item) => {
        const itemContent = { ...item } as Record<string, unknown>;
        delete itemContent.id;
        return itemContent;
      }),
    }),
  };
}

function asLegacyPdfSnapshot(
  snapshot: DocumentPdfSnapshot,
  documentSnapshotHash: string,
): DocumentPdfSnapshot {
  const content = {
    ...snapshot,
    documentSnapshotHash,
  } as Record<string, unknown>;
  delete content.renderedAt;
  delete content.contentHash;
  return { ...snapshot, contentHash: legacyHash(content) };
}

const invoice: Document = issueDocument(
  {
    id: "inv-1",
    type: "factura",
    number: "F-2026-0001",
    date: "2026-06-09",
    client: {
      name: "Ana López",
      firstName: "Ana",
      lastName: "López",
      nif: "X1234567L",
      address: "Calle Cliente 2",
      postalCode: "28002",
      city: "Madrid",
    },
    items: [
      {
        id: "l1",
        description: "Servicio",
        quantity: 2,
        unit: "m2",
        unitPrice: 100,
        ivaPercent: 21,
      },
    ],
    paymentTerms: "Transferencia bancaria",
    status: "borrador",
    createdAt: "2026-06-09T09:00:00.000Z",
    updatedAt: "2026-06-09T09:00:00.000Z",
  },
  PROFILE,
  "2026-06-09T09:00:00.000Z",
);

function appDataWithDocuments(documents: Document[]): AppData {
  return {
    ...EMPTY_DATA,
    profile: {
      ...PROFILE,
      numbering: {
        ...PROFILE.numbering,
        lastSequence: { ...PROFILE.numbering.lastSequence },
        formats: {
          factura: { ...PROFILE.numbering.formats.factura },
          factura_rectificativa: {
            ...PROFILE.numbering.formats.factura_rectificativa,
          },
          presupuesto: { ...PROFILE.numbering.formats.presupuesto },
          recibo: { ...PROFILE.numbering.formats.recibo },
        },
      },
    },
    documents,
  };
}

function idSequence(...ids: string[]): () => string {
  let index = 0;
  return () => {
    const id = ids[index];
    index += 1;
    if (!id) throw new Error("Secuencia de IDs agotada en el test.");
    return id;
  };
}

describe("buildReceiptFromInvoice", () => {
  it("crea recibo pagado vinculado a la factura", () => {
    const receipt = buildReceiptFromInvoice(invoice, PROFILE);
    expect(receipt.type).toBe("recibo");
    expect(receipt.status).toBe("pagado");
    expect(receipt.sourceDocumentId).toBe("inv-1");
    expect(receipt.notes).toContain("F-2026-0001");
    expect(receipt.items).toHaveLength(1);
    expect(receipt.items[0].id).not.toBe("l1");
    expect(receipt.items[0].unit).toBe("m2");
    expect(receipt.items[0].quantity).toBe(2);
    expect(receipt.paymentTerms).toBe("Transferencia bancaria");
  });

  it("no crea otro recibo si la factura conserva un backlink", () => {
    expect(() =>
      buildReceiptFromInvoice(
        { ...invoice, receiptDocumentId: "receipt-missing" },
        PROFILE,
      ),
    ).toThrow("ya conserva un vínculo de recibo");
  });

  it("el recibo generado bajo petición puede emitirse como pagado", () => {
    const paidInvoice = markDocumentPaid(
      invoice,
      "2026-06-24T10:00:00.000Z",
    );
    const receiptDraft = {
      ...buildReceiptFromInvoice(invoice, PROFILE),
      id: "receipt-1",
      number: "R-2026-0001",
      createdAt: "2026-06-24T10:00:00.000Z",
      updatedAt: "2026-06-24T10:00:00.000Z",
    };
    const paidReceipt = markDocumentPaid(
      issueDocument(
        { ...receiptDraft, status: "borrador" },
        PROFILE,
        "2026-06-24T10:00:00.000Z",
      ),
      "2026-06-24T10:00:00.000Z",
    );

    expect(paidInvoice.status).toBe("pagado");
    expect(paidReceipt.type).toBe("recibo");
    expect(paidReceipt.status).toBe("pagado");
    expect(paidReceipt.sourceDocumentId).toBe(invoice.id);
  });

  it("usa la fuente canónica y bloquea derivados de una factura corrupta", () => {
    const drifted: Document = {
      ...invoice,
      number: "FALSA-VIVA",
      client: { name: "Cliente vivo falso" },
      items: [{ ...invoice.items[0], unitPrice: 999 }],
    };
    const receipt = buildReceiptFromInvoice(drifted, PROFILE);

    expect(receipt.notes).toContain(invoice.documentSnapshot!.number);
    expect(receipt.client.name).toBe(invoice.documentSnapshot!.customer.name);
    expect(receipt.items[0].unitPrice).toBe(
      invoice.documentSnapshot!.items[0].unitPrice,
    );

    const corrupt: Document = {
      ...invoice,
      documentSnapshot: {
        ...invoice.documentSnapshot!,
        number: "F-ALTERADA",
      },
    };
    expect(() =>
      buildReceiptFromInvoice(corrupt, PROFILE),
    ).toThrow("no supera la comprobación de integridad");
    expect(() => markDocumentPaid(corrupt)).toThrow(
      "no supera la comprobación de integridad",
    );
    expect(() => markDocumentSent(corrupt)).toThrow(
      "no supera la comprobación de integridad",
    );
  });

  it("rechaza un presupuesto sellado disfrazado de factura", () => {
    const quote = issueDocument(
      {
        id: "quote-disguised",
        type: "presupuesto",
        number: "P-2026-0001",
        date: invoice.date,
        client: { ...invoice.client },
        items: invoice.items.map((item) => ({ ...item })),
        status: "borrador",
        createdAt: "2026-06-24T10:00:00.000Z",
        updatedAt: "2026-06-24T10:00:00.000Z",
      },
      PROFILE,
      "2026-06-24T10:00:00.000Z",
    );
    const disguised: Document = { ...quote, type: "factura" };

    expect(() => markDocumentPaid(disguised)).toThrow(
      "no es válida para este tipo de documento",
    );
    expect(() =>
      buildReceiptFromInvoice(disguised, PROFILE),
    ).toThrow("factura canónica");
  });

  it("rechaza cualquier factura rectificativa aunque figure cobrada", () => {
    const rectification = markDocumentPaid(
      issueDocument(
        {
          id: "rectification-paid",
          type: "factura",
          number: "FR-2026-0001",
          date: "2026-06-10",
          client: { ...invoice.client },
          items: invoice.items.map((item) => ({
            ...item,
            id: `rect-${item.id}`,
            unitPrice: -item.unitPrice,
          })),
          rectification: {
            originalDocumentId: invoice.id,
            originalNumber: invoice.number,
            originalDate: invoice.date,
            reason: "Anulación",
            type: "anulacion",
          },
          status: "borrador",
          documentLifecycle: "draft",
          integrityLock: "unlocked",
          createdAt: "2026-06-10T09:00:00.000Z",
          updatedAt: "2026-06-10T09:00:00.000Z",
        },
        PROFILE,
        "2026-06-10T09:00:00.000Z",
      ),
      "2026-06-10T10:00:00.000Z",
    );

    expect(() => buildReceiptFromInvoice(rectification, PROFILE)).toThrow(
      "rectificativa no puede generar un recibo",
    );
  });

  it("nunca fecha el recibo antes que una factura futura", () => {
    const futureInvoice = issueDocument(
      {
        id: "future-invoice",
        type: "factura",
        number: "F-2999-0001",
        date: "2999-12-31",
        client: { ...invoice.client },
        items: invoice.items.map((item) => ({ ...item, id: `future-${item.id}` })),
        status: "borrador",
        createdAt: "2026-06-10T09:00:00.000Z",
        updatedAt: "2026-06-10T09:00:00.000Z",
      },
      PROFILE,
      "2026-06-10T09:00:00.000Z",
    );

    const receipt = buildReceiptFromInvoice(futureInvoice, PROFILE);

    expect(receipt.date).toBe(futureInvoice.documentSnapshot!.date);
    expect(receipt.date >= futureInvoice.documentSnapshot!.date).toBe(true);
  });

  it("no deriva recibos de una factura histórica fiscalmente inválida", () => {
    const source = (
      id: string,
      overrides: Partial<Document>,
      profile = PROFILE,
    ) =>
      issueDocument(
        {
          id,
          type: "factura",
          number: `F-2026-${id}`,
          date: "2026-06-10",
          client: { ...invoice.client },
          items: invoice.items.map((item) => ({ ...item, id: `${id}-line` })),
          status: "borrador",
          createdAt: "2026-06-10T09:00:00.000Z",
          updatedAt: "2026-06-10T09:00:00.000Z",
          ...overrides,
        },
        profile,
        "2026-06-10T09:00:00.000Z",
      );

    const invalidVat = source("invalid-vat", {
      items: [{ ...invoice.items[0], id: "invalid-vat-line", ivaPercent: -1 }],
    });
    const negativeOrdinary = source("negative", {
      items: [{ ...invoice.items[0], id: "negative-line", unitPrice: -100 }],
    });
    const incompleteClient = source("incomplete-client", {
      client: { name: "Cliente incompleto" },
    });
    const blankConcept = source("blank-concept", {
      items: [{ ...invoice.items[0], id: "blank-line", description: " " }],
    });
    const incompleteProfile = {
      ...PROFILE,
      name: "",
      address: "",
      postalCode: "",
      city: "",
    };
    const incompleteIssuer = source("incomplete-issuer", {}, incompleteProfile);

    expect(() => buildReceiptFromInvoice(invalidVat, PROFILE)).toThrow("IVA");
    expect(() => buildReceiptFromInvoice(negativeOrdinary, PROFILE)).toThrow(
      "totales negativos",
    );
    expect(() => buildReceiptFromInvoice(incompleteClient, PROFILE)).toThrow(
      "Completa estos datos del cliente",
    );
    expect(() => buildReceiptFromInvoice(blankConcept, PROFILE)).toThrow(
      "Añade al menos un concepto",
    );
    expect(() =>
      buildReceiptFromInvoice(incompleteIssuer, incompleteProfile),
    ).toThrow("Revisa estos datos");
  });

  it("bloquea un recibo si el redondeo legacy de origen no es reproducible", () => {
    const fractional = issueDocument(
      {
        ...invoice,
        id: "legacy-rounding-invoice",
        number: "F-2026-0099",
        status: "borrador",
        documentLifecycle: "draft",
        integrityLock: "unlocked",
        documentSnapshot: undefined,
        pdfSnapshot: undefined,
        snapshotSeal: undefined,
        snapshotIntegrityRequired: undefined,
        issuedAt: undefined,
        sentAt: undefined,
        paidAt: undefined,
        paymentStatus: undefined,
        items: [
          {
            id: "positive-line",
            description: "Servicio",
            quantity: 1,
            unitPrice: 1,
            ivaPercent: 0,
          },
          {
            id: "legacy-discount",
            description: "Descuento legacy",
            quantity: 1,
            unitPrice: -0.005,
            ivaPercent: 0,
          },
        ],
      },
      PROFILE,
      "2026-06-09T09:00:00.000Z",
    );
    const currentSnapshot = fractional.documentSnapshot!;
    const legacySnapshot = asLegacyDocumentSnapshot({
      ...currentSnapshot,
      items: currentSnapshot.items.map((item) =>
        item.id === "legacy-discount"
          ? { ...item, subtotal: 0, ivaAmount: 0, total: 0 }
          : item,
      ),
      taxSummary: {
        subtotal: 1,
        iva: 0,
        total: 1,
        vatExempt: false,
        byRate: [
          {
            ivaPercent: 0,
            taxableBase: 1,
            ivaAmount: 0,
            total: 1,
          },
        ],
      },
    });
    const legacyPdf = asLegacyPdfSnapshot(
      buildDocumentPdfSnapshot(
        legacySnapshot,
        PROFILE,
        "2026-06-09T09:00:00.000Z",
      ),
      legacySnapshot.snapshotHash,
    );
    const legacyInvoice: Document = {
      ...fractional,
      documentSnapshot: legacySnapshot,
      pdfSnapshot: legacyPdf,
      snapshotSeal: buildDocumentSnapshotSeal(
        fractional.id,
        legacySnapshot,
        legacyPdf,
      ),
      snapshotIntegrityRequired: true,
    };

    expect(() => buildReceiptFromInvoice(legacyInvoice, PROFILE)).toThrow(
      "no puede reproducir exactamente los importes congelados",
    );
  });
});

describe("receipt generation inspection and preparation", () => {
  const NOW = "2026-06-24T10:00:00.000Z";

  function paidSource(overrides: Partial<Document> = {}): Document {
    return {
      ...markDocumentPaid(invoice, NOW),
      ...overrides,
    };
  }

  function issuedReceiptFor(
    source: Document,
    id = "receipt-existing",
  ): Document {
    return markDocumentPaid(
      issueDocument(
        {
          ...buildReceiptFromInvoice(source, PROFILE, {
            now: NOW,
            createId: idSequence(`${id}-line`),
          }),
          id,
          number: "R-2026-0001",
          status: "borrador",
          createdAt: NOW,
          updatedAt: NOW,
        },
        PROFILE,
        NOW,
      ),
      NOW,
    );
  }

  it("distingue factura elegible y causas acotadas sin lanzar", () => {
    const paid = paidSource();
    expect(inspectReceiptGeneration([paid], paid.id)).toMatchObject({
      status: "eligible",
      invoice: paid,
    });
    expect(inspectReceiptGeneration([paid], "missing")).toEqual({
      status: "blocked",
      reason: "invoice_not_found",
    });
    expect(inspectReceiptGeneration([invoice], invoice.id)).toEqual({
      status: "blocked",
      reason: "invoice_not_collected",
    });

    const corrupt: Document = {
      ...paid,
      documentSnapshot: {
        ...paid.documentSnapshot!,
        number: "F-ALTERADA",
      },
    };
    expect(inspectReceiptGeneration([corrupt], corrupt.id)).toEqual({
      status: "blocked",
      reason: "invoice_integrity_blocked",
    });
    expect(inspectReceiptGeneration([paid, { ...paid }], paid.id)).toEqual({
      status: "blocked",
      reason: "source_invalid",
    });

    const orphan: Document = {
      ...paid,
      receiptDocumentId: "receipt-missing",
    };
    expect(inspectReceiptGeneration([orphan], orphan.id)).toEqual({
      status: "blocked",
      reason: "receipt_link_missing",
    });

    const firstClaim: Document = {
      ...paid,
      id: "receipt-claim-1",
      type: "recibo",
      number: "R-2026-0001",
      sourceDocumentId: paid.id,
    };
    const secondClaim: Document = {
      ...firstClaim,
      id: "receipt-claim-2",
      number: "R-2026-0002",
    };
    expect(
      inspectReceiptGeneration([paid, firstClaim, secondClaim], paid.id),
    ).toEqual({
      status: "blocked",
      reason: "receipt_link_ambiguous",
    });
  });

  it("identifica rectificativas cobradas positivas y negativas como no elegibles", () => {
    const original = issueDocument(
      {
        ...invoice,
        id: "rectification-original",
        number: "F-2026-0100",
        status: "borrador",
        documentLifecycle: "draft",
        integrityLock: "unlocked",
        documentSnapshot: undefined,
        pdfSnapshot: undefined,
        snapshotSeal: undefined,
        snapshotIntegrityRequired: undefined,
        issuedAt: undefined,
      },
      PROFILE,
      NOW,
    );
    const rectification = markDocumentPaid(
      issueDocument(
        {
          id: "rectification-paid",
          type: "factura",
          number: "FR-2026-0001",
          date: "2026-06-24",
          client: { ...original.client },
          items: original.items.map((item) => ({
            ...item,
            id: `rect-${item.id}`,
          })),
          rectification: {
            originalDocumentId: original.id,
            originalNumber: original.number,
            originalDate: original.date,
            reason: "Corrección",
            type: "correccion",
          },
          status: "borrador",
          documentLifecycle: "draft",
          integrityLock: "unlocked",
          createdAt: NOW,
          updatedAt: NOW,
        },
        PROFILE,
        NOW,
      ),
      NOW,
    );
    const linkedOriginal: Document = {
      ...original,
      status: "rectificada",
      rectifiedById: rectification.id,
    };

    expect(
      inspectReceiptGeneration(
        [linkedOriginal, rectification],
        rectification.id,
      ),
    ).toEqual({ status: "blocked", reason: "invoice_rectification" });

    const annulment = markDocumentPaid(
      issueDocument(
        {
          id: "annulment-paid",
          type: "factura",
          number: "FR-2026-0002",
          date: "2026-06-24",
          client: { ...original.client },
          items: original.items.map((item) => ({
            ...item,
            id: `annul-${item.id}`,
            unitPrice: -item.unitPrice,
          })),
          rectification: {
            originalDocumentId: original.id,
            originalNumber: original.number,
            originalDate: original.date,
            reason: "Anulación completa",
            type: "anulacion",
          },
          status: "borrador",
          documentLifecycle: "draft",
          integrityLock: "unlocked",
          createdAt: NOW,
          updatedAt: NOW,
        },
        PROFILE,
        NOW,
      ),
      NOW,
    );
    const canceledOriginal: Document = {
      ...original,
      status: "anulada",
      documentLifecycle: "canceled",
      rectifiedById: annulment.id,
    };

    expect(
      inspectReceiptGeneration(
        [canceledOriginal, annulment],
        annulment.id,
      ),
    ).toEqual({ status: "blocked", reason: "invoice_rectification" });
  });

  it("prepara un recibo canónico sin mutar ni reemitir la factura origen", () => {
    const source = paidSource();
    const data = appDataWithDocuments([source]);
    const result = prepareReceiptGeneration(data, source.id, {
      now: NOW,
      createId: idSequence("receipt-new", "receipt-new-line"),
    });

    expect(result.status).toBe("ready");
    if (result.status !== "ready") return;

    expect(data.documents).toEqual([source]);
    expect(data.documents[0].receiptDocumentId).toBeUndefined();
    expect(result.receipt).toMatchObject({
      id: "receipt-new",
      number: "R-2026-0001",
      type: "recibo",
      status: "pagado",
      paymentStatus: "paid",
      sourceDocumentId: source.id,
    });
    expect(result.receipt.items[0].id).toBe("receipt-new-line");
    expect(result.receipt.documentSnapshot?.sourceDocumentId).toBe(source.id);
    expect(
      Object.prototype.hasOwnProperty.call(
        result.receipt.documentSnapshot!,
        "sourceDocumentId",
      ),
    ).toBe(true);
    expect(
      inspectDocumentSnapshotsIntegrity(result.receipt, {
        requireDocumentSnapshot: true,
        requirePdfSnapshot: true,
        requireSnapshotSeal: true,
      }).ok,
    ).toBe(true);

    const sourceAfter = result.data.documents.find(
      (document) => document.id === source.id,
    )!;
    expect(sourceAfter.receiptDocumentId).toBe(result.receipt.id);
    expect(sourceAfter.documentSnapshot).toBe(source.documentSnapshot);
    expect(sourceAfter.pdfSnapshot).toBe(source.pdfSnapshot);
    expect(sourceAfter.snapshotSeal).toBe(source.snapshotSeal);
    expect(sourceAfter.verifactu).toEqual(source.verifactu);
    expect(result.data.profile.numbering.lastSequence.recibo).toBe(1);
    expect(result.data.counters.recibo).toBe(1);
    expect(
      inspectReceiptGeneration(result.data.documents, source.id),
    ).toMatchObject({
      status: "existing",
      receipt: { id: result.receipt.id },
      integrityBlocked: false,
    });
  });

  it("mantiene un recibo legacy sin origen congelado bloqueado y no lo resella", () => {
    const source = paidSource();
    const currentReceipt = issuedReceiptFor(source, "receipt-legacy");
    const snapshotWithoutOrigin = {
      ...currentReceipt.documentSnapshot!,
    } as Record<string, unknown>;
    delete snapshotWithoutOrigin.sourceDocumentId;
    const legacySnapshot = asLegacyDocumentSnapshot(
      snapshotWithoutOrigin as unknown as DocumentSnapshot,
    );
    const legacyPdf = asLegacyPdfSnapshot(
      buildDocumentPdfSnapshot(legacySnapshot, PROFILE, NOW),
      legacySnapshot.snapshotHash,
    );
    const legacyReceipt: Document = {
      ...currentReceipt,
      documentSnapshot: legacySnapshot,
      pdfSnapshot: legacyPdf,
      snapshotSeal: buildDocumentSnapshotSeal(
        currentReceipt.id,
        legacySnapshot,
        legacyPdf,
      ),
    };
    const linkedSource: Document = {
      ...source,
      receiptDocumentId: legacyReceipt.id,
    };
    const originalSnapshot = legacyReceipt.documentSnapshot;
    const originalSeal = legacyReceipt.snapshotSeal;
    const data = appDataWithDocuments([linkedSource, legacyReceipt]);

    expect(
      Object.prototype.hasOwnProperty.call(
        legacyReceipt.documentSnapshot!,
        "sourceDocumentId",
      ),
    ).toBe(false);
    expect(
      inspectReceiptGeneration(data.documents, linkedSource.id),
    ).toMatchObject({
      status: "existing",
      receipt: legacyReceipt,
      integrityBlocked: true,
    });
    const checkedLegacyReceipt = withDocumentRelationshipIntegritySignals(
      data.documents,
    ).find((document) => document.id === legacyReceipt.id)!;
    expect(checkedLegacyReceipt.snapshotIntegrity?.status).toBe("blocked");
    expect(documentAmounts(checkedLegacyReceipt, false).total).toBe(0);
    const normalizedForDisplay = withDocumentRelationshipIntegritySignals(
      data.documents,
    );
    expect(
      inspectReceiptGenerationForDisplay(
        normalizedForDisplay,
        linkedSource.id,
      ),
    ).toMatchObject({
      status: "existing",
      receipt: { id: legacyReceipt.id },
      integrityBlocked: true,
    });
    expect(
      prepareReceiptGeneration(data, linkedSource.id, {
        now: NOW,
        createId: idSequence("must-not-be-used"),
      }),
    ).toMatchObject({
      status: "existing",
      receipt: legacyReceipt,
      integrityBlocked: true,
    });
    expect(legacyReceipt.documentSnapshot).toBe(originalSnapshot);
    expect(legacyReceipt.snapshotSeal).toBe(originalSeal);
    expect(data.documents).toEqual([linkedSource, legacyReceipt]);
  });

  it("bloquea el candidato si la validación final detecta una identidad fiscal duplicada", () => {
    const source = paidSource();
    const hiddenReceipt = markDocumentPaid(
      issueDocument(
        {
          id: "hidden-receipt",
          type: "recibo",
          number: "R-2026-0001",
          date: "2026-06-24",
          client: { ...source.client },
          items: source.items.map((item) => ({
            ...item,
            id: `hidden-${item.id}`,
          })),
          status: "borrador",
          createdAt: NOW,
          updatedAt: NOW,
        },
        PROFILE,
        NOW,
      ),
      NOW,
    );
    const typeDriftedHiddenReceipt: Document = {
      ...hiddenReceipt,
      type: "factura",
    };
    const data = appDataWithDocuments([source, typeDriftedHiddenReceipt]);

    expect(
      prepareReceiptGeneration(data, source.id, {
        now: NOW,
        createId: idSequence("receipt-candidate", "candidate-line"),
      }),
    ).toEqual({
      status: "blocked",
      reason: "generated_relationship_invalid",
    });
    expect(data.documents).toEqual([source, typeDriftedHiddenReceipt]);
  });

  it("rechaza colisiones de ID antes de construir o publicar el candidato", () => {
    const source = paidSource();
    const data = appDataWithDocuments([source]);

    expect(
      prepareReceiptGeneration(data, source.id, {
        now: NOW,
        createId: idSequence(source.id),
      }),
    ).toEqual({ status: "blocked", reason: "source_invalid" });
    expect(data.documents).toEqual([source]);
  });
});

describe("isAutoGeneratedReceipt", () => {
  it("evita duplicar un recibo vinculado aunque su origen no esté acreditado", () => {
    const autoReceipt: Document = {
      ...invoice,
      id: "r1",
      type: "recibo",
      number: "R-2026-0001",
      status: "pagado",
      sourceDocumentId: "inv-1",
    };
    expect(isAutoGeneratedReceipt(autoReceipt)).toBe(true);
    expect(hasFrozenAutoGeneratedReceiptOrigin(autoReceipt)).toBe(false);
    expect(isCollectedDocument(autoReceipt)).toBe(false);
    expect(isCollectedDocument({ ...invoice, status: "pagado" })).toBe(true);
  });

  it("excluye un recibo automático nuevo con origen congelado", () => {
    const receipt = markDocumentPaid(
      issueDocument(
        {
          ...buildReceiptFromInvoice(invoice, PROFILE),
          id: "receipt-sealed",
          number: "R-2026-0001",
          status: "borrador",
          createdAt: "2026-06-24T10:00:00.000Z",
          updatedAt: "2026-06-24T10:00:00.000Z",
        },
        PROFILE,
        "2026-06-24T10:00:00.000Z",
      ),
      "2026-06-24T10:05:00.000Z",
    );

    expect(isAutoGeneratedReceipt(receipt)).toBe(true);
    expect(hasFrozenAutoGeneratedReceiptOrigin(receipt)).toBe(true);
    expect(isCollectedDocument(receipt)).toBe(false);

    const frozenOnly: Document = {
      ...receipt,
      sourceDocumentId: undefined,
    };
    expect(isAutoGeneratedReceipt(frozenOnly)).toBe(true);
    expect(isCollectedDocument(frozenOnly)).toBe(false);
  });

  it("clasifica como recibo un payload cuyo tipo vivo contradice el snapshot", () => {
    const receipt = markDocumentPaid(
      issueDocument(
        {
          ...buildReceiptFromInvoice(invoice, PROFILE),
          id: "receipt-type-drift",
          number: "R-2026-0009",
          status: "borrador",
          createdAt: "2026-06-24T10:00:00.000Z",
          updatedAt: "2026-06-24T10:00:00.000Z",
        },
        PROFILE,
        "2026-06-24T10:00:00.000Z",
      ),
      "2026-06-24T10:05:00.000Z",
    );
    const drifted: Document = { ...receipt, type: "factura" };

    expect(isAutoGeneratedReceipt(drifted)).toBe(true);
    expect(isCollectedDocument(drifted)).toBe(false);
    expect(findReceiptForInvoice([drifted], invoice.id)).toBe(drifted);
  });
});

describe("unmarkInvoiceCollection", () => {
  function paidInvoiceWithReceipt(receipt: Document): Document {
    return markDocumentPaid(
      { ...invoice, receiptDocumentId: receipt.id },
      "2026-06-24T10:00:00.000Z",
    );
  }

  function draftReceipt(overrides: Partial<Document> = {}): Document {
    return {
      ...buildReceiptFromInvoice(invoice, PROFILE),
      id: "receipt-draft",
      number: "R-2026-0001",
      status: "borrador",
      createdAt: "2026-06-24T09:00:00.000Z",
      updatedAt: "2026-06-24T09:00:00.000Z",
      ...overrides,
    };
  }

  function emittedReceipt(overrides: Partial<Document> = {}): Document {
    return markDocumentPaid(
      issueDocument(
        draftReceipt({
          id: "receipt-issued",
          number: "R-2026-0001",
          ...overrides,
        }),
        PROFILE,
        "2026-06-24T10:00:00.000Z",
      ),
      "2026-06-24T10:05:00.000Z",
    );
  }

  it("encuentra un recibo sellado aunque se borren los vínculos vivos", () => {
    const receipt = emittedReceipt();
    const frozenOnlyReceipt: Document = {
      ...receipt,
      sourceDocumentId: undefined,
    };

    expect(
      findReceiptForInvoice([frozenOnlyReceipt], invoice.id),
    ).toBe(frozenOnlyReceipt);
  });

  it("no muta una factura cuya integridad está bloqueada", () => {
    const paid = markDocumentPaid(invoice, "2026-06-24T10:00:00.000Z");
    const corrupt: Document = {
      ...paid,
      documentSnapshot: {
        ...paid.documentSnapshot!,
        number: "F-ALTERADA",
      },
    };
    const documents = [corrupt];

    const result = unmarkInvoiceCollection(
      documents,
      corrupt.id,
      "enviado",
      "2026-06-24T11:00:00.000Z",
    );

    expect(result.documents).toBe(documents);
    expect(result.documents[0].status).toBe("pagado");
  });

  it("no muta una factura bloqueada por su relación documental", () => {
    const blocked: Document = {
      ...markDocumentPaid(invoice, "2026-06-24T10:00:00.000Z"),
      snapshotIntegrity: {
        status: "blocked",
        issues: ["document_relationship_invalid"],
      },
    };
    const documents = [blocked];

    const result = unmarkInvoiceCollection(
      documents,
      blocked.id,
      "enviado",
      "2026-06-24T11:00:00.000Z",
    );

    expect(result.documents).toBe(documents);
    expect(result.documents[0]).toBe(blocked);
  });

  it("valida el grafo y no muta una identidad fiscal duplicada", () => {
    const paid = markDocumentPaid(invoice, "2026-06-24T10:00:00.000Z");
    const duplicateIdentity = markDocumentPaid(
      issueDocument(
        {
          id: "duplicate-fiscal-identity",
          type: "factura",
          number: invoice.number,
          date: invoice.date,
          client: { ...invoice.client },
          items: invoice.items.map((item) => ({
            ...item,
            id: `duplicate-${item.id}`,
          })),
          status: "borrador",
          createdAt: "2026-06-24T09:00:00.000Z",
          updatedAt: "2026-06-24T09:00:00.000Z",
        },
        PROFILE,
        "2026-06-24T09:00:00.000Z",
      ),
      "2026-06-24T10:00:00.000Z",
    );
    const documents = [paid, duplicateIdentity];

    const result = unmarkInvoiceCollection(
      documents,
      paid.id,
      "enviado",
      "2026-06-24T11:00:00.000Z",
    );

    expect(result.documents).toBe(documents);
    expect(result.documents[0].status).toBe("pagado");
  });

  it("rechaza una colisión fiscal entre factura sellada y copia legacy", () => {
    const paid = markDocumentPaid(invoice, "2026-06-24T10:00:00.000Z");
    const legacyDuplicate: Document = {
      ...paid,
      id: "legacy-duplicate",
      pdfSnapshot: undefined,
      snapshotSeal: undefined,
      snapshotIntegrityRequired: undefined,
    };

    expect(
      findUniqueReceiptSourceInvoice(
        [paid, legacyDuplicate],
        paid.id,
      ),
    ).toBeUndefined();
  });

  it("exige que el ID de factura aparezca exactamente una vez", () => {
    const paid = markDocumentPaid(invoice, "2026-06-24T10:00:00.000Z");
    const duplicateId: Document = { ...paid };
    const documents = [paid, duplicateId];

    const result = unmarkInvoiceCollection(
      documents,
      paid.id,
      "enviado",
      "2026-06-24T11:00:00.000Z",
    );

    expect(result.documents).toBe(documents);
    expect(result.documents).toEqual([paid, duplicateId]);
    expect(findUniqueReceiptSourceInvoice(documents, paid.id)).toBeUndefined();
  });

  it("no elimina un recibo emitido si comparte ID con un borrador", () => {
    const removableReceipt = draftReceipt({ id: "receipt-duplicated" });
    const protectedReceipt = emittedReceipt({
      id: removableReceipt.id,
      number: "R-2026-0099",
    });
    const paidInvoice = paidInvoiceWithReceipt(removableReceipt);
    const documents = [paidInvoice, removableReceipt, protectedReceipt];

    const result = unmarkInvoiceCollection(
      documents,
      paidInvoice.id,
      "enviado",
      "2026-06-24T11:00:00.000Z",
      EMPTY_DATA.profile.numbering,
    );

    expect(result.documents).toBe(documents);
    expect(result.removedReceiptId).toBeUndefined();
    expect(result.documents).toContain(removableReceipt);
    expect(result.documents).toContain(protectedReceipt);
    expect(result.documents[0]).toBe(paidInvoice);
  });

  it("no desmarca si varios recibos reclaman la misma factura", () => {
    const firstReceipt = draftReceipt({ id: "receipt-first" });
    const secondReceipt = draftReceipt({ id: "receipt-second" });
    const paidInvoice = paidInvoiceWithReceipt(firstReceipt);
    const documents = [paidInvoice, firstReceipt, secondReceipt];

    const result = unmarkInvoiceCollection(
      documents,
      paidInvoice.id,
      "enviado",
      "2026-06-24T11:00:00.000Z",
      EMPTY_DATA.profile.numbering,
    );

    expect(result.documents).toBe(documents);
    expect(result.removedReceiptId).toBeUndefined();
    expect(
      findReceiptForInvoice(documents, paidInvoice.id, firstReceipt.id),
    ).toBeUndefined();
  });

  it("no desmarca un backlink huérfano o dirigido a otro tipo", () => {
    const paid = markDocumentPaid(
      { ...invoice, receiptDocumentId: "missing-receipt" },
      "2026-06-24T10:00:00.000Z",
    );
    const quote: Document = {
      ...invoice,
      id: "quote-target",
      type: "presupuesto",
      number: "P-2026-0001",
      documentSnapshot: undefined,
      pdfSnapshot: undefined,
      snapshotSeal: undefined,
      snapshotIntegrityRequired: undefined,
      status: "borrador",
    };

    const orphanDocuments = [paid];
    expect(
      unmarkInvoiceCollection(
        orphanDocuments,
        paid.id,
        "enviado",
        "2026-06-24T11:00:00.000Z",
      ).documents,
    ).toBe(orphanDocuments);

    const wrongTypeInvoice: Document = {
      ...paid,
      receiptDocumentId: quote.id,
    };
    const wrongTypeDocuments = [wrongTypeInvoice, quote];
    expect(
      unmarkInvoiceCollection(
        wrongTypeDocuments,
        wrongTypeInvoice.id,
        "enviado",
        "2026-06-24T11:00:00.000Z",
      ).documents,
    ).toBe(wrongTypeDocuments);
  });

  it("desmarcar cobro con recibo borrador puede eliminarlo sin tocar emitidos", () => {
    const removableReceipt = draftReceipt();
    const protectedReceipt = emittedReceipt({
      id: "receipt-issued",
      number: "R-2026-0002",
      sourceDocumentId: "other-invoice",
    });
    const paidInvoice = paidInvoiceWithReceipt(removableReceipt);

    const result = unmarkInvoiceCollection(
      [paidInvoice, removableReceipt, protectedReceipt],
      paidInvoice.id,
      "enviado",
      "2026-06-24T11:00:00.000Z",
      EMPTY_DATA.profile.numbering,
    );

    expect(result.removedReceiptId).toBe(removableReceipt.id);
    expect(result.documents.some((doc) => doc.id === removableReceipt.id)).toBe(
      false,
    );
    expect(result.documents.find((doc) => doc.id === protectedReceipt.id)).toBe(
      protectedReceipt,
    );
    expect(result.documents.find((doc) => doc.id === paidInvoice.id)).toMatchObject({
      status: "enviado",
      paymentStatus: "pending",
      paidAt: undefined,
      receiptDocumentId: undefined,
    });
  });

  it("no desmarca el cobro mientras exista un recibo emitido", () => {
    const receipt = emittedReceipt();
    const paidInvoice = paidInvoiceWithReceipt(receipt);
    const secondReceipt = emittedReceipt({
      id: "receipt-2",
      number: "R-2026-0003",
      sourceDocumentId: "other-invoice",
    });

    const result = unmarkInvoiceCollection(
      [paidInvoice, receipt, secondReceipt],
      paidInvoice.id,
      "enviado",
      "2026-06-24T11:00:00.000Z",
      EMPTY_DATA.profile.numbering,
    );

    expect(result.preservedReceiptId).toBe(receipt.id);
    expect(result.removedReceiptId).toBeUndefined();
    expect(result.documents.find((doc) => doc.id === receipt.id)).toBe(receipt);
    expect(result.documents.find((doc) => doc.id === secondReceipt.id)?.number).toBe(
      "R-2026-0003",
    );
    expect(result.documents.find((doc) => doc.id === paidInvoice.id)).toBe(
      paidInvoice,
    );
  });

  it("desmarcar cobro no altera snapshot/hash de factura", () => {
    const receipt = emittedReceipt();
    const paidInvoice = paidInvoiceWithReceipt(receipt);
    const snapshotHash = paidInvoice.documentSnapshot?.snapshotHash;
    const contentHash = paidInvoice.pdfSnapshot?.contentHash;

    const result = unmarkInvoiceCollection(
      [paidInvoice, receipt],
      paidInvoice.id,
      "enviado",
      "2026-06-24T11:00:00.000Z",
      EMPTY_DATA.profile.numbering,
    );
    const invoiceAfter = result.documents.find((doc) => doc.id === paidInvoice.id);

    expect(invoiceAfter?.documentSnapshot).toBe(paidInvoice.documentSnapshot);
    expect(invoiceAfter?.pdfSnapshot).toBe(paidInvoice.pdfSnapshot);
    expect(invoiceAfter?.documentSnapshot?.snapshotHash).toBe(snapshotHash);
    expect(invoiceAfter?.pdfSnapshot?.contentHash).toBe(contentHash);
  });

  it("desmarcar cobro no altera snapshot/hash de recibo emitido", () => {
    const receipt = emittedReceipt();
    const paidInvoice = paidInvoiceWithReceipt(receipt);
    const snapshotHash = receipt.documentSnapshot?.snapshotHash;
    const contentHash = receipt.pdfSnapshot?.contentHash;

    const result = unmarkInvoiceCollection(
      [paidInvoice, receipt],
      paidInvoice.id,
      "enviado",
      "2026-06-24T11:00:00.000Z",
      EMPTY_DATA.profile.numbering,
    );
    const receiptAfter = result.documents.find((doc) => doc.id === receipt.id);

    expect(receiptAfter).toBe(receipt);
    expect(receiptAfter?.documentSnapshot?.snapshotHash).toBe(snapshotHash);
    expect(receiptAfter?.pdfSnapshot?.contentHash).toBe(contentHash);
  });
});
