import { roundMoney } from "./calculations";
import { selectCanonicalFiscalDocumentsForExport } from "./billing/fiscal-export-documents";
import { isAutoGeneratedReceipt } from "./receipts";
import {
  DEFAULT_PROFILE,
  type BusinessProfile,
  type Document,
  type Expense,
} from "./types";
import { documentAmounts } from "./vat-regime";

export const DEFAULT_IRPF_PERCENT = 20;

export function normalizeIrpfPercent(value?: number): number {
  if (value === undefined || value === null || Number.isNaN(value)) {
    return DEFAULT_IRPF_PERCENT;
  }
  return Math.min(100, Math.max(0, value));
}

/** Facturas y recibos emitidos que generan base e IVA repercutido */
export function isTaxableSaleDocument(doc: Document): boolean {
  if (doc.type !== "factura" && doc.type !== "recibo") return false;
  if (doc.status === "borrador" || doc.status === "anulada") return false;
  if (doc.rectifiedById) return false;
  if (isAutoGeneratedReceipt(doc)) return false;
  return true;
}

export function expenseIvaAmount(expense: Expense): number {
  const amount = Number.isFinite(expense.amount) ? expense.amount : 0;
  const ivaPercent = Number.isFinite(expense.ivaPercent)
    ? expense.ivaPercent
    : 0;
  return roundMoney(amount * (ivaPercent / 100));
}

export interface TaxSummary {
  vatExempt: boolean;
  integrityBlockedDocuments: number;
  salesBase: number;
  salesIva: number;
  expenseBase: number;
  expenseIva: number;
  netIva: number;
  ivaToPay: number;
  ivaCredit: number;
  grossProfit: number;
  irpfPercent: number;
  irpfEstimate: number;
  estimatedNetProfit: number;
}

export interface TaxSummaryOptions {
  irpfPercent?: number;
  vatExempt?: boolean;
  profile?: BusinessProfile;
  isDocumentDateInPeriod?: (date: string) => boolean;
}

export function calculateTaxSummary(
  documents: Document[],
  expenses: Expense[],
  options: TaxSummaryOptions = {},
): TaxSummary {
  const irpfPercent = options.irpfPercent ?? DEFAULT_IRPF_PERCENT;
  const profile = options.profile ?? DEFAULT_PROFILE;
  const vatExempt = options.vatExempt ?? Boolean(profile.vatExempt);
  const fiscalSelection = selectCanonicalFiscalDocumentsForExport(
    documents,
    profile,
    options.isDocumentDateInPeriod ?? (() => true),
  );
  const integrityBlockedDocuments = fiscalSelection.blockedDocuments.length;
  const sales = fiscalSelection.documents.filter(isTaxableSaleDocument);
  const salesAmounts = sales.map((document) =>
    documentAmounts(document, vatExempt),
  );

  const salesBase = salesAmounts.reduce(
    (sum, amounts) => sum + amounts.subtotal,
    0,
  );
  const salesIva = salesAmounts.reduce(
    (sum, amounts) => sum + amounts.iva,
    0,
  );

  const expenseBase = expenses.reduce((sum, expense) => sum + expense.amount, 0);
  const expenseIva = vatExempt
    ? 0
    : expenses.reduce((sum, expense) => sum + expenseIvaAmount(expense), 0);

  const netIva = salesIva - expenseIva;
  const ivaToPay = Math.max(0, netIva);
  const ivaCredit = Math.max(0, -netIva);

  const grossProfit = salesBase - expenseBase;
  const rate = normalizeIrpfPercent(irpfPercent);
  const irpfEstimate = grossProfit > 0 ? grossProfit * (rate / 100) : 0;
  const estimatedNetProfit = grossProfit - irpfEstimate - ivaToPay;

  return {
    vatExempt,
    integrityBlockedDocuments,
    salesBase,
    salesIva,
    expenseBase,
    expenseIva,
    netIva,
    ivaToPay,
    ivaCredit,
    grossProfit,
    irpfPercent: rate,
    irpfEstimate,
    estimatedNetProfit,
  };
}
