import { selectCanonicalFiscalDocumentsForExport } from "./billing/fiscal-export-documents";
import { expenseFiscalAmounts } from "./expenses";
import { isAutoGeneratedReceipt } from "./receipts";
import {
  DEFAULT_PROFILE,
  type BusinessProfile,
  type Document,
  type Expense,
} from "./types";
import { documentAmounts } from "./vat-regime";

export const DEFAULT_IRPF_PERCENT = 20;

export function normalizeIrpfPercent(value?: number): number {
  if (value === undefined || value === null || Number.isNaN(value)) {
    return DEFAULT_IRPF_PERCENT;
  }
  return Math.min(100, Math.max(0, value));
}

/** Facturas y recibos emitidos que generan base e IVA repercutido */
export function isTaxableSaleDocument(doc: Document): boolean {
  if (doc.type !== "factura" && doc.type !== "recibo") return false;
  if (doc.status === "borrador" || doc.status === "anulada") return false;
  if (doc.rectifiedById) return false;
  if (isAutoGeneratedReceipt(doc)) return false;
  return true;
}

/**
 * Resuelve una cadena ya canonizada dentro de un periodo fiscal aislado.
 * Una corrección sustituye a su original cuando ambas fechas caen en el
 * periodo; una anulación conserva original y abono para que se compensen.
 * Las correcciones interperiodo se excluyen hasta poder expresar una
 * diferencia fiscal auditable, en lugar de imputar el total corregido otra vez.
 */
export function taxableSaleDocumentsForPeriod(documents: Document[]): {
  documents: Document[];
  unsupportedRectificationDocuments: number;
} {
  const byId = new Map(documents.map((document) => [document.id, document]));
  let unsupportedRectificationDocuments = 0;
  const selected = documents.filter((document) => {
    if (document.snapshotIntegrity?.status === "blocked") return false;

    const baseSale =
      (document.type === "factura" || document.type === "recibo") &&
      document.status !== "borrador" &&
      !isAutoGeneratedReceipt(document);
    if (!baseSale) return false;

    if (document.rectification) {
      if (
        document.rectification.type === "correccion" &&
        !byId.has(document.rectification.originalDocumentId)
      ) {
        unsupportedRectificationDocuments += 1;
        return false;
      }
      return true;
    }

    if (document.rectifiedById) {
      const rectification = byId.get(document.rectifiedById);
      if (!rectification) return true;
      return rectification.rectification?.type === "anulacion";
    }

    return document.status !== "anulada";
  });

  return { documents: selected, unsupportedRectificationDocuments };
}

export function expenseIvaAmount(expense: Expense): number {
  return expenseFiscalAmounts(expense).deductibleIva;
}

export interface TaxSummary {
  vatExempt: boolean;
  integrityBlockedDocuments: number;
  unsupportedRectificationDocuments: number;
  /** Gastos cuyo IVA procede de un desglose por líneas conciliado. */
  lineVatExpenseCount: number;
  /** Gastos que usan cabecera o el contrato de importe íntegro P1-06. */
  headerVatExpenseCount: number;
  /** Evidencia fiscal de gastos (líneas o resumen) que no puede conciliarse. */
  unsupportedMixedVatExpenses: number;
  salesBase: number;
  salesIva: number;
  /** Gasto neto que reduce la estimación orientativa de IRPF. */
  expenseBase: number;
  /** IVA deducible estimado; excluye gastos no deducibles. */
  expenseIva: number;
  /**
   * Coste económico de los gastos: base si el IVA es deducible y total
   * registrado cuando el gasto no es deducible.
   */
  operatingExpenseCost: number;
  nonDeductibleExpenseCount: number;
  nonDeductibleExpenseTotal: number;
  netIva: number;
  ivaToPay: number;
  ivaCredit: number;
  /** Beneficio económico antes de reservar IRPF; la posición de IVA va aparte. */
  grossProfit: number;
  /** Base orientativa de IRPF: ventas menos base de gastos deducible. */
  estimatedIrpfBase: number;
  irpfPercent: number;
  irpfEstimate: number;
  /** Resultado tras reservar el IRPF estimado; la posición de IVA va aparte. */
  profitAfterIrpfReserve: number;
}

export interface TaxSummaryOptions {
  irpfPercent?: number;
  vatExempt?: boolean;
  profile?: BusinessProfile;
  isDocumentDateInPeriod?: (date: string) => boolean;
}

export interface TaxableFiscalDocumentSelection {
  documents: Document[];
  integrityBlockedDocuments: number;
  unsupportedRectificationDocuments: number;
}

/**
 * Única selección de ventas permitida para cifras fiscales y sus resúmenes UI.
 * Recalcula snapshots y relaciones antes de devolver documentos canónicos.
 */
export function selectTaxableFiscalDocumentsForPeriod(
  documents: Document[],
  options: Pick<
    TaxSummaryOptions,
    "profile" | "isDocumentDateInPeriod"
  > = {},
): TaxableFiscalDocumentSelection {
  const fiscalSelection = selectCanonicalFiscalDocumentsForExport(
    documents,
    options.profile ?? DEFAULT_PROFILE,
    options.isDocumentDateInPeriod ?? (() => true),
  );
  const resolvedSales = taxableSaleDocumentsForPeriod(
    fiscalSelection.documents,
  );

  return {
    documents: resolvedSales.documents,
    integrityBlockedDocuments: fiscalSelection.blockedDocuments.length,
    unsupportedRectificationDocuments:
      resolvedSales.unsupportedRectificationDocuments,
  };
}

export class TaxExportBlockedError extends Error {
  readonly integrityBlockedDocuments: number;
  readonly unsupportedRectificationDocuments: number;
  readonly unsupportedMixedVatExpenses: number;

  constructor(
    summary: Pick<
      TaxSummary,
      | "integrityBlockedDocuments"
      | "unsupportedRectificationDocuments"
      | "unsupportedMixedVatExpenses"
    >,
  ) {
    super(
      "No se puede exportar un resumen fiscal incompleto. Revisa los documentos bloqueados, las rectificativas interperiodo y los gastos con evidencia fiscal sin conciliar.",
    );
    this.name = "TaxExportBlockedError";
    this.integrityBlockedDocuments = summary.integrityBlockedDocuments;
    this.unsupportedRectificationDocuments =
      summary.unsupportedRectificationDocuments;
    this.unsupportedMixedVatExpenses = summary.unsupportedMixedVatExpenses;
  }
}

export function assertTaxSummaryExportable(
  summary: Pick<
    TaxSummary,
    | "integrityBlockedDocuments"
    | "unsupportedRectificationDocuments"
    | "unsupportedMixedVatExpenses"
  >,
): void {
  if (
    summary.integrityBlockedDocuments > 0 ||
    summary.unsupportedRectificationDocuments > 0 ||
    summary.unsupportedMixedVatExpenses > 0
  ) {
    throw new TaxExportBlockedError(summary);
  }
}

export function calculateTaxSummary(
  documents: Document[],
  expenses: Expense[],
  options: TaxSummaryOptions = {},
): TaxSummary {
  const irpfPercent = options.irpfPercent ?? DEFAULT_IRPF_PERCENT;
  const profile = options.profile ?? DEFAULT_PROFILE;
  const vatExempt = options.vatExempt ?? Boolean(profile.vatExempt);
  const fiscalSelection = selectTaxableFiscalDocumentsForPeriod(
    documents,
    {
      profile,
      isDocumentDateInPeriod: options.isDocumentDateInPeriod,
    },
  );
  const sales = fiscalSelection.documents;
  const salesAmounts = sales.map((document) =>
    documentAmounts(document, vatExempt),
  );

  const salesBase = salesAmounts.reduce(
    (sum, amounts) => sum + amounts.subtotal,
    0,
  );
  const salesIva = salesAmounts.reduce(
    (sum, amounts) => sum + amounts.iva,
    0,
  );

  const expenseFiscalRows = expenses.map((expense) =>
    expenseFiscalAmounts(expense, vatExempt),
  );
  const expenseBase = expenseFiscalRows.reduce(
    (sum, expense) => sum + expense.deductibleIrpfExpense,
    0,
  );
  const expenseIva = expenseFiscalRows.reduce(
    (sum, expense) => sum + expense.deductibleIva,
    0,
  );
  const operatingExpenseCost = expenseFiscalRows.reduce(
    (sum, expense) => sum + expense.operatingCost,
    0,
  );
  const nonDeductibleExpenses = expenseFiscalRows.filter(
    (expense) => !expense.deductible,
  );
  const nonDeductibleExpenseTotal = nonDeductibleExpenses.reduce(
    (sum, expense) => sum + expense.registeredTotal,
    0,
  );
  const lineVatExpenseCount = expenseFiscalRows.filter(
    (expense) => expense.vatSource === "lines",
  ).length;
  const headerVatExpenseCount = expenseFiscalRows.filter(
    (expense) => expense.vatSource === "header",
  ).length;
  const unsupportedMixedVatExpenses = expenseFiscalRows.filter(
    (expense) => expense.vatBlocked,
  ).length;

  const netIva = salesIva - expenseIva;
  const ivaToPay = Math.max(0, netIva);
  const ivaCredit = Math.max(0, -netIva);

  const grossProfit = salesBase - operatingExpenseCost;
  const estimatedIrpfBase = salesBase - expenseBase;
  const rate = normalizeIrpfPercent(irpfPercent);
  const irpfEstimate =
    estimatedIrpfBase > 0 ? estimatedIrpfBase * (rate / 100) : 0;
  const profitAfterIrpfReserve = grossProfit - irpfEstimate;

  return {
    vatExempt: vatExempt && salesIva === 0,
    integrityBlockedDocuments: fiscalSelection.integrityBlockedDocuments,
    unsupportedRectificationDocuments:
      fiscalSelection.unsupportedRectificationDocuments,
    lineVatExpenseCount,
    headerVatExpenseCount,
    unsupportedMixedVatExpenses,
    salesBase,
    salesIva,
    expenseBase,
    expenseIva,
    operatingExpenseCost,
    nonDeductibleExpenseCount: nonDeductibleExpenses.length,
    nonDeductibleExpenseTotal,
    netIva,
    ivaToPay,
    ivaCredit,
    grossProfit,
    estimatedIrpfBase,
    irpfPercent: rate,
    irpfEstimate,
    profitAfterIrpfReserve,
  };
}
