import { roundMoney } from "./calculations";
import { selectCanonicalFiscalDocumentsForExport } from "./billing/fiscal-export-documents";
import { isAutoGeneratedReceipt } from "./receipts";
import {
  DEFAULT_PROFILE,
  type BusinessProfile,
  type Document,
  type Expense,
} from "./types";
import { documentAmounts } from "./vat-regime";

export const DEFAULT_IRPF_PERCENT = 20;

export function normalizeIrpfPercent(value?: number): number {
  if (value === undefined || value === null || Number.isNaN(value)) {
    return DEFAULT_IRPF_PERCENT;
  }
  return Math.min(100, Math.max(0, value));
}

/** Facturas y recibos emitidos que generan base e IVA repercutido */
export function isTaxableSaleDocument(doc: Document): boolean {
  if (doc.type !== "factura" && doc.type !== "recibo") return false;
  if (doc.status === "borrador" || doc.status === "anulada") return false;
  if (doc.rectifiedById) return false;
  if (isAutoGeneratedReceipt(doc)) return false;
  return true;
}

/**
 * Resuelve una cadena ya canonizada dentro de un periodo fiscal aislado.
 * Una corrección sustituye a su original cuando ambas fechas caen en el
 * periodo; una anulación conserva original y abono para que se compensen.
 * Las correcciones interperiodo se excluyen hasta poder expresar una
 * diferencia fiscal auditable, en lugar de imputar el total corregido otra vez.
 */
export function taxableSaleDocumentsForPeriod(documents: Document[]): {
  documents: Document[];
  unsupportedRectificationDocuments: number;
} {
  const byId = new Map(documents.map((document) => [document.id, document]));
  let unsupportedRectificationDocuments = 0;
  const selected = documents.filter((document) => {
    if (document.snapshotIntegrity?.status === "blocked") return false;

    const baseSale =
      (document.type === "factura" || document.type === "recibo") &&
      document.status !== "borrador" &&
      !isAutoGeneratedReceipt(document);
    if (!baseSale) return false;

    if (document.rectification) {
      if (
        document.rectification.type === "correccion" &&
        !byId.has(document.rectification.originalDocumentId)
      ) {
        unsupportedRectificationDocuments += 1;
        return false;
      }
      return true;
    }

    if (document.rectifiedById) {
      const rectification = byId.get(document.rectifiedById);
      if (!rectification) return true;
      return rectification.rectification?.type === "anulacion";
    }

    return document.status !== "anulada";
  });

  return { documents: selected, unsupportedRectificationDocuments };
}

export function expenseIvaAmount(expense: Expense): number {
  const amount = Number.isFinite(expense.amount) ? expense.amount : 0;
  const ivaPercent = Number.isFinite(expense.ivaPercent)
    ? expense.ivaPercent
    : 0;
  return roundMoney(amount * (ivaPercent / 100));
}

export interface TaxSummary {
  vatExempt: boolean;
  integrityBlockedDocuments: number;
  unsupportedRectificationDocuments: number;
  salesBase: number;
  salesIva: number;
  expenseBase: number;
  expenseIva: number;
  netIva: number;
  ivaToPay: number;
  ivaCredit: number;
  grossProfit: number;
  irpfPercent: number;
  irpfEstimate: number;
  estimatedNetProfit: number;
}

export interface TaxSummaryOptions {
  irpfPercent?: number;
  vatExempt?: boolean;
  profile?: BusinessProfile;
  isDocumentDateInPeriod?: (date: string) => boolean;
}

export interface TaxableFiscalDocumentSelection {
  documents: Document[];
  integrityBlockedDocuments: number;
  unsupportedRectificationDocuments: number;
}

/**
 * Única selección de ventas permitida para cifras fiscales y sus resúmenes UI.
 * Recalcula snapshots y relaciones antes de devolver documentos canónicos.
 */
export function selectTaxableFiscalDocumentsForPeriod(
  documents: Document[],
  options: Pick<
    TaxSummaryOptions,
    "profile" | "isDocumentDateInPeriod"
  > = {},
): TaxableFiscalDocumentSelection {
  const fiscalSelection = selectCanonicalFiscalDocumentsForExport(
    documents,
    options.profile ?? DEFAULT_PROFILE,
    options.isDocumentDateInPeriod ?? (() => true),
  );
  const resolvedSales = taxableSaleDocumentsForPeriod(
    fiscalSelection.documents,
  );

  return {
    documents: resolvedSales.documents,
    integrityBlockedDocuments: fiscalSelection.blockedDocuments.length,
    unsupportedRectificationDocuments:
      resolvedSales.unsupportedRectificationDocuments,
  };
}

export class TaxExportBlockedError extends Error {
  readonly integrityBlockedDocuments: number;
  readonly unsupportedRectificationDocuments: number;

  constructor(
    summary: Pick<
      TaxSummary,
      "integrityBlockedDocuments" | "unsupportedRectificationDocuments"
    >,
  ) {
    super(
      "No se puede exportar un resumen fiscal incompleto. Revisa los documentos bloqueados y las rectificativas interperiodo.",
    );
    this.name = "TaxExportBlockedError";
    this.integrityBlockedDocuments = summary.integrityBlockedDocuments;
    this.unsupportedRectificationDocuments =
      summary.unsupportedRectificationDocuments;
  }
}

export function assertTaxSummaryExportable(
  summary: Pick<
    TaxSummary,
    "integrityBlockedDocuments" | "unsupportedRectificationDocuments"
  >,
): void {
  if (
    summary.integrityBlockedDocuments > 0 ||
    summary.unsupportedRectificationDocuments > 0
  ) {
    throw new TaxExportBlockedError(summary);
  }
}

export function calculateTaxSummary(
  documents: Document[],
  expenses: Expense[],
  options: TaxSummaryOptions = {},
): TaxSummary {
  const irpfPercent = options.irpfPercent ?? DEFAULT_IRPF_PERCENT;
  const profile = options.profile ?? DEFAULT_PROFILE;
  const vatExempt = options.vatExempt ?? Boolean(profile.vatExempt);
  const fiscalSelection = selectTaxableFiscalDocumentsForPeriod(
    documents,
    {
      profile,
      isDocumentDateInPeriod: options.isDocumentDateInPeriod,
    },
  );
  const sales = fiscalSelection.documents;
  const salesAmounts = sales.map((document) =>
    documentAmounts(document, vatExempt),
  );

  const salesBase = salesAmounts.reduce(
    (sum, amounts) => sum + amounts.subtotal,
    0,
  );
  const salesIva = salesAmounts.reduce(
    (sum, amounts) => sum + amounts.iva,
    0,
  );

  const expenseBase = expenses.reduce((sum, expense) => sum + expense.amount, 0);
  const expenseIva = vatExempt
    ? 0
    : expenses.reduce((sum, expense) => sum + expenseIvaAmount(expense), 0);

  const netIva = salesIva - expenseIva;
  const ivaToPay = Math.max(0, netIva);
  const ivaCredit = Math.max(0, -netIva);

  const grossProfit = salesBase - expenseBase;
  const rate = normalizeIrpfPercent(irpfPercent);
  const irpfEstimate = grossProfit > 0 ? grossProfit * (rate / 100) : 0;
  const estimatedNetProfit = grossProfit - irpfEstimate - ivaToPay;

  return {
    vatExempt: vatExempt && salesIva === 0,
    integrityBlockedDocuments: fiscalSelection.integrityBlockedDocuments,
    unsupportedRectificationDocuments:
      fiscalSelection.unsupportedRectificationDocuments,
    salesBase,
    salesIva,
    expenseBase,
    expenseIva,
    netIva,
    ivaToPay,
    ivaCredit,
    grossProfit,
    irpfPercent: rate,
    irpfEstimate,
    estimatedNetProfit,
  };
}
