export const AEAT_P0_DEEP_REVIEW_FIELD_LABELS_V10: Readonly<Record<string, string>> = Object.freeze({
  FILING_RECEIPT_ID: "Justificante de presentación",
  ORIGINAL_FILING_RECEIPT_ID: "Justificante anterior",
  PROCEDURE_ID: "Expediente o procedimiento",
  ACT_ID: "Acto",
  EXECUTION_ACT_ID: "Acuerdo de ejecución",
  ORIGINAL_ACT_ID: "Acto original",
  REVIEW_RESOLUTION_ID: "Resolución ejecutada",
  NOTIFICATION_ID: "Notificación",
  ORIGINAL_DEBT_KEY: "Deuda original",
  CERTIFICATE_ID: "Certificado",
  REPLACEMENT_CERTIFICATE_ID: "Nuevo certificado",
  FILING_JUSTIFICATION_NUMBER: "Número de justificante",
  MODEL: "Modelo",
  FISCAL_YEAR: "Ejercicio",
  TAX_PERIOD: "Período",
  ISSUE_DATE: "Fecha del documento",
  EFFECTIVE_NOTIFICATION_DATE: "Fecha de notificación",
  CERTIFICATE_RECEIPT_DATE: "Recepción del certificado",
  FILING_DATE: "Fecha de presentación",
  REFERENCE_DATE: "Fecha de referencia",
  REVIEW_RESOLUTION_ENTRY_DATE: "Entrada de la resolución",
  ORIGINAL_DEADLINE: "Plazo original",
  NEW_DEADLINE: "Nuevo plazo",
  RESPONSE_DEADLINE: "Plazo de respuesta",
  ALLEGATION_DEADLINE: "Plazo de alegaciones",
  APPEAL_DEADLINE: "Plazo de recurso",
  VALID_UNTIL: "Válido hasta",
  ORIGINAL_RESULT: "Resultado original",
  REQUESTED_RESULT: "Resultado solicitado",
  REQUESTED_REFUND: "Devolución solicitada",
  PROPOSED_REFUND: "Devolución propuesta",
  PROPOSED_DEBT_ADJUSTMENT: "Ajuste propuesto",
  RECOGNIZED_REFUND: "Devolución reconocida",
  ADJUSTED_DEBT: "Deuda ajustada",
  INTEREST: "Intereses",
  PREVIOUS_RESULT: "Resultado anterior",
  RECTIFIED_RESULT: "Resultado rectificado",
  DIFFERENCE: "Diferencia",
  CANCELLED_AMOUNT: "Importe anulado",
  NEW_AMOUNT: "Nuevo importe",
  REFUND_AMOUNT: "Devolución",
  SUBMISSION_RESULT: "Resultado de la presentación",
  DECISION_RESULT: "Decisión",
  PROPOSAL_RESULT: "Resultado propuesto",
  FINAL_RESULT: "Resultado final",
  CERTIFICATE_RESULT: "Resultado del certificado",
  CORRECTION_RESULT: "Resultado de la corrección",
  CERTIFICATE_KIND: "Tipo de certificado",
  EXECUTION_SCOPE: "Alcance de la ejecución",
} as const);

export const AEAT_P0_DEEP_REVIEW_CONTROLLED_LABELS_V10 = Object.freeze([
  "Tipo de documento",
  ...Object.values(AEAT_P0_DEEP_REVIEW_FIELD_LABELS_V10),
] as const);
