import type { FiscalDocumentType } from "../extractors/contracts";
import type { CorpusInventoryRow } from "./contracts";

export const REAL_VARIANT_FAMILIES = [
  "MODEL_035",
  "MODEL_036",
  "MODEL_037",
  "MODEL_100",
  "MODEL_111",
  "MODEL_115",
  "MODEL_123",
  "MODEL_130",
  "MODEL_131",
  "MODEL_151",
  "MODEL_180",
  "MODEL_184",
  "MODEL_190",
  "MODEL_193",
  "MODEL_200",
  "MODEL_202",
  "MODEL_216",
  "MODEL_296",
  "MODEL_303",
  "MODEL_308",
  "MODEL_309",
  "MODEL_341",
  "MODEL_347",
  "MODEL_349",
  "MODEL_369",
  "MODEL_390",
  "MODEL_714",
  "MODEL_720",
  "MODEL_721",
  "MODEL_840",
  "CURRENT_CENSUS_CERTIFICATE",
  "AEAT_ECONOMIC_ACTIVITIES_VIEW",
  "AEAT_TAX_STATUS_VIEW",
  "AEAT_OBLIGATIONS_VIEW",
  "TGSS_CURRENT_STATUS_REPORT",
  "TGSS_EMPLOYMENT_HISTORY",
  "TGSS_SELF_EMPLOYED_ACTIVITIES",
  "ROI_CERTIFICATE",
  "LANDLORD_WITHHOLDING_EXEMPTION_CERTIFICATE",
] as const satisfies readonly FiscalDocumentType[];

export type RealVariantFamily = (typeof REAL_VARIANT_FAMILIES)[number];

const HIGH_PRIORITY = new Set<RealVariantFamily>([
  "MODEL_036",
  "MODEL_100",
  "MODEL_111",
  "MODEL_130",
  "MODEL_180",
  "MODEL_184",
  "MODEL_190",
  "MODEL_200",
  "MODEL_303",
  "MODEL_347",
  "MODEL_349",
  "MODEL_390",
  "MODEL_720",
  "MODEL_721",
  "CURRENT_CENSUS_CERTIFICATE",
  "TGSS_EMPLOYMENT_HISTORY",
  "AEAT_ECONOMIC_ACTIVITIES_VIEW",
  "AEAT_TAX_STATUS_VIEW",
  "AEAT_OBLIGATIONS_VIEW",
]);

type InventorySeed = Omit<
  CorpusInventoryRow,
  | "officialSyntheticCount"
  | "realAnonymizedCount"
  | "holdoutCount"
  | "coverageStatus"
  | "gapPriority"
  | "lastVerifiedAt"
>;

function row(seed: InventorySeed): CorpusInventoryRow {
  return Object.freeze({
    ...seed,
    fiscalYears: Object.freeze([...seed.fiscalYears]),
    layoutIds: Object.freeze([...seed.layoutIds]),
    officialSyntheticCount: 0,
    realAnonymizedCount: 0,
    holdoutCount: 0,
    coverageStatus: "REAL_VARIANT_GAP" as const,
    gapPriority: HIGH_PRIORITY.has(seed.family as RealVariantFamily)
      ? ("HIGH" as const)
      : ("NORMAL" as const),
    lastVerifiedAt: "2026-07-15",
  });
}

export const CURRENT_CORPUS_INVENTORY: readonly CorpusInventoryRow[] =
  Object.freeze([
    row({
      family: "MODEL_035",
      authority: "AEAT",
      fiscalYears: [2026],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2026"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "MODEL_036",
      authority: "AEAT",
      fiscalYears: [2026],
      layoutIds: ["AEAT_MODEL_036_INTERESTED_COPY_2026"],
      semanticCaseCount: 5,
      manifestCount: 5,
      nativePdfCount: 5,
      rasterOrOcrCount: 0,
      incompleteFixtureCount: 5,
    }),
    row({
      family: "MODEL_037",
      authority: "AEAT",
      fiscalYears: [2024],
      layoutIds: ["AEAT_MODEL_037_BOE_2023_HISTORICAL"],
      semanticCaseCount: 3,
      manifestCount: 3,
      nativePdfCount: 3,
      rasterOrOcrCount: 0,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "MODEL_100",
      authority: "AEAT",
      fiscalYears: [2025],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2025"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "MODEL_111",
      authority: "AEAT",
      fiscalYears: [2026],
      layoutIds: ["AEAT_MODEL_111_PRINTED_LAYOUT_VERSIONED"],
      semanticCaseCount: 4,
      manifestCount: 4,
      nativePdfCount: 4,
      rasterOrOcrCount: 0,
      incompleteFixtureCount: 4,
    }),
    row({
      family: "MODEL_115",
      authority: "AEAT",
      fiscalYears: [2026],
      layoutIds: ["AEAT_MODEL_115_PRINTED_LAYOUT_VERSIONED"],
      semanticCaseCount: 4,
      manifestCount: 4,
      nativePdfCount: 4,
      rasterOrOcrCount: 0,
      incompleteFixtureCount: 4,
    }),
    row({
      family: "MODEL_123",
      authority: "AEAT",
      fiscalYears: [2026],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2026"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "MODEL_130",
      authority: "AEAT",
      fiscalYears: [2026],
      layoutIds: ["AEAT_MODEL_130_BOE_2015_LAYOUT"],
      semanticCaseCount: 4,
      manifestCount: 4,
      nativePdfCount: 4,
      rasterOrOcrCount: 0,
      incompleteFixtureCount: 4,
    }),
    row({
      family: "MODEL_131",
      authority: "AEAT",
      fiscalYears: [2026],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2026"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "MODEL_151",
      authority: "AEAT",
      fiscalYears: [2026],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2026"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "MODEL_180",
      authority: "AEAT",
      fiscalYears: [2025],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2025"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "MODEL_184",
      authority: "AEAT",
      fiscalYears: [2025],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2025"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "MODEL_190",
      authority: "AEAT",
      fiscalYears: [2025],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2025"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "MODEL_193",
      authority: "AEAT",
      fiscalYears: [2025],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2025"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "MODEL_200",
      authority: "AEAT",
      fiscalYears: [2025],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2025"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "MODEL_202",
      authority: "AEAT",
      fiscalYears: [2026],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2026"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "MODEL_216",
      authority: "AEAT",
      fiscalYears: [2026],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2026"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "MODEL_296",
      authority: "AEAT",
      fiscalYears: [2025],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2025"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "MODEL_303",
      authority: "AEAT",
      fiscalYears: [2026],
      layoutIds: ["AEAT_MODEL_303_BOE_2026"],
      semanticCaseCount: 5,
      manifestCount: 5,
      nativePdfCount: 5,
      rasterOrOcrCount: 0,
      incompleteFixtureCount: 5,
    }),
    row({
      family: "MODEL_308",
      authority: "AEAT",
      fiscalYears: [2026],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2026"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "MODEL_309",
      authority: "AEAT",
      fiscalYears: [2026],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2026"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "MODEL_341",
      authority: "AEAT",
      fiscalYears: [2026],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2026"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "MODEL_347",
      authority: "AEAT",
      fiscalYears: [2025],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2025"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "MODEL_349",
      authority: "AEAT",
      fiscalYears: [2026],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2026"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "MODEL_369",
      authority: "AEAT",
      fiscalYears: [2026],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2026"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "MODEL_390",
      authority: "AEAT",
      fiscalYears: [2026],
      layoutIds: ["AEAT_MODEL_390_BOE_2026"],
      semanticCaseCount: 4,
      manifestCount: 4,
      nativePdfCount: 4,
      rasterOrOcrCount: 0,
      incompleteFixtureCount: 4,
    }),
    row({
      family: "MODEL_714",
      authority: "AEAT",
      fiscalYears: [2025],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2025"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "MODEL_720",
      authority: "AEAT",
      fiscalYears: [2025],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2025"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "MODEL_721",
      authority: "AEAT",
      fiscalYears: [2025],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2025"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "MODEL_840",
      authority: "AEAT",
      fiscalYears: [2026],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2026"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "CURRENT_CENSUS_CERTIFICATE",
      authority: "AEAT",
      fiscalYears: [2026],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2026"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "AEAT_ECONOMIC_ACTIVITIES_VIEW",
      authority: "AEAT",
      fiscalYears: [2026],
      layoutIds: ["SYNTHETIC_AEAT_INSPIRED_ACTIVITIES_VIEW_V1"],
      semanticCaseCount: 4,
      manifestCount: 4,
      nativePdfCount: 4,
      rasterOrOcrCount: 0,
      incompleteFixtureCount: 1,
    }),
    row({
      family: "AEAT_TAX_STATUS_VIEW",
      authority: "AEAT",
      fiscalYears: [2026],
      layoutIds: ["SYNTHETIC_AEAT_INSPIRED_TAX_STATUS_VIEW_V1"],
      semanticCaseCount: 4,
      manifestCount: 4,
      nativePdfCount: 4,
      rasterOrOcrCount: 0,
      incompleteFixtureCount: 0,
    }),
    row({
      family: "AEAT_OBLIGATIONS_VIEW",
      authority: "AEAT",
      fiscalYears: [2026],
      layoutIds: ["SYNTHETIC_AEAT_INSPIRED_OBLIGATIONS_VIEW_V1"],
      semanticCaseCount: 4,
      manifestCount: 4,
      nativePdfCount: 4,
      rasterOrOcrCount: 0,
      incompleteFixtureCount: 2,
    }),
    row({
      family: "TGSS_CURRENT_STATUS_REPORT",
      authority: "TGSS",
      fiscalYears: [2026],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2026"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "TGSS_EMPLOYMENT_HISTORY",
      authority: "TGSS",
      fiscalYears: [2026],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2026"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "TGSS_SELF_EMPLOYED_ACTIVITIES",
      authority: "TGSS",
      fiscalYears: [2026],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2026"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "ROI_CERTIFICATE",
      authority: "AEAT",
      fiscalYears: [2026],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2026"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
    row({
      family: "LANDLORD_WITHHOLDING_EXEMPTION_CERTIFICATE",
      authority: "AEAT",
      fiscalYears: [2026],
      layoutIds: ["SYNTHETIC_PENDING29_2_0_2026"],
      semanticCaseCount: 4,
      manifestCount: 12,
      nativePdfCount: 4,
      rasterOrOcrCount: 8,
      incompleteFixtureCount: 3,
    }),
  ]);

export function isRealVariantFamily(
  value: unknown,
): value is RealVariantFamily {
  return (
    typeof value === "string" &&
    (REAL_VARIANT_FAMILIES as readonly string[]).includes(value)
  );
}

export function readCorpusInventory(): readonly CorpusInventoryRow[] {
  return CURRENT_CORPUS_INVENTORY.map((entry) => ({
    ...entry,
    fiscalYears: [...entry.fiscalYears],
    layoutIds: [...entry.layoutIds],
  }));
}
