export const TAX_DIAGNOSTIC_RISK_TAGS = Object.freeze({
  A_INVOICING_SUBJECT: "INVOICING_SUBJECT",
  A_TAXPAYER_ROLE: "ENTITY_SEPARATION",
  A_PERSONAL_ACTIVITY: "PERSONAL_VS_ENTITY_ACTIVITY",
  C_ACTIVITY_KINDS: "MULTIPLE_ACTIVITY_NATURE",
  D_INCOME_TAX_REGIME: "INCOME_TAX_METHOD",
  D_WITHHELD_PERCENT: "PROFESSIONAL_WITHHOLDING_SHARE",
  E_VAT_REGIMES: "VAT_EXEMPTION_AND_SERVICE",
  F_EMPLOYEES: "EMPLOYEE_VS_PROFESSIONAL_PAYMENTS",
  F_PROFESSIONALS: "EMPLOYEE_VS_PROFESSIONAL_PAYMENTS",
  G_RENTS_PREMISES: "BUSINESS_PREMISES_RENT",
  G_RENT_WITHHOLDING: "BUSINESS_PREMISES_RENT",
  G_LANDLORD_EXEMPTION: "LANDLORD_WITHHOLDING_EXEMPTION",
  I_EU_GOODS_SALES: "EU_OPERATIONS",
  I_EU_GOODS_PURCHASES: "EU_OPERATIONS",
  I_EU_SERVICES_SALES: "EU_OPERATIONS",
  I_EU_SERVICES_PURCHASES: "EU_OPERATIONS",
  I_ROI: "ROI_VS_349_OPERATIONS",
  J_EU_CONSUMERS: "EU_B2C_OSS_IOSS",
  J_OSS: "EU_B2C_OSS_IOSS",
  L_COMPANY_INSTALLMENTS: "NATURAL_PERSON_VS_COMPANY",
  N_CENSUS_REVIEWED: "CURRENT_VS_HISTORICAL_DOCUMENT",
  N_CENSUS_OBLIGATIONS: "CURRENT_VS_HISTORICAL_DOCUMENT",
} as const);

export function taxDiagnosticRiskTag(questionId: string): string | undefined {
  return TAX_DIAGNOSTIC_RISK_TAGS[
    questionId as keyof typeof TAX_DIAGNOSTIC_RISK_TAGS
  ];
}
