import { createBatch1PracticalGuideV1 } from "./create-batch-1-practical-guide.v1";

export const MODEL_038_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "038",
  category: "Registros públicos · Declaración informativa",
  statusLabel: "Mensual",
  statusTone: "current",
  effectiveYear: 2026,
  intro: [
    "El Modelo 038 comunica determinadas inscripciones de constitución, establecimiento, modificación o extinción de entidades sujetas al Impuesto sobre Sociedades que autorizan los titulares de Registros públicos.",
    "No es una declaración que una sociedad o un autónomo presente por el mero hecho de figurar en el Registro Mercantil: el declarante es el titular registral obligado a suministrar la información.",
  ],
  notices: [
    {
      title: "La entidad inscrita no es el declarante ordinario",
      paragraphs: [
        "La obligación corresponde al titular del Registro público que autoriza la inscripción. Estar inscrito no convierte a la empresa en presentadora del Modelo 038.",
      ],
    },
    {
      title: "Plazo mensual y extensión técnica excepcional",
      paragraphs: [
        "Se presenta durante cada mes natural por las inscripciones autorizadas en el mes inmediato anterior. Los cuatro días adicionales solo deben aplicarse cuando la AEAT reconozca la imposibilidad técnica y habilite expresamente esa extensión; no son un plazo ordinario.",
      ],
    },
  ],
  type: "Declaración informativa sin ingreso.",
  presenter: "Titulares de Registros públicos obligados por la norma.",
  nonPresenter: "La sociedad inscrita, sus socios o un autónomo por aparecer en un Registro.",
  periodicity: "Mensual; cada envío informa las inscripciones autorizadas en el mes natural anterior.",
  deadline: "Durante el mes natural siguiente; una extensión técnica solo procede si la AEAT la habilita para la incidencia prevista.",
  channel: "Presentación electrónica mediante fichero ajustado al diseño de registro vigente.",
  result: "Informativo: no genera cuota, devolución ni pago.",
  included: [
    "Constitución, establecimiento, modificación o extinción inscrita cuando la norma exige comunicarla.",
    "Identificación del Registro, de la entidad y de la inscripción autorizada.",
    "Identificador Registral Único de la Sociedad (IRUS) cuando corresponda al diseño vigente.",
    "Altas, correcciones y bajas de registros mediante el cauce técnico publicado.",
  ],
  excluded: [
    "El alta censal de la entidad, que se gestiona mediante el Modelo 036.",
    "La declaración anual del Impuesto sobre Sociedades mediante el Modelo 200.",
    "Una comunicación manual de la empresa inscrita.",
  ],
  preparation: [
    "Conciliar el asiento registral con la identidad y NIF de la entidad.",
    "Validar fecha, tipo de operación e identificadores exigidos por el diseño.",
    "Separar las inscripciones del mes anterior y evitar duplicados.",
    "Conservar el fichero, la respuesta y el detalle de registros aceptados o rechazados.",
  ],
  correction:
    "El titular registral debe corregir los registros erróneos con el mecanismo de consulta, baja o sustitución publicado por la AEAT; la entidad inscrita no presenta un 038 paralelo.",
  procedureSourceId: "aeat.model-038.procedure-home.2026-07-08",
  recordSourceId: "aeat.model-038.procedure-record.2026-07-08",
  helpSourceId: "aeat.model-038.help.2026-06-19",
  document: {
    label: "Descargar diseño de registro del Modelo 038",
    sourceId: "aeat.model-038.register-design-pdf.2024-06-28",
  },
  legalSourceIds: ["boe.model-038.order-2002", "boe.model-038.update-2024"],
  related: [
    { code: "036", href: "/consultor-fiscal/modelos/036", description: "Alta, modificación y baja censal de la entidad." },
    { code: "200", href: "/consultor-fiscal/modelos/200", description: "Declaración anual del Impuesto sobre Sociedades." },
  ],
  faq: [
    { question: "¿Lo presenta una empresa por estar inscrita en el Registro Mercantil?", answer: "No. La presenta el titular del Registro obligado a informar; la empresa es la entidad declarada." },
    { question: "¿Quién es el declarante?", answer: "El titular del Registro público que autoriza las inscripciones incluidas por la normativa del Modelo 038." },
    { question: "¿Es mensual?", answer: "Sí. Se presenta durante cada mes natural respecto de las inscripciones del mes inmediatamente anterior." },
    { question: "¿Qué mes se informa?", answer: "El mes natural anterior al mes en el que se efectúa el envío." },
    { question: "¿Genera un pago?", answer: "No. Es una declaración informativa y no produce una cuota a ingresar." },
    { question: "¿Puede presentarse manualmente?", answer: "El procedimiento vigente se articula mediante presentación electrónica y fichero conforme al diseño oficial." },
    { question: "¿Cómo se corrige un registro?", answer: "Mediante los servicios oficiales de consulta, baja o corrección que correspondan al envío; debe revisarse la respuesta de la AEAT." },
    { question: "¿Qué ocurre si el fichero contiene errores?", answer: "Los registros rechazados no deben darse por presentados. Hay que subsanar la causa y reenviarlos por el cauce oficial." },
  ],
});

export const MODEL_039_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "039",
  category: "IVA · Grupo de entidades",
  statusLabel: "Comunicación censal especializada",
  statusTone: "current",
  effectiveYear: 2026,
  intro: [
    "El Modelo 039 comunica opciones, composición y cambios del régimen especial del grupo de entidades del IVA.",
    "Un grupo mercantil no es automáticamente un grupo de IVA: deben cumplirse los requisitos, existir una entidad dominante y ejercerse las opciones del régimen.",
  ],
  notices: [
    {
      title: "Grupo mercantil y grupo de IVA no son lo mismo",
      paragraphs: [
        "La vinculación societaria por sí sola no permite presentar el 039. La entidad dominante debe comprobar participación, control, composición y modalidad del régimen especial.",
      ],
    },
  ],
  type: "Comunicación censal del régimen especial del grupo de entidades de IVA.",
  presenter: "La entidad dominante o representante del grupo de IVA en los supuestos previstos.",
  nonPresenter: "Una empresa aislada o cualquier miembro de un grupo mercantil sin opción válida por el régimen de IVA.",
  periodicity: "No periódica: se presenta por opción, renuncia, inclusión, exclusión o cambio de composición.",
  deadline: "Depende de la causa de la comunicación; debe comprobarse el plazo específico antes del hecho o periodo afectado.",
  channel: "Presentación electrónica del formulario o modelo oficial, con la documentación que corresponda.",
  result: "Censal: no es una autoliquidación ni genera un pago directo.",
  included: [
    "Identidad de la entidad dominante y de las dependientes.",
    "Porcentajes de participación y control exigidos por el régimen.",
    "Opción por la modalidad básica o avanzada cuando proceda.",
    "Inclusiones, exclusiones, renuncia y cambios en la composición del grupo.",
  ],
  excluded: [
    "El alta censal general de una sociedad, que se gestiona en el Modelo 036.",
    "Las autoliquidaciones individuales del grupo, Modelo 322.",
    "La autoliquidación agregada del grupo, Modelo 353.",
    "La pertenencia meramente mercantil a un conjunto de sociedades.",
  ],
  preparation: [
    "Acreditar entidad dominante, dependientes y porcentajes de participación.",
    "Documentar el acuerdo y la modalidad elegida.",
    "Conciliar entradas y salidas de entidades con el periodo de efecto.",
    "Comprobar después las obligaciones de los Modelos 322 y 353 y, en su caso, del SII.",
  ],
  correction:
    "Comunica la variación por el motivo y plazo que correspondan. Una entrada o salida mal fechada puede afectar las autoliquidaciones del grupo y debe revisarse antes de corregir.",
  procedureSourceId: "aeat.model-039.procedure-home.2026-04-01",
  recordSourceId: "aeat.model-039.procedure-record.2026-07-10",
  helpSourceId: "aeat.model-039.help.2026-05-06",
  document: { label: "Descargar instrucciones oficiales del Modelo 039", sourceId: "aeat.model-039.instructions-pdf.2026-05-29" },
  legalSourceIds: ["boe.model-039.order-2008"],
  related: [
    { code: "036", href: "/consultor-fiscal/modelos/036", description: "Declaración censal general de empresarios y entidades." },
    { code: "322", href: "/consultor-fiscal/modelos/322", description: "Autoliquidación individual de IVA de cada entidad del grupo." },
    { code: "353", href: "/consultor-fiscal/modelos/353", description: "Autoliquidación agregada del grupo de entidades." },
  ],
  faq: [
    { question: "¿Qué diferencia existe entre un grupo mercantil y un grupo de IVA?", answer: "El grupo de IVA exige requisitos y una opción fiscal específica; la relación mercantil por sí sola no basta." },
    { question: "¿Quién presenta el Modelo 039?", answer: "La entidad dominante o representante en las comunicaciones previstas para el grupo." },
    { question: "¿Lo presenta cada entidad?", answer: "No para la misma comunicación de composición; la entidad dominante centraliza el 039, aunque cada miembro conserva otras obligaciones." },
    { question: "¿Qué es la modalidad avanzada?", answer: "Una modalidad específica del régimen con reglas propias de cálculo y documentación; no se presume por pertenecer al grupo." },
    { question: "¿Sustituye al Modelo 036?", answer: "No. El 039 comunica el régimen de grupo; el 036 mantiene las altas y variaciones censales generales." },
    { question: "¿Qué ocurre si entra o sale una empresa?", answer: "La variación debe comunicarse con la causa y fecha de efecto correctas y coordinarse con las autoliquidaciones del periodo." },
    { question: "¿Qué modelos de IVA presenta después el grupo?", answer: "Con carácter general se relaciona con las autoliquidaciones individuales 322 y la agregada 353, según el régimen aplicable." },
    { question: "¿Puede utilizarlo una pequeña SL aislada?", answer: "No por ser una SL. Solo si integra válidamente un grupo de entidades y la comunicación corresponde a su entidad dominante." },
  ],
});

const territorialNotice = {
  title: "Comprueba primero qué Administración es competente",
  paragraphs: [
    "Las tasas sobre el juego están cedidas o gestionadas territorialmente en muchos supuestos. La ficha estatal de la AEAT se limita a los casos de gestión estatal que identifica; no debe usarse para sustituir el trámite autonómico.",
  ],
} as const;

export const MODEL_043_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "043",
  category: "Tasa fiscal sobre el juego · Bingo",
  statusLabel: "Competencia territorial limitada",
  statusTone: "territorial",
  effectiveYear: 2026,
  intro: [
    "El Modelo 043 liquida la tasa fiscal sobre el juego del bingo cuando la gestión corresponde a la Administración tributaria estatal.",
    "No lo presenta quien juega ni cualquier local de ocio: se dirige al sujeto pasivo autorizado en el ámbito estatal y se vincula a los cartones o soportes del bingo.",
  ],
  notices: [territorialNotice],
  type: "Solicitud de liquidación de la tasa fiscal sobre el bingo.",
  presenter: "El sujeto pasivo u organizador autorizado cuando la gestión de la tasa corresponde a la AEAT estatal.",
  nonPresenter: "El jugador, un bar por tener juegos o un operador sujeto al trámite de una comunidad autónoma.",
  periodicity: "Ligada a la autorización, retirada o utilización de los cartones y al régimen territorial aplicable.",
  deadline: "Debe comprobarse antes de la retirada o utilización cuando así lo exige el trámite estatal.",
  channel: "Formulario y documentación oficial ante la Administración competente; no todos los territorios usan la AEAT.",
  result: "Liquidación o pago de la tasa cuando procede.",
  included: ["Salas y modalidades de bingo incluidas en la gestión estatal.", "Cartones o soportes autorizados.", "Base, cuota y devengo según las reglas específicas.", "Autorización administrativa y datos del operador."],
  excluded: ["Premios del jugador y su tributación personal.", "Retenciones del pagador sobre premios.", "Trámites autonómicos que no corresponden a la AEAT estatal."],
  preparation: ["Confirmar competencia estatal o autonómica.", "Aportar autorización del juego y datos de la sala.", "Conciliar cartones o soportes con la liquidación.", "Conservar justificante y documentación de retirada o uso."],
  correction: "Una cuota o dato incorrecto se corrige por el procedimiento de rectificación o devolución de ingresos indebidos de la Administración competente.",
  procedureSourceId: "aeat.model-043.procedure-home.2026-06-09",
  recordSourceId: "aeat.model-043.procedure-record.2026-06-09",
  helpSourceId: "aeat.model-043.topic.2026-01-22",
  document: { label: "Descargar instrucciones oficiales del Modelo 043", sourceId: "aeat.model-043.instructions-pdf.captured-2026-07-13" },
  legalSourceIds: ["boe.order-27-july-2001.models-043-044-045", "boe.rdl-16-1977.games"],
  related: [
    { code: "136", href: "/consultor-fiscal/modelos/136", description: "Autoliquidación de determinados premios sin retención." },
    { code: "230", href: "/consultor-fiscal/modelos/230", description: "Retención del pagador sobre determinados premios." },
    { code: "270", href: "/consultor-fiscal/modelos/270", description: "Resumen informativo de premios y retenciones." },
  ],
  faq: [
    { question: "¿Lo presenta quien juega?", answer: "No. Lo presenta el sujeto pasivo u organizador autorizado cuando corresponde la gestión estatal." },
    { question: "¿Lo presenta cualquier bar con juegos?", answer: "No. Debe tratarse de bingo autorizado e incluido en el ámbito del modelo." },
    { question: "¿La competencia es estatal o autonómica?", answer: "Depende del territorio y del supuesto; debe comprobarse antes de usar el trámite AEAT." },
    { question: "¿Cuándo se paga?", answer: "Según el devengo y la retirada o utilización de cartones prevista por el régimen aplicable." },
    { question: "¿Qué autorización se necesita?", answer: "La autorización administrativa del juego y de la sala que exija la autoridad competente." },
    { question: "¿Es lo mismo que tributar por premios?", answer: "No. Esta tasa grava la organización del juego; los premios tienen reglas y modelos distintos." },
    { question: "¿Puede presentarse por internet?", answer: "Hay que seguir el canal publicado por la Administración competente; la ficha AEAT no sustituye el portal autonómico." },
    { question: "¿Cómo se corrige un pago incorrecto?", answer: "Mediante rectificación o devolución de ingresos indebidos ante la Administración que gestionó la tasa." },
  ],
});

export const MODEL_044_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "044",
  category: "Tasa fiscal sobre el juego · Casinos",
  statusLabel: "Competencia territorial limitada",
  statusTone: "territorial",
  effectiveYear: 2026,
  intro: [
    "El Modelo 044 se utiliza para la tasa fiscal sobre casinos de juego cuando su gestión corresponde a la Administración tributaria estatal.",
    "La obligación recae en el casino autorizado, no en los jugadores ni en una sociedad por desarrollar cualquier actividad de ocio.",
  ],
  notices: [territorialNotice],
  type: "Declaración o liquidación sectorial de la tasa sobre casinos.",
  presenter: "El casino o sujeto pasivo autorizado en los supuestos de gestión estatal.",
  nonPresenter: "El jugador, un local de ocio sin autorización de casino o un operador sujeto al trámite autonómico.",
  periodicity: "La que establezca el régimen territorial y la liquidación aplicable al casino.",
  deadline: "Debe verificarse en el procedimiento de la Administración competente para el periodo concreto.",
  channel: "Formulario oficial y pago ante la AEAT o la Administración autonómica que corresponda.",
  result: "Cuota de la tasa, calculada conforme a la base y escala aplicables.",
  included: ["Ingresos brutos del juego y cantidades pagadas a jugadores según la definición legal.", "Base imponible y escala o cuota aplicable.", "Periodo, autorización e identificación del casino.", "Registros contables exigidos al operador."],
  excluded: ["La renta personal obtenida por el jugador.", "La retención de premios.", "Casinos cuya tasa gestiona una comunidad autónoma por su propio procedimiento."],
  preparation: ["Confirmar competencia territorial.", "Conciliar ingresos del juego y premios pagados.", "Verificar escala, periodo y devengo vigentes.", "Conservar contabilidad, autorización y justificante."],
  correction: "La complementaria o rectificación debe seguir el procedimiento de la Administración que recibió la liquidación; una devolución requiere el cauce de ingresos indebidos cuando proceda.",
  procedureSourceId: "aeat.model-044.procedure-home.2026-06-09",
  recordSourceId: "aeat.model-044.procedure-record.2026-06-09",
  helpSourceId: "aeat.model-044.topic.2026-01-22",
  document: { label: "Descargar instrucciones oficiales del Modelo 044", sourceId: "aeat.model-044.instructions-pdf.captured-2026-07-13" },
  legalSourceIds: ["boe.order-27-july-2001.models-043-044-045", "boe.order-13-november-1981.games-tax"],
  related: [
    { code: "136", href: "/consultor-fiscal/modelos/136", description: "Premios incluidos en el gravamen especial sin retención." },
    { code: "230", href: "/consultor-fiscal/modelos/230", description: "Retenciones de determinados premios." },
    { code: "270", href: "/consultor-fiscal/modelos/270", description: "Resumen de premios y retenciones." },
  ],
  faq: [
    { question: "¿Lo presenta el casino o el jugador?", answer: "El casino o sujeto pasivo autorizado; nunca el jugador por participar." },
    { question: "¿Quién gestiona el impuesto?", answer: "Puede ser la AEAT estatal o la comunidad autónoma; hay que verificar el territorio." },
    { question: "¿Cómo se calcula la base?", answer: "Con los ingresos del juego y las deducciones admitidas por la normativa específica, no con el beneficio contable general." },
    { question: "¿Se descuentan los premios pagados?", answer: "Solo en los términos de la definición legal de la base aplicable al casino." },
    { question: "¿Cuándo se presenta?", answer: "En el periodo y plazo publicado por la Administración competente." },
    { question: "¿Se puede domiciliar?", answer: "Depende del trámite y calendario vigentes; debe comprobarse antes de iniciar la presentación." },
    { question: "¿Qué documentación debe conservarse?", answer: "Autorización, registros de juego, ingresos, premios, liquidación y justificante." },
    { question: "¿Cómo se corrige?", answer: "Mediante complementaria, rectificación o devolución ante la Administración que gestionó la cuota." },
  ],
});

export const MODEL_045_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "045",
  category: "Tasa fiscal sobre el juego · Máquinas",
  statusLabel: "Competencia territorial limitada",
  statusTone: "territorial",
  effectiveYear: 2026,
  intro: [
    "El Modelo 045 liquida la tasa sobre máquinas o aparatos automáticos incluidos en la normativa del juego cuando la gestión corresponde a la Administración estatal.",
    "No afecta a cualquier máquina de un negocio: debe ser una máquina recreativa o de azar sujeta, identificada y autorizada conforme al régimen territorial aplicable.",
  ],
  notices: [territorialNotice],
  type: "Declaración-liquidación sectorial por máquinas de juego.",
  presenter: "La empresa operadora o titular de la autorización en los supuestos de gestión estatal.",
  nonPresenter: "El usuario, el local por tener una máquina expendedora o un operador sujeto a la tasa autonómica.",
  periodicity: "Por máquina y conforme al alta, periodo o pago previo previsto en el régimen competente.",
  deadline: "Puede exigirse antes de la autorización o por periodos; debe comprobarse el trámite territorial vigente.",
  channel: "Formulario y pago ante la Administración competente, con identificación individual de la máquina.",
  result: "Cuota de la tasa por cada máquina o aparato sujeto.",
  included: ["Máquinas recreativas o de azar incluidas legalmente.", "Matrícula, serie, fabricante, tipo y ubicación.", "Alta, sustitución, traslado y baja cuando deban declararse.", "Cuota, periodo, autorización y empresa operadora."],
  excluded: ["Máquinas expendedoras o herramientas ordinarias no incluidas en la normativa del juego.", "Premios y retenciones personales del jugador.", "Trámites autonómicos fuera de la gestión estatal."],
  preparation: ["Comprobar tipo y autorización de cada máquina.", "Conciliar matrícula, serie, local y empresa operadora.", "Determinar cuota y devengo territoriales.", "Documentar altas, traslados, sustituciones y bajas."],
  correction: "Corrige la máquina y el periodo exactos ante la Administración competente. Un traslado o baja no debe darse por efectivo sin su comunicación administrativa cuando sea exigible.",
  procedureSourceId: "aeat.model-045.procedure-home.2026-06-09",
  recordSourceId: "aeat.model-045.procedure-record.2026-06-09",
  helpSourceId: "aeat.model-045.topic.2026-01-22",
  document: { label: "Descargar instrucciones oficiales del Modelo 045", sourceId: "aeat.model-045.instructions-pdf.captured-2026-07-13" },
  legalSourceIds: ["boe.order-27-july-2001.models-043-044-045", "boe.rd-2110-1998.machines"],
  related: [
    { code: "136", href: "/consultor-fiscal/modelos/136", description: "Autoliquidación de determinados premios sin retención." },
    { code: "230", href: "/consultor-fiscal/modelos/230", description: "Retenciones sobre premios sujetos." },
    { code: "270", href: "/consultor-fiscal/modelos/270", description: "Resumen informativo de premios." },
  ],
  faq: [
    { question: "¿Afecta a una máquina expendedora?", answer: "No por el mero hecho de ser automática; debe ser una máquina incluida en la normativa del juego." },
    { question: "¿Quién presenta el modelo?", answer: "La empresa operadora o titular de la autorización cuando corresponde la gestión estatal." },
    { question: "¿Se presenta por cada máquina?", answer: "La identificación y cuota se individualizan por máquina según el régimen aplicable." },
    { question: "¿Qué ocurre si se traslada?", answer: "Debe comunicarse el traslado y la nueva ubicación cuando lo exija la autoridad competente." },
    { question: "¿Qué ocurre si se da de baja?", answer: "La baja debe documentarse; no se presume solo porque la máquina deje de utilizarse." },
    { question: "¿La competencia es autonómica?", answer: "Con frecuencia sí; la ficha estatal solo sirve para los supuestos de gestión AEAT." },
    { question: "¿Cuándo se paga?", answer: "Según el devengo, periodo o pago previo fijado por la normativa territorial." },
    { question: "¿Cómo se rectifica?", answer: "Ante la Administración que gestionó la tasa, identificando máquina, periodo y causa de la corrección." },
  ],
});
