import type { FiscalModelPracticalGuideV1 } from "./fiscal-model-practical-guide.types";

export const MODEL_349_GUIDE_V1 = {
  code: "349",
  lastVerifiedAt: "2026-07-14",
  requiresAnnualReview: true,
  intro: [
    "El Modelo 349 sirve para informar de determinadas entregas, adquisiciones y servicios realizados con empresas o profesionales de otros países de la Unión Europea.",
    "Es una declaración informativa: no sirve para pagar IVA. Una operación declarable puede tener que incluirse aunque su importe sea reducido.",
  ],
  notices: [
    { title: "No tiene un importe mínimo general", paragraphs: ["El límite de 3.005,06 € pertenece al Modelo 347 y no se aplica al 349. Los 50.000 € solo intervienen en la periodicidad de determinadas entregas y servicios."] },
    { title: "No toda factura extranjera es intracomunitaria", paragraphs: ["Hay que comprobar el país, si ambas partes actúan como empresarios o profesionales, el NIF-IVA, el tipo de operación y las reglas de localización del IVA."] },
    { title: "ROI y VIES son comprobaciones esenciales", paragraphs: ["El NIF-IVA del operador debe validarse en VIES cuando proceda y conviene conservar la evidencia de la consulta y del transporte de los bienes."] },
  ],
  actions: [
    { label: "Presentar Modelo 349 del periodo disponible", sourceId: "aeat.model-349.procedure-home.2026-07-08", primary: true },
    { label: "Comprobar un NIF-IVA en VIES", href: "https://ec.europa.eu/taxation_customs/vies/#/vat-validation", primary: true },
    { label: "Consultar instrucciones oficiales", sourceId: "aeat.model-349.instructions-pdf.2026-06-12" },
    { label: "Ver ayuda del formulario", sourceId: "aeat.model-349.form-help.2026-06-19" },
    { label: "Presentar mediante fichero", sourceId: "aeat.model-349.file-help.2026-06-19" },
    { label: "Consultar la nota informativa", sourceId: "aeat.model-349.information-note.2026-07-08" },
  ],
  quickSummaryTitle: "El Modelo 349 en pocas palabras",
  quickFacts: [
    { label: "Qué es", value: "Una declaración recapitulativa de determinadas operaciones intracomunitarias." },
    { label: "Genera un pago", value: "No." },
    { label: "Importe mínimo", value: "No existe un mínimo general para incluir una operación declarable." },
    { label: "Quién", value: "Empresarios o profesionales que realizan operaciones intracomunitarias incluidas." },
    { label: "Identificación", value: "Normalmente exige NIF-IVA válido y comprobación en VIES." },
    { label: "Periodicidad", value: "Mensual con carácter general; trimestral si se cumplen las condiciones oficiales." },
    { label: "Presentación anual", value: "No existe desde 2020." },
    { label: "Presentación", value: "Formulario web hasta 40.000 registros o mediante fichero." },
  ],
  sections: [
    {
      id: "model-349-decision",
      title: "Cómo saber si una operación va en el 349",
      cards: [
        { title: "1. Comprueba el país", paragraphs: ["La otra parte debe estar identificada a efectos de IVA en otro Estado miembro. Gran Bretaña, Canarias, Ceuta y Melilla requieren un análisis distinto."] },
        { title: "2. Identifica a las partes", paragraphs: ["Comprueba que intervienen empresas o profesionales y que el NIF-IVA comunicado es válido para la operación."] },
        { title: "3. Clasifica la operación", paragraphs: ["Distingue bienes, servicios, triangulares, transferencias u otros supuestos especiales. No clasifiques por el nombre comercial del proveedor."] },
        { title: "4. Concilia el IVA", paragraphs: ["La operación debe poder explicarse también en los libros y en el Modelo 303 o, cuando corresponda, en el 309 o 369."] },
      ],
      note: "No utilices el Modelo 349 como una lista de todas las facturas extranjeras.",
    },
    {
      id: "model-349-roi-vies",
      title: "ROI, NIF-IVA y VIES",
      cards: [
        { title: "Alta en el ROI", paragraphs: ["La solicitud se comunica mediante el Modelo 036. En el formulario vigente deben revisarse anualmente las casillas y textos; actualmente se identifican las casillas 582 y 584 para la solicitud y la fecha prevista de la primera operación."], links: [{ label: "Ver Modelo 036", href: "/consultor-fiscal/modelos/036" }] },
        { title: "Plazo de resolución", paragraphs: ["La Administración dispone de tres meses para resolver la solicitud. El silencio no debe tratarse como un alta automática."] },
        { title: "Consulta VIES", paragraphs: ["Comprueba el NIF-IVA antes de aplicar el tratamiento intracomunitario y conserva una evidencia fechada. Un resultado inválido exige revisar país, número y situación del operador."] },
      ],
      note: "En una entrega intracomunitaria exenta, entre otros requisitos, el cliente debe comunicar un NIF-IVA válido de otro Estado miembro y la operación debe informarse en el 349.",
    },
    {
      id: "model-349-keys",
      title: "Claves más habituales",
      cards: [
        { title: "E · Entregas", paragraphs: ["Entregas intracomunitarias de bienes declarables."] },
        { title: "A · Adquisiciones", paragraphs: ["Adquisiciones intracomunitarias de bienes declarables."] },
        { title: "S · Servicios prestados", paragraphs: ["Servicios intracomunitarios prestados a una empresa o profesional de otro Estado miembro cuando se cumplen las reglas aplicables."] },
        { title: "I · Servicios recibidos", paragraphs: ["Servicios intracomunitarios recibidos de una empresa o profesional establecido en otro Estado miembro."] },
      ],
      accordions: [
        { question: "Claves de supuestos especiales", paragraphs: ["Las instrucciones contemplan además T, M y H para determinadas operaciones triangulares o transferencias y R, D y C para rectificaciones relacionadas con las clases de operación correspondientes. No deben elegirse sin identificar el supuesto exacto."] },
      ],
    },
    {
      id: "model-349-goods-services",
      title: "Bienes, servicios y ejemplos digitales",
      cards: [
        { title: "Compra de bienes", paragraphs: ["Una compra a un proveedor francés con transporte a España y NIF-IVA válido puede ser una adquisición intracomunitaria con clave A."] },
        { title: "Servicio prestado", paragraphs: ["Un servicio de consultoría a una empresa alemana identificada puede declararse con clave S si se cumplen las reglas de localización."] },
        { title: "Servicio recibido", paragraphs: ["Una suscripción profesional de 25 € facturada por una empresa irlandesa puede generar inversión del sujeto pasivo y Modelo 349 con clave I; no existe un mínimo general."] },
      ],
      note: "Software, publicidad o plataformas como Google o Meta no van siempre al 349: depende de qué entidad factura, su país, el NIF-IVA y la naturaleza de la operación.",
    },
    {
      id: "model-349-territories",
      title: "Reino Unido, Irlanda del Norte y territorios españoles",
      cards: [
        { title: "Gran Bretaña", paragraphs: ["Inglaterra, Escocia y Gales son territorio tercero: sus operaciones ordinarias no se incluyen en el 349 por ser Reino Unido."] },
        { title: "Irlanda del Norte", paragraphs: ["El prefijo XI puede utilizarse para operaciones de bienes cubiertas por el régimen específico. No convierte los servicios en operaciones intracomunitarias."] },
        { title: "Canarias, Ceuta y Melilla", paragraphs: ["No forman parte del territorio de aplicación del IVA ni son otro Estado miembro. Una operación con estos territorios no va al 349 por ese único motivo."] },
      ],
    },
    {
      id: "model-349-proof-currency",
      title: "Pruebas, transporte y moneda",
      cards: [
        { title: "Transporte de bienes", paragraphs: ["Conserva facturas, pedidos, CMR u otros documentos de transporte, justificantes de pago y comunicaciones del cliente. La exención de una entrega exige poder acreditar el desplazamiento."] },
        { title: "Conversión a euros", paragraphs: ["Si una factura está en otra moneda, aplica el criterio de conversión exigido por la normativa del IVA y conserva el tipo de cambio utilizado."] },
      ],
    },
    {
      id: "model-349-periodicity",
      title: "Periodicidad y plazos",
      cards: [
        { title: "Regla general", paragraphs: ["La periodicidad general es mensual. El 349 ya no tiene presentación anual desde 2020."] },
        { title: "Presentación trimestral", paragraphs: ["Puede presentarse trimestralmente cuando el importe total de entregas de bienes y prestaciones de servicios intracomunitarias no supera 50.000 € ni en el trimestre en curso ni en cada uno de los cuatro trimestres naturales anteriores."] },
        { title: "Qué no entra en los 50.000 €", paragraphs: ["El umbral de periodicidad no incluye las adquisiciones intracomunitarias. Tampoco es una exención ni un importe mínimo para declarar operaciones."] },
      ],
      note: "Si se supera el umbral durante un trimestre, revisa la regla especial para pasar a periodicidad mensual. Los plazos y la domiciliación deben comprobarse en el calendario oficial del ejercicio.",
    },
    {
      id: "model-349-filing",
      title: "Formulario, fichero y correcciones",
      cards: [
        { title: "Formulario web", paragraphs: ["Admite hasta 40.000 registros, permite importar, validar, guardar y recuperar declaraciones presentadas."] },
        { title: "Presentación mediante fichero", paragraphs: ["Es necesaria por encima del límite del formulario y puede utilizarse también con menos registros si el archivo cumple el diseño vigente."] },
        { title: "Vista previa", paragraphs: ["El PDF de vista previa no es válido para presentar. Solo la firma y envío y el justificante con CSV acreditan la presentación."] },
      ],
      note: "El formulario puede presentar registros correctos dejando otros pendientes como función avanzada. Para corregir una declaración ya presentada, recupérala, añade, modifica o elimina registros y vuelve a presentar el conjunto completo, que sustituye al anterior; no uses por inercia el antiguo flujo de complementaria o sustitutiva. La vía mediante fichero tiene reglas propias. Distingue esta corrección de una rectificación comercial posterior, que se informa con las claves y periodos previstos por las instrucciones.",
    },
    {
      id: "model-349-related",
      title: "Relación con otros modelos",
      cards: [
        { title: "Modelo 303", paragraphs: ["Las operaciones del 349 suelen tener reflejo en la liquidación periódica del IVA y deben poder conciliarse con los libros."], links: [{ label: "Ver Modelo 303", href: "/consultor-fiscal/modelos/303" }] },
        { title: "Modelos 309 y 369", paragraphs: ["Determinadas personas sin 303 periódico pueden necesitar el 309; el 369 corresponde a regímenes especiales de ventanilla única. Ninguno se presume automáticamente."], links: [{ label: "Ver Modelo 309", href: "/consultor-fiscal/modelos/309" }, { label: "Ver Modelo 369", href: "/consultor-fiscal/modelos/369" }] },
        { title: "Modelo 347", paragraphs: ["Una operación ya incluida en el 349 no debe duplicarse automáticamente en el 347."], links: [{ label: "Ver Modelo 347", href: "/consultor-fiscal/modelos/347" }] },
      ],
    },
    {
      id: "model-349-territory-note",
      title: "Ámbito territorial",
      note: "Esta guía se refiere principalmente a la AEAT estatal y al territorio de aplicación del IVA español formado por Península y Baleares. Canarias, Ceuta y Melilla tienen particularidades y no forman parte de ese territorio. En País Vasco o Navarra también puede corresponder la Hacienda foral.",
    },
  ],
  fillingTitle: "Cómo preparar y presentar el Modelo 349",
  fillingSteps: [
    { title: "1. Reúne las operaciones", paragraphs: ["Parte de los libros de IVA y separa bienes, servicios y supuestos especiales. No copies todas las facturas extranjeras."] },
    { title: "2. Verifica NIF-IVA y país", paragraphs: ["Consulta VIES y conserva el resultado; revisa especialmente prefijos, Reino Unido e Irlanda del Norte."] },
    { title: "3. Determina clave y periodo", paragraphs: ["Clasifica E, A, S o I y utiliza las claves avanzadas solo cuando corresponda. Comprueba la fecha de devengo y la periodicidad."] },
    { title: "4. Concilia importes", paragraphs: ["Contrasta 349, 303 o 309, libros, moneda y documentación del transporte."] },
    { title: "5. Valida, firma y conserva", paragraphs: ["Corrige errores, firma, envía y guarda justificante, CSV y evidencias de la operación."] },
  ],
  afterTitle: "Qué ocurre después",
  afterSteps: [
    { title: "Conciliación", description: "Comprueba que libros, IVA periódico y declaración recapitulativa explican los mismos hechos." },
    { title: "Rectificación", description: "Distingue un error de la declaración presentada de una rectificación comercial posterior y aplica el procedimiento correspondiente." },
    { title: "Archivo", description: "Conserva facturas, VIES, transporte, conversión de moneda y justificante de presentación." },
  ],
  comparison: {
    title: "¿Necesitas el Modelo 349 o el Modelo 347?",
    current: { title: "Modelo 349", description: "Declara operaciones intracomunitarias incluidas, sin importe mínimo general y con periodicidad mensual o trimestral." },
    related: { title: "Modelo 347", description: "Declara anualmente determinadas operaciones con terceros cuando se supera el límite general y no existe exclusión.", href: "/consultor-fiscal/modelos/347", label: "Ver Modelo 347" },
    additional: [
      { title: "Modelo 036", description: "Sirve para solicitar el alta censal en el ROI.", href: "/consultor-fiscal/modelos/036", label: "Ver Modelo 036" },
      { title: "Modelo 303", description: "Liquida el IVA y debe poder conciliarse con el 349.", href: "/consultor-fiscal/modelos/303", label: "Ver Modelo 303" },
    ],
    conclusion: "El 349 no tiene mínimo general; los 50.000 € regulan periodicidad. El límite anual de 3.005,06 € corresponde al 347.",
  },
  pdfNotice: ["La vista previa no es válida para presentar. Debes firmar y enviar en la sede oficial y obtener el justificante con CSV."],
  documents: [{ label: "Descargar instrucciones oficiales en PDF", sourceId: "aeat.model-349.instructions-pdf.2026-06-12" }],
  officialLinks: [
    { label: "Ficha administrativa del procedimiento", sourceId: "aeat.model-349.procedure-record.2026-07-08" },
    { label: "Ayuda del formulario web", sourceId: "aeat.model-349.form-help.2026-06-19" },
    { label: "Ayuda de presentación mediante fichero", sourceId: "aeat.model-349.file-help.2026-06-19" },
    { label: "Nota informativa oficial", sourceId: "aeat.model-349.information-note.2026-07-08" },
    { label: "Validación oficial de NIF-IVA en VIES", href: "https://ec.europa.eu/taxation_customs/vies/#/vat-validation" },
  ],
  legalLinks: [
    { label: "Orden EHA/769/2010", sourceId: "boe.model-349.order-eha-769-2010.original" },
    { label: "Orden HAC/1274/2020", sourceId: "boe.model-349.order-hac-1274-2020.original" },
    { label: "Ley 37/1992 del IVA", href: "https://www.boe.es/buscar/act.php?id=BOE-A-1992-28740" },
  ],
  faq: [
    { question: "¿El Modelo 349 sirve para pagar IVA?", answer: "No. Es una declaración informativa; el IVA se liquida mediante los modelos que correspondan." },
    { question: "¿Tiene un importe mínimo?", answer: "No existe un importe mínimo general para incluir una operación declarable." },
    { question: "¿Qué significan los 50.000 €?", answer: "Solo determinan si puede utilizarse periodicidad trimestral; no exoneran de declarar." },
    { question: "¿Se presenta anualmente?", answer: "No. La presentación anual desapareció desde 2020." },
    { question: "¿Qué es el ROI?", answer: "El Registro de Operadores Intracomunitarios, solicitado mediante el Modelo 036." },
    { question: "¿Qué es VIES?", answer: "El sistema europeo de consulta de números de IVA. Conviene comprobar y conservar el resultado." },
    { question: "¿Una compra de bienes de la UE va en el 349?", answer: "Puede ser una adquisición intracomunitaria con clave A si se cumplen los requisitos." },
    { question: "¿Un servicio prestado a una empresa de la UE va en el 349?", answer: "Puede declararse con clave S según las reglas de localización e identificación." },
    { question: "¿Un servicio recibido de la UE va en el 349?", answer: "Puede declararse con clave I y generar inversión del sujeto pasivo si se cumplen los requisitos." },
    { question: "¿Una compra a un proveedor estadounidense va en el 349?", answer: "No por ser extranjera: Estados Unidos no es un Estado miembro de la Unión Europea." },
    { question: "¿Una factura pequeña puede ir en el 349?", answer: "Sí. No existe un mínimo general; una suscripción profesional de 25 € puede ser declarable." },
    { question: "¿Una factura de Google, Meta o una herramienta digital va siempre al 349?", answer: "No. Depende de la entidad que factura, el país, el NIF-IVA y la naturaleza del servicio." },
    { question: "¿Una factura del Reino Unido va en el 349?", answer: "Las operaciones ordinarias con Gran Bretaña no; Irlanda del Norte tiene un régimen específico para bienes con prefijo XI." },
    { question: "¿Una operación con Canarias va en el 349?", answer: "No por ese motivo. Canarias no forma parte del territorio de aplicación del IVA ni es otro Estado miembro." },
    { question: "¿Debe coincidir con el Modelo 303?", answer: "Los hechos deben poder conciliarse con el IVA periódico y los libros, aunque las casillas y periodos tengan reglas propias." },
    { question: "¿Tengo que incluirla también en el Modelo 347?", answer: "No debe duplicarse automáticamente una operación ya informada en el Modelo 349." },
    { question: "¿Puede estar relacionado con el Modelo 309?", answer: "Sí en determinados casos de personas sin autoliquidación periódica, pero no se presume para todas las operaciones." },
    { question: "¿Qué documentos debo conservar?", answer: "Factura, consulta VIES, transporte de bienes, pago, conversión de moneda y justificante de presentación." },
    { question: "¿Cómo corrijo un error?", answer: "Distingue corregir una declaración ya presentada de informar una rectificación comercial posterior y sigue las instrucciones oficiales." },
    { question: "¿La vista previa en PDF es válida?", answer: "No." },
  ],
  sourceIds: [
    "aeat.model-349.procedure-home.2026-07-08",
    "aeat.model-349.procedure-record.2026-07-08",
    "aeat.model-349.form-help.2026-06-19",
    "aeat.model-349.file-help.2026-06-19",
    "aeat.model-349.information-note.2026-07-08",
    "aeat.model-349.instructions-pdf.2026-06-12",
    "boe.model-349.order-eha-769-2010.original",
    "boe.model-349.order-hac-1274-2020.original",
  ],
} as const satisfies FiscalModelPracticalGuideV1;
