import { createBatch1PracticalGuideV1 } from "./create-batch-1-practical-guide.v1";

export const MODEL_156_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "156",
  category: "Deducción por maternidad · Información de terceros",
  statusLabel: "Resumen anual",
  statusTone: "current",
  effectiveYear: 2026,
  intro: [
    "El Modelo 156 es el resumen anual de cotizaciones de afiliados y mutualistas que suministran la Seguridad Social, mutualidades alternativas y otros organismos obligados para contrastar la deducción por maternidad.",
    "No lo presenta la madre ni el autónomo por sus propias cuotas, y la aparición de datos no concede automáticamente la deducción.",
  ],
  notices: [{ title: "El afiliado no presenta el 156", paragraphs: ["Si faltan meses o cotizaciones, el interesado debe pedir la corrección al organismo informante, no presentar una declaración 156 por su cuenta."] }],
  type: "Declaración informativa anual de cotizaciones.",
  presenter: "Seguridad Social, mutualidades alternativas y organismos gestores obligados.",
  nonPresenter: "La madre, el afiliado o el trabajador autónomo por sus propias cotizaciones.",
  periodicity: "Anual, como resumen de la información del ejercicio.",
  deadline: "En el plazo anual oficial de declaraciones informativas; debe comprobarse el calendario del ejercicio.",
  channel: "Presentación electrónica mediante fichero conforme al diseño vigente.",
  result: "Informativo: no reconoce ni paga la deducción.",
  included: ["Identificación de afiliados o mutualistas.", "Régimen, mutualidad y periodos de alta.", "Cotizaciones computables según el diseño.", "Correcciones de datos suministrados por el organismo."],
  excluded: ["La solicitud anticipada del Modelo 140.", "La declaración de Renta del Modelo 100.", "La información mensual del Modelo 185.", "Una petición de devolución del afiliado."],
  preparation: ["Conciliar afiliación, régimen y meses de alta.", "Comprobar cotizaciones con los registros del organismo.", "Validar identidad y periodos.", "Coordinar las correcciones con la información mensual del Modelo 185 cuando proceda."],
  correction: "El organismo informante corrige los registros. El contribuyente debe solicitarle la subsanación y después comprobar sus datos fiscales o la Renta.",
  procedureSourceId: "aeat.model-156.procedure-home.2026-04-07",
  recordSourceId: "aeat.model-156.procedure-record.2026-07-08",
  helpSourceId: "aeat.model-156.help.2026-02-02",
  legalSourceIds: ["boe.model-156.order-hac-3580-2003", "boe.model-156.order-hfp-1351-2021"],
  related: [
    { code: "140", href: "/consultor-fiscal/modelos/140", description: "Solicitud y variaciones del abono anticipado por maternidad." },
    { code: "100", href: "/consultor-fiscal/modelos/100", description: "Declaración anual donde se aplica la deducción cuando corresponde." },
    { code: "185", href: "/consultor-fiscal/modelos/185", description: "Información mensual de afiliación y cotizaciones desde 2026." },
  ],
  faq: [
    { question: "¿Lo presenta una trabajadora autónoma?", answer: "No. Lo presenta el organismo o mutualidad obligada." },
    { question: "¿Quién comunica mis cotizaciones?", answer: "La Seguridad Social, mutualidad alternativa u organismo gestor que las administra." },
    { question: "¿Para qué se utilizan?", answer: "Para contrastar periodos y cotizaciones relevantes, entre otros fines, para la deducción por maternidad." },
    { question: "¿Concede la deducción?", answer: "No por sí solo; la persona debe cumplir todos los requisitos." },
    { question: "¿Qué diferencia existe con el Modelo 185?", answer: "El 156 es un resumen anual; el 185 suministra información mensualmente desde 2026." },
    { question: "¿Qué hago si faltan meses?", answer: "Solicita la corrección al organismo informante y conserva la documentación de alta y cotización." },
    { question: "¿Cuándo se presenta?", answer: "En el plazo anual que publique la AEAT para el ejercicio." },
    { question: "¿Puedo corregirlo personalmente?", answer: "No como declarante; la corrección corresponde al organismo que suministró los datos." },
  ],
});

export const MODEL_159_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "159",
  category: "Energía eléctrica · Información de terceros",
  statusLabel: "Declaración anual",
  statusTone: "current",
  effectiveYear: 2026,
  intro: [
    "El Modelo 159 informa anualmente sobre contratos, puntos de suministro y consumo de energía eléctrica a través de las entidades del sector obligadas.",
    "No lo presenta el consumidor ni un autónomo por tener luz contratada, y no es una factura ni una autoliquidación.",
  ],
  notices: [{ title: "La información procede de la compañía obligada", paragraphs: ["Si el CUPS, titular o inmueble es incorrecto, solicita primero la rectificación a la entidad que suministró la información."] }],
  type: "Declaración informativa anual de consumo eléctrico.",
  presenter: "Comercializadores, distribuidores u operadores del sector eléctrico obligados por la norma.",
  nonPresenter: "El titular del contrato, el propietario del inmueble o un autónomo por consumir electricidad.",
  periodicity: "Anual respecto de contratos, consumos e importes del ejercicio.",
  deadline: "En el plazo anual oficial; debe revisarse el calendario de declaraciones informativas.",
  channel: "Presentación electrónica mediante fichero ajustado al diseño vigente.",
  result: "Informativo: no genera impuesto ni modifica una factura.",
  included: ["Titular y CUPS del punto de suministro.", "Dirección y referencia catastral cuando proceda.", "Potencia, consumo e importes facturados.", "Altas, bajas y uso o destino informado del inmueble."],
  excluded: ["Una factura eléctrica.", "El cálculo de un gasto deducible.", "La declaración anual de Renta o Sociedades.", "Una comprobación automática de actividad económica."],
  preparation: ["Conciliar CUPS y titularidad contractual.", "Validar dirección y referencia catastral.", "Revisar consumos e importes del periodo.", "Controlar altas y bajas del contrato."],
  correction: "La entidad obligada debe corregir el fichero. El consumidor puede aportar contrato y facturas para pedir la subsanación, pero no presenta un Modelo 159 propio.",
  procedureSourceId: "aeat.model-159.procedure-home.2026-03-01",
  recordSourceId: "aeat.model-159.procedure-record.2026-07-08",
  helpSourceId: "aeat.model-159.help.2026-02-03",
  legalSourceIds: ["boe.model-159.order-hac-672-2024"],
  related: [
    { code: "100", href: "/consultor-fiscal/modelos/100", description: "Declaración anual de Renta del titular cuando corresponda." },
    { code: "200", href: "/consultor-fiscal/modelos/200", description: "Impuesto sobre Sociedades de la entidad." },
    { code: "347", href: "/consultor-fiscal/modelos/347", description: "Operaciones con terceros, con reglas y exclusiones propias." },
  ],
  faq: [
    { question: "¿Lo presenta el titular del contrato?", answer: "No. Lo presenta la entidad eléctrica obligada." },
    { question: "¿Qué empresa lo presenta?", answer: "La comercializadora, distribuidora u operador que determine la normativa." },
    { question: "¿Qué datos comunica?", answer: "Titular, CUPS, inmueble, potencia, consumo, importes y movimientos del contrato previstos en el diseño." },
    { question: "¿Incluye la referencia catastral?", answer: "Sí cuando procede y está prevista para identificar el inmueble." },
    { question: "¿Genera un impuesto?", answer: "No. Es informativo." },
    { question: "¿Por qué aparece el consumo en mis datos fiscales?", answer: "Porque la AEAT recibe información de terceros para contrastar inmuebles, contratos y actividades." },
    { question: "¿Cuándo se presenta?", answer: "Anualmente, en el plazo oficial del ejercicio." },
    { question: "¿Cómo se corrige un CUPS erróneo?", answer: "Pide la corrección a la entidad que lo comunicó; ella debe rectificar el registro." },
  ],
});

export const MODEL_165_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "165",
  category: "Inversión en empresas nuevas · Información",
  statusLabel: "Declaración anual",
  statusTone: "current",
  effectiveYear: 2026,
  intro: [
    "El Modelo 165 informa de los certificados individuales que emiten determinadas entidades de nueva o reciente creación a sus socios o partícipes.",
    "Lo presenta la empresa que recibió la inversión, no el inversor; ni el certificado ni el 165 garantizan por sí solos la deducción en Renta.",
  ],
  notices: [{ title: "Ser una startup no basta", paragraphs: ["La entidad, la inversión, la participación y la permanencia deben cumplir los requisitos legales. Porcentajes y límites se revisan por ejercicio."] }],
  type: "Declaración informativa anual de certificados a inversores.",
  presenter: "La entidad de nueva o reciente creación que emite certificados y cumple los requisitos del incentivo.",
  nonPresenter: "El socio inversor o cualquier sociedad por el mero hecho de ser reciente.",
  periodicity: "Anual respecto de los certificados e inversiones del ejercicio.",
  deadline: "En el plazo anual oficial de declaraciones informativas.",
  channel: "Presentación electrónica mediante fichero conforme al diseño vigente.",
  result: "Informativo: no concede ni paga la deducción.",
  included: ["Identidad del inversor y de la entidad.", "Fecha e importe de suscripción o ampliación de capital.", "Participación y certificado individual emitido.", "Requisitos de forma societaria, actividad, fondos propios y antigüedad que deben comprobarse."],
  excluded: ["Garantizar la deducción del inversor.", "Inversiones en cualquier empresa sin requisitos.", "Calcular automáticamente porcentaje, base máxima o permanencia.", "La declaración de Renta o Sociedades."],
  preparation: ["Verificar requisitos de la entidad en el ejercicio.", "Conciliar escrituras, desembolsos y libro de socios.", "Emitir certificados coherentes con el fichero.", "Revisar porcentajes, vinculación y permanencia aplicables."],
  correction: "La entidad debe corregir tanto el registro como el certificado entregado al socio. El inversor debe conservar el certificado rectificado para su declaración.",
  procedureSourceId: "aeat.model-165.procedure-home.2026-07-08",
  recordSourceId: "aeat.model-165.procedure-record.2026-07-08",
  helpSourceId: "aeat.model-165.help.2026-02-02",
  legalSourceIds: ["boe.model-165.order-hap-2455-2013", "boe.model-165.order-hfp-1284-2023"],
  related: [
    { code: "100", href: "/consultor-fiscal/modelos/100", description: "Declaración del inversor donde se aplica la deducción si procede." },
    { code: "200", href: "/consultor-fiscal/modelos/200", description: "Declaración del Impuesto sobre Sociedades de la entidad." },
    { code: "036", href: "/consultor-fiscal/modelos/036", description: "Situación censal y actividad de la entidad." },
  ],
  faq: [
    { question: "¿Lo presenta el inversor?", answer: "No. Lo presenta la empresa que emitió el certificado." },
    { question: "¿Toda startup presenta el Modelo 165?", answer: "No. Solo las entidades que cumplen los requisitos y emiten los certificados afectados." },
    { question: "¿Qué debe certificar la empresa?", answer: "La inversión y los datos exigidos para acreditar que la entidad y la operación cumplen las condiciones." },
    { question: "¿El certificado garantiza la deducción?", answer: "No. El inversor debe cumplir también sus requisitos personales, de participación y permanencia." },
    { question: "¿Qué participación puede tener el inversor?", answer: "La que permita la normativa del ejercicio; debe revisarse junto con la vinculación familiar o societaria." },
    { question: "¿Cuánto tiempo debe mantener las acciones?", answer: "El periodo legal vigente del incentivo; no debe fijarse sin comprobar el ejercicio de la inversión." },
    { question: "¿Cuándo se presenta?", answer: "Anualmente, en el plazo oficial publicado." },
    { question: "¿Qué ocurre si el certificado es erróneo?", answer: "La entidad debe rectificar certificado y declaración para mantenerlos coherentes." },
  ],
});

export const MODEL_170_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "170",
  category: "Pagos · Información de terceros",
  statusLabel: "Mensual desde 2026",
  statusTone: "current",
  effectiveYear: 2026,
  monthlyFromYear: 2026,
  firstMonthlyFiling: "2026-02",
  intro: [
    "Desde 2026, el Modelo 170 informa mensualmente de operaciones gestionadas mediante tarjetas y pagos asociados a números de teléfono móvil para empresarios o profesionales establecidos en España.",
    "Lo presenta la entidad de crédito, pago o dinero electrónico que gestiona los cobros, incluidas las entidades obligadas que actúan desde otro Estado; no lo presenta el comercio que cobra.",
  ],
  notices: [
    { title: "Desde 2026 es mensual", paragraphs: ["Cada declaración se refiere al mes anterior y se presenta durante el mes siguiente. La primera mensual correspondió a enero de 2026 y se presentó en febrero."] },
    { title: "El comercio es informado, no declarante", paragraphs: ["Los importes son cobros gestionados, no beneficio neto ni base fiscal automática. El comercio debe conciliar devoluciones e incidencias con su entidad de pago."] },
  ],
  type: "Declaración informativa mensual mediante servicio web.",
  presenter: "Entidades de crédito, pago o dinero electrónico que gestionan cobros para empresarios o profesionales establecidos en España.",
  nonPresenter: "El comercio, autónomo o profesional que recibe los cobros.",
  periodicity: "Mensual desde enero de 2026; informa el mes natural anterior.",
  deadline: "Durante el mes natural siguiente. La extensión técnica solo procede en los casos y términos expresamente publicados.",
  channel: "Servicio web; el cliente AEAT puede utilizarse para envíos dentro del límite técnico publicado.",
  result: "Informativo: no calcula beneficio, IVA ni cuota a pagar.",
  included: ["Comercios y profesionales establecidos en España.", "Cobros con tarjetas físicas o virtuales.", "Pagos asociados a números de teléfono móvil gestionados por la entidad.", "Terminales, número de operaciones, importes mensuales, cuentas e identificador de registro.", "Altas, modificaciones y bajas de registros."],
  excluded: ["Pagos P2P entre particulares no gestionados como cobros empresariales.", "El beneficio o margen neto del comercio.", "La operativa anual de todas las tarjetas del Modelo 174.", "Los saldos y movimientos de cuentas del Modelo 196."],
  preparation: ["Identificar correctamente al comercio y su establecimiento en España.", "Separar tarjeta y pago móvil.", "Conciliar operaciones, devoluciones, terminales y cuentas.", "Aplicar A0, A1 o baja según el servicio y conservar las respuestas."],
  correction: "La entidad de pago corrige el registro mediante el servicio web. El comercio debe comunicarle el error con sus liquidaciones, pero no presentar un Modelo 170 propio.",
  procedureSourceId: "aeat.model-170.procedure-home.2026-07-08",
  recordSourceId: "aeat.model-170.procedure-record.2026-03-04",
  helpSourceId: "aeat.model-170.faq.2026-07-08",
  legalSourceIds: ["boe.model-170.order-hac-747-2025", "boe.model-170.order-eha-97-2010"],
  related: [
    { code: "171", href: "/consultor-fiscal/modelos/171", description: "Operaciones de efectivo y cobros de documentos informados anualmente." },
    { code: "174", href: "/consultor-fiscal/modelos/174", description: "Contratos, personas y operativa anual de todo tipo de tarjetas." },
    { code: "379", href: "/consultor-fiscal/modelos/379", description: "Información de pagos transfronterizos con finalidad y obligados distintos." },
  ],
  faq: [
    { question: "¿Lo presenta el comercio?", answer: "No. Lo presenta la entidad que gestiona sus cobros." },
    { question: "¿Quién comunica mis cobros?", answer: "La entidad de crédito, pago o dinero electrónico obligada que presta el servicio." },
    { question: "¿Es anual?", answer: "No desde 2026: es mensual." },
    { question: "¿Incluye Bizum u otros pagos móviles?", answer: "Incluye pagos asociados a números de teléfono móvil gestionados como cobros empresariales; no los pagos P2P ordinarios." },
    { question: "¿Es lo mismo que el beneficio?", answer: "No. Son cobros brutos gestionados y no descuentan automáticamente compras, gastos o impuestos." },
    { question: "¿Se incluyen devoluciones?", answer: "La entidad debe seguir la especificación para reflejar importes y correcciones; el comercio debe conciliar sus liquidaciones." },
    { question: "¿Cómo se corrige?", answer: "La entidad presenta la modificación o baja del registro por el servicio web." },
    { question: "¿Qué ocurre si la entidad está fuera de España?", answer: "Puede quedar obligada si presta el servicio a empresarios establecidos en España en los supuestos previstos, incluso en libre prestación." },
  ],
});

export const MODEL_171_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "171",
  category: "Operaciones financieras · Efectivo",
  statusLabel: "Declaración anual",
  statusTone: "current",
  effectiveYear: 2026,
  intro: [
    "El Modelo 171 informa anualmente de determinadas imposiciones, disposiciones de fondos y cobros de documentos que comunican las entidades financieras obligadas.",
    "No lo presenta el titular de la cuenta y no fija el límite legal de pagos en efectivo: que una operación se informe no significa que esté prohibida ni que exista automáticamente una infracción.",
  ],
  notices: [{ title: "Información no equivale a infracción", paragraphs: ["El umbral informativo general de 3.000 euros debe contrastarse con el diseño vigente y no debe confundirse con los límites legales de pagos en efectivo."] }],
  type: "Declaración informativa anual de operaciones financieras.",
  presenter: "Entidades de crédito y demás entidades financieras obligadas.",
  nonPresenter: "La persona que ingresa o retira efectivo, emite un cheque o es titular de la cuenta.",
  periodicity: "Anual, con operaciones individualizadas del ejercicio.",
  deadline: "Durante enero, conforme al calendario y diseño vigentes.",
  channel: "Presentación electrónica mediante fichero.",
  result: "Informativo: no genera cuota ni sanción automática.",
  included: ["Imposiciones y disposiciones de fondos incluidas por la norma.", "Cobros de cheques u otros documentos.", "Identificación, cuenta, fecha, moneda e importe.", "Operaciones que alcanzan el umbral informativo del diseño."],
  excluded: ["El límite jurídico de pagos en efectivo.", "Cobros con tarjeta o móvil del Modelo 170.", "Operativa completa de tarjetas del Modelo 174.", "Saldos e intereses ordinarios del Modelo 196."],
  preparation: ["Aplicar el umbral del diseño vigente.", "Individualizar fecha, cuenta e intervinientes.", "Separar imposición, disposición y cobro de documento.", "Controlar divisa, contravalor y correcciones."],
  correction: "La entidad financiera corrige el fichero. El cliente debe aportar justificantes y solicitarle la subsanación, no presentar un 171 personal.",
  procedureSourceId: "aeat.model-171.procedure-home.2026-03-01",
  recordSourceId: "aeat.model-171.procedure-record.2026-07-08",
  helpSourceId: "aeat.model-171.help.2026-02-02",
  document: { label: "Descargar diseño de registro del Modelo 171", sourceId: "aeat.model-171.register-design.pdf" },
  legalSourceIds: ["boe.model-171.order-eha-98-2010", "boe.models-171-174.order-hac-747-2025"],
  related: [
    { code: "170", href: "/consultor-fiscal/modelos/170", description: "Cobros empresariales con tarjeta y móvil informados mensualmente." },
    { code: "174", href: "/consultor-fiscal/modelos/174", description: "Contratos y operativa anual de tarjetas." },
    { code: "196", href: "/consultor-fiscal/modelos/196", description: "Cuentas, saldos y rendimientos informados por entidades." },
  ],
  faq: [
    { question: "¿Lo presenta la persona que ingresa efectivo?", answer: "No. Lo presenta la entidad financiera." },
    { question: "¿Qué operaciones se informan?", answer: "Determinadas imposiciones, retiradas y cobros de documentos individualizados." },
    { question: "¿Cuál es el umbral?", answer: "La referencia general es 3.000 euros cuando resulte aplicable; debe comprobarse el diseño vigente." },
    { question: "¿Es lo mismo que el límite de pagos en efectivo?", answer: "No. Son reglas diferentes." },
    { question: "¿Se informa un cheque?", answer: "Sí, cuando el cobro del documento queda incluido por la norma." },
    { question: "¿Es anual?", answer: "Sí." },
    { question: "¿Cómo se corrige?", answer: "La entidad financiera rectifica el registro en su declaración." },
    { question: "¿Genera un impuesto?", answer: "No. Es informativo y no implica por sí solo una infracción." },
  ],
});

export const MODEL_174_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "174",
  category: "Tarjetas · Información de terceros",
  statusLabel: "Primera presentación · enero de 2027",
  statusTone: "future",
  effectiveYear: 2026,
  taxPeriodYear: 2026,
  filingYear: 2027,
  intro: [
    "El Modelo 174 es la nueva declaración anual sobre contratos, titulares, autorizados, beneficiarios y operaciones de todo tipo de tarjetas.",
    "La primera información corresponde a 2026 y se presentará en enero de 2027 mediante mensajes informáticos; el titular de la tarjeta no presenta el modelo.",
  ],
  notices: [
    { title: "Primera campaña futura", paragraphs: ["No debe mostrarse como un trámite ya presentable durante 2026. La primera campaña informa 2026 y se abre en enero de 2027."] },
    { title: "No es el Modelo 170", paragraphs: ["El 170 informa mensualmente cobros gestionados para comercios; el 174 informa anualmente contratos, personas relacionadas y operativa de tarjetas."] },
  ],
  type: "Declaración informativa anual mediante servicio web.",
  presenter: "Entidades emisoras y demás obligados definidos por la Orden HAC/747/2025.",
  nonPresenter: "El titular, autorizado, beneficiario o usuario de la tarjeta.",
  periodicity: "Anual; la primera información corresponde al ejercicio 2026.",
  deadline: "Primera presentación durante enero de 2027, con la extensión técnica únicamente en los supuestos oficiales.",
  channel: "Mensajes informáticos del servicio web con altas, modificaciones y bajas.",
  result: "Informativo: no liquida el gasto ni la renta del titular.",
  included: ["Tarjetas de crédito, débito, débito diferido, dinero electrónico, efectivo y otros tipos definidos.", "Titular del contrato, autorizados, beneficiarios y otras personas relacionadas.", "Abonos, recargas en efectivo, cargos, compras y retiradas.", "Contrato, tarjeta, cuenta o IBAN e identificación extranjera.", "Registros de alta, modificación y baja."],
  excluded: ["Una declaración personal del usuario.", "Los cobros mensuales de un comercio del Modelo 170.", "La atribución automática de gasto, renta o fraude.", "Una campaña de presentación durante 2026."],
  preparation: ["Mapear contratos, tarjetas y personas relacionadas.", "Clasificar el tipo de tarjeta y operación.", "Conciliar cargos, abonos, recargas y retiradas.", "Validar A0, A1, A2 e identificadores según el diseño."],
  correction: "La entidad obligada modifica o da de baja el registro por el servicio web. El usuario debe pedir la corrección al emisor y conservar la documentación.",
  procedureSourceId: "aeat.model-174.procedure-home.2026-07-08",
  recordSourceId: "aeat.model-174.procedure-record.2026-07-08",
  document: { label: "Consultar contenido y diseño oficial del Modelo 174", sourceId: "aeat.model-174.content-design.pdf" },
  legalSourceIds: ["boe.models-171-174.order-hac-747-2025"],
  related: [
    { code: "170", href: "/consultor-fiscal/modelos/170", description: "Cobros empresariales con tarjeta y móvil informados mensualmente." },
    { code: "196", href: "/consultor-fiscal/modelos/196", description: "Información de cuentas y rendimientos financieros." },
  ],
  allowProcedureAction: false,
  primaryActionLabel: "Consultar la futura ficha oficial del Modelo 174",
  externalActionNotice: "La primera presentación corresponde a enero de 2027. Factu no recoge tarjetas, contratos ni movimientos.",
  faq: [
    { question: "¿Lo presenta el titular?", answer: "No. Lo presenta la entidad emisora u obligado definido por la norma." },
    { question: "¿Desde cuándo existe?", answer: "La información comienza con el ejercicio 2026." },
    { question: "¿Qué ejercicio se informa primero?", answer: "2026, presentado en enero de 2027." },
    { question: "¿Qué tarjetas incluye?", answer: "Los tipos definidos por la norma: crédito, débito, débito diferido, dinero electrónico, efectivo y otros." },
    { question: "¿Incluye autorizados?", answer: "Sí, junto con titulares, beneficiarios y demás personas relacionadas previstas." },
    { question: "¿Incluye retiradas?", answer: "Sí, cuando forman parte de los campos y operaciones exigidos." },
    { question: "¿Qué diferencia tiene con el 170?", answer: "El 170 mira cobros mensuales de comercios; el 174 mira anualmente tarjetas, personas y operativa." },
    { question: "¿Cómo se corrige un registro?", answer: "La entidad obligada usa los mensajes de modificación o baja del servicio web." },
  ],
});
