import { createBatch1PracticalGuideV1 } from "./create-batch-1-practical-guide.v1";

export const MODEL_102_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "102",
  category: "IRPF · Segundo plazo de Renta",
  statusLabel: "Documento de ingreso",
  statusTone: "auxiliary",
  effectiveYear: 2026,
  taxPeriodYear: 2025,
  filingYear: 2026,
  intro: [
    "El Modelo 102 es el documento para ingresar el segundo plazo de la declaración de la Renta cuando el contribuyente fraccionó el resultado y ese segundo pago no quedó domiciliado.",
    "No es una nueva declaración, no recalcula el IRPF y no sirve para rectificar el Modelo 100 ni para pagar otras deudas.",
  ],
  notices: [
    { title: "Comprueba antes si el segundo plazo está domiciliado", paragraphs: ["Si el 40 % quedó domiciliado, no debe volver a pagarse manualmente. Verifica la declaración y los datos bancarios antes de usar el documento."] },
  ],
  type: "Documento de ingreso asociado a la declaración del IRPF.",
  presenter: "El contribuyente que fraccionó la Renta y debe ingresar manualmente el segundo 40 %.",
  nonPresenter: "Quien domicilió correctamente el segundo plazo o quien quiere rectificar, aplazar otra deuda o presentar una complementaria.",
  periodicity: "Una vez por campaña cuando se eligió el fraccionamiento especial 60 % / 40 %.",
  deadline: "La fecha exacta cambia cada campaña; debe consultarse en el calendario de Renta del ejercicio.",
  channel: "Documento de ingreso en entidad colaboradora y herramientas oficiales de pago vinculadas al Modelo 100; no es una declaración electrónica independiente.",
  result: "Ingreso del segundo 40 % sin intereses si se cumplen las condiciones del fraccionamiento especial.",
  included: ["NIF, ejercicio e identificación del contribuyente.", "Importe pendiente del segundo plazo.", "Referencia de la declaración del Modelo 100.", "Pago y justificante de la entidad colaboradora."],
  excluded: ["Rectificar la declaración de Renta.", "Solicitar un aplazamiento general.", "Pagar una complementaria u otro impuesto.", "Duplicar un cargo ya domiciliado."],
  preparation: ["Consultar la declaración presentada y confirmar el segundo plazo.", "Comprobar si existe domiciliación y si fue atendida.", "Usar el importe exacto del 40 % pendiente.", "Guardar justificante y conciliarlo con la Renta."],
  correction: "Si el importe de la Renta es incorrecto, corrige el Modelo 100 por su cauce. Si el problema es el pago, consulta deuda, recargos o incidencias en la AEAT sin emitir otro 102 duplicado.",
  procedureSourceId: "aeat.model-102.procedure-home.2026-06-09",
  recordSourceId: "aeat.model-102.procedure-record.2026-06-09",
  document: { label: "Descargar documento oficial Modelo 102 de la campaña", sourceId: "aeat.model-102.form-pdf.2026-04-17" },
  legalSourceIds: ["boe.irpf-2025-order-hac-277-2026"],
  related: [{ code: "100", href: "/consultor-fiscal/modelos/100", description: "Declaración anual de Renta que origina el resultado y el fraccionamiento." }],
  allowProcedureAction: false,
  externalActionNotice: "El Modelo 102 no se presenta como una declaración electrónica independiente. Factu no realiza pagos ni consulta cuentas bancarias.",
  faq: [
    { question: "¿Qué porcentaje se paga?", answer: "El segundo plazo representa el 40 % del resultado fraccionado de la Renta." },
    { question: "¿Lo uso si el pago estaba domiciliado?", answer: "No, salvo que la AEAT confirme una incidencia y el importe siga pendiente; evita un pago duplicado." },
    { question: "¿Es una nueva declaración?", answer: "No. Es un documento de ingreso asociado al Modelo 100 ya presentado." },
    { question: "¿Puede pagarse por internet?", answer: "Puede utilizarse el servicio oficial de pago disponible, pero no se presenta como una declaración independiente." },
    { question: "¿Dónde se presenta?", answer: "En una entidad colaboradora o mediante el cauce de pago oficial indicado por la AEAT para la campaña." },
    { question: "¿Cuál es la fecha límite?", answer: "La fija cada campaña de Renta; debe comprobarse el ejercicio concreto." },
    { question: "¿Qué ocurre si no pago en plazo?", answer: "Puede iniciarse el periodo ejecutivo y aplicarse recargos o intereses según la situación; consulta la deuda oficial." },
    { question: "¿Cómo corrijo el importe?", answer: "El cálculo se corrige en la declaración de Renta, no modificando aisladamente el Modelo 102." },
  ],
});

export const MODEL_113_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "113",
  category: "IRPF · Cambio de residencia",
  statusLabel: "Comunicación especial",
  statusTone: "current",
  effectiveYear: 2026,
  intro: [
    "El Modelo 113 comunica determinadas ganancias patrimoniales latentes por cambio de residencia a otro Estado de la Unión Europea o del EEE con intercambio efectivo de información.",
    "No lo presenta cualquier persona que emigra: exige residencia previa y participaciones que superen los umbrales legales del impuesto de salida.",
  ],
  notices: [
    { title: "No sustituye el cambio de domicilio", paragraphs: ["El Modelo 030 comunica el domicilio y la residencia censal. El 113 atiende una obligación específica sobre determinadas acciones o participaciones."] },
    { title: "Umbrales que deben comprobarse", paragraphs: ["La regla general exige, entre otros requisitos, un valor conjunto superior a 4.000.000 de euros o una participación superior al 25 % en una entidad cuyo valor exceda de 1.000.000 de euros. Debe revisarse la norma vigente y la valoración concreta."] },
  ],
  type: "Comunicación del régimen especial del impuesto de salida.",
  presenter: "Persona física que traslada su residencia a un Estado admitido y cumple residencia previa y umbrales de participación.",
  nonPresenter: "Cualquier emigrante por el mero cambio de país o quien solo necesita comunicar su domicilio mediante el Modelo 030.",
  periodicity: "No periódica: nace por el traslado y por determinados hechos posteriores.",
  deadline: "Depende del cambio de residencia y de la transmisión, nuevo traslado o incumplimiento que deba comunicarse.",
  channel: "Presentación electrónica conforme al procedimiento y diseño oficial del Modelo 113.",
  result: "Comunicación fiscal; no supone necesariamente un pago inmediato.",
  included: ["Acciones o participaciones afectadas y su valor de mercado.", "País y fecha del traslado.", "Residencia en España durante al menos diez de los quince periodos anteriores, cuando resulte aplicable.", "Ventas posteriores, traslado fuera del ámbito admitido u otros hechos que la norma obliga a comunicar."],
  excluded: ["El simple cambio de domicilio.", "Activos distintos de las participaciones afectadas.", "La declaración ordinaria de Renta.", "Una declaración general de bienes en el extranjero."],
  preparation: ["Documentar residencia de los quince periodos previos.", "Identificar participaciones, porcentajes y valores de mercado.", "Comprobar el Estado de destino y el intercambio de información.", "Mantener un control de transmisiones y traslados posteriores."],
  correction: "Rectifica la comunicación cuando cambien o sean incorrectos los valores, participaciones o hechos declarados. Un hecho posterior puede tener un plazo propio y no debe esperar a la Renta anual.",
  procedureSourceId: "aeat.model-113.procedure-home.2026-06-09",
  recordSourceId: "aeat.model-113.procedure-record.2026-06-09",
  helpSourceId: "aeat.model-113.help.2026-01-09",
  legalSourceIds: ["boe.model-113.order-2015", "boe.order-hap-2194-2013"],
  related: [
    { code: "030", href: "/consultor-fiscal/modelos/030", description: "Comunicación censal de domicilio y residencia." },
    { code: "100", href: "/consultor-fiscal/modelos/100", description: "Declaración anual del IRPF." },
    { code: "720", href: "/consultor-fiscal/modelos/720", description: "Información de determinados bienes y derechos en el extranjero." },
  ],
  faq: [
    { question: "¿Lo presenta cualquier persona que se muda?", answer: "No. Solo quien cumple los requisitos de residencia previa y los umbrales de participaciones afectados." },
    { question: "¿Qué activos están afectados?", answer: "Determinadas acciones o participaciones cuyo valor o porcentaje supera los límites legales." },
    { question: "¿Cuáles son los límites?", answer: "Como referencia general, valor conjunto superior a 4 millones o más del 25 % en una entidad valorada por encima de 1 millón, sujetos a la norma vigente." },
    { question: "¿Se paga al salir de España?", answer: "No necesariamente en los traslados acogidos al régimen especial; hay que distinguir comunicación, aplazamiento y exigibilidad." },
    { question: "¿Qué ocurre si vendo después?", answer: "La transmisión puede ser un hecho que deba comunicarse y afectar al régimen; debe controlarse su plazo específico." },
    { question: "¿Qué pasa si me traslado fuera de la UE o del EEE admitido?", answer: "El nuevo traslado puede romper las condiciones y activar consecuencias que deben revisarse y comunicarse." },
    { question: "¿Sustituye al cambio de domicilio del Modelo 030?", answer: "No. Ambos responden a finalidades distintas." },
    { question: "¿Qué plazo tengo?", answer: "Depende del hecho comunicado; consulta la ficha e instrucciones oficiales en cada caso." },
  ],
});

export const MODEL_136_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "136",
  category: "IRPF e IRNR · Premios",
  statusLabel: "Autoliquidación trimestral",
  statusTone: "current",
  effectiveYear: 2026,
  intro: [
    "El Modelo 136 autoliquida el gravamen especial de determinados premios de loterías y apuestas cuando el premio gravado no ha soportado la retención correspondiente.",
    "No se utiliza para cualquier premio. Normalmente el pagador practica la retención mediante el Modelo 230; el 136 corresponde al perceptor solo en los supuestos previstos.",
  ],
  notices: [
    { title: "Premios compartidos", paragraphs: ["La exención y la parte gravada se distribuyen entre los beneficiarios según su participación. El ejemplo de esta guía supone un único titular."] },
  ],
  type: "Autoliquidación del gravamen especial sobre determinados premios.",
  presenter: "El perceptor cuando el premio sujeto no ha soportado la retención que correspondía.",
  nonPresenter: "Quien recibe un premio ya correctamente retenido o un premio fuera del gravamen especial.",
  periodicity: "Trimestral cuando se produce un premio que debe autoliquidarse.",
  deadline: "En los plazos trimestrales oficiales del periodo en que se cobra el premio.",
  channel: "Presentación electrónica del Modelo 136 y pago de la cuota resultante.",
  result: "Ingreso del 20 % sobre la parte del premio que exceda de la cuantía exenta aplicable.",
  included: ["Premios incluidos de SELAE, comunidades autónomas, ONCE, Cruz Roja y entidades análogas admitidas.", "Parte exenta general de 40.000 euros cuando se cumplen los requisitos vigentes.", "Prorrateo de la exención en participaciones y premios compartidos.", "Base gravada y cuota al 20 %."],
  excluded: ["Premios ordinarios sujetos a otras reglas del IRPF.", "Premios que ya soportaron correctamente la retención.", "La declaración informativa o retención del pagador mediante 230 y 270."],
  preparation: ["Identificar entidad organizadora y justificante del premio.", "Comprobar retención practicada y parte exenta.", "Repartir titularidad y premio compartido.", "Calcular la base gravada sin duplicar la retención."],
  correction: "Si la cuota fue excesiva, solicita rectificación o devolución por el cauce oficial; si faltó importe, presenta la complementaria del periodo correcto.",
  procedureSourceId: "aeat.model-136.procedure-home.2026-06-09",
  recordSourceId: "aeat.model-136.procedure-record.2026-06-09",
  legalSourceIds: ["boe.model-136.order-hap-70-2013", "boe.order-hac-763-2018"],
  related: [
    { code: "230", href: "/consultor-fiscal/modelos/230", description: "Autoliquidación de la retención practicada por el pagador." },
    { code: "270", href: "/consultor-fiscal/modelos/270", description: "Resumen anual de premios y retenciones." },
    { code: "100", href: "/consultor-fiscal/modelos/100", description: "Declaración anual de Renta, sin volver a integrar la parte sujeta al gravamen especial como premio ordinario." },
  ],
  extraSections: [
    {
      id: "model-136-example",
      title: "Ejemplo orientativo con un único titular",
      cards: [{ title: "Premio de 100.000 euros", bullets: ["Parte exenta: 40.000 euros.", "Base gravada: 60.000 euros.", "Cuota al 20 %: 12.000 euros.", "Si el premio es compartido, primero se distribuyen premio y exención entre los beneficiarios."] }],
    },
  ],
  faq: [
    { question: "¿Se presenta por cualquier premio?", answer: "No. Solo por premios incluidos en el gravamen especial y cuando corresponde autoliquidar por falta de retención." },
    { question: "¿Cuál es la parte exenta?", answer: "La referencia general vigente es 40.000 euros por décimo, fracción, cupón o apuesta, si se cumplen las condiciones." },
    { question: "¿Qué ocurre si el premio es compartido?", answer: "Premio y exención se reparten según el porcentaje real de cada beneficiario." },
    { question: "¿Qué tipo se aplica?", answer: "El 20 % sobre la parte gravada." },
    { question: "¿Cuándo lo presenta el ganador?", answer: "Cuando el premio sujeto no soportó la retención correspondiente y la norma exige autoliquidarlo." },
    { question: "¿Qué diferencia hay con el Modelo 230?", answer: "El 230 lo usa el pagador para ingresar la retención; el 136 lo usa el perceptor en el supuesto de falta de retención." },
    { question: "¿Cuándo se presenta?", answer: "En el plazo trimestral del periodo en que se cobró el premio." },
    { question: "¿El premio se incluye otra vez en la Renta?", answer: "La parte sometida al gravamen especial no debe duplicarse como premio ordinario; revisa otras rentas o rendimientos asociados." },
  ],
});

export const MODEL_146_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "146",
  category: "IRPF · Retenciones de pensiones",
  statusLabel: "Solicitud de cálculo",
  statusTone: "current",
  effectiveYear: 2026,
  intro: [
    "El Modelo 146 permite a determinados pensionistas con dos o más pagadores solicitar que la AEAT determine un tipo conjunto de retención.",
    "No es el procedimiento general de una persona con dos empleos, no cambia la pensión y no elimina por sí solo la obligación de presentar la Renta.",
  ],
  notices: [{ title: "Solo para pensionistas con varios pagadores", paragraphs: ["La solicitud debe acompañarse de los datos personales y familiares exigidos y revisarse cuando cambie una pensión o un pagador."] }],
  type: "Solicitud de determinación de retenciones.",
  presenter: "Pensionista que cobra prestaciones de dos o más pagadores incluidos en el procedimiento.",
  nonPresenter: "Una persona con dos empleos, un pensionista con un solo pagador o quien solo quiere aumentar voluntariamente su retención.",
  periodicity: "A solicitud del pensionista y con vigencia conforme al procedimiento.",
  deadline: "Debe presentarse en el plazo que permita aplicar el tipo al periodo correspondiente; comprueba el calendario oficial.",
  channel: "Presentación electrónica o presencial admitida por la ficha oficial.",
  result: "Documento de la AEAT con un tipo conjunto que se comunica a los pagadores.",
  included: ["Relación de pagadores y pensiones previstas.", "Importe anual estimado de las prestaciones.", "Datos personales y familiares relevantes para retenciones.", "Comunicación del tipo a los pagadores y cambios posteriores."],
  excluded: ["La declaración de Renta.", "Trabajos por cuenta ajena con dos empresas.", "Modificar el importe de la pensión.", "Garantizar que no resulte cuota en la Renta."],
  preparation: ["Reunir certificados o previsiones de cada pagador.", "Actualizar datos personales y familiares.", "Identificar altas, bajas o variaciones esperadas.", "Entregar la comunicación resultante a los pagadores que corresponda."],
  correction: "Si cambia una pensión, un pagador o la situación familiar, revisa si procede una nueva solicitud o comunicación; no mantengas el tipo anterior sin comprobar su vigencia.",
  procedureSourceId: "aeat.model-146.procedure-home.2026-06-09",
  recordSourceId: "aeat.model-146.procedure-record.2026-06-09",
  helpSourceId: "aeat.model-146.help.2026-01-09",
  document: { label: "Descargar formulario oficial Modelo 146", sourceId: "aeat.model-146.form-pdf.captured-2026-07-13" },
  legalSourceIds: ["boe.model-146.resolution-2003"],
  related: [
    { code: "100", href: "/consultor-fiscal/modelos/100", description: "Declaración anual del IRPF que sigue su propia obligación." },
    { code: "145", href: "/consultor-fiscal/modelos/145", description: "Comunicación de datos personales y familiares al pagador." },
  ],
  faq: [
    { question: "¿Sirve para una persona con dos trabajos?", answer: "No. Este procedimiento está diseñado para pensionistas con varios pagadores." },
    { question: "¿Qué pensionistas pueden solicitarlo?", answer: "Quienes perciben pensiones de dos o más pagadores incluidos y cumplen las condiciones oficiales." },
    { question: "¿Evita presentar la Renta?", answer: "No. La obligación anual se determina por las reglas del IRPF." },
    { question: "¿Quién calcula la nueva retención?", answer: "La AEAT determina el tipo conjunto a partir de la información aportada." },
    { question: "¿Debo comunicar datos familiares?", answer: "Sí, los que sean relevantes y exija el procedimiento." },
    { question: "¿Cuánto dura?", answer: "La vigencia depende del procedimiento y de que no cambien los datos; comprueba el documento emitido." },
    { question: "¿Qué ocurre si cambia una pensión?", answer: "Debe revisarse el cálculo y comunicarse la variación cuando proceda." },
    { question: "¿Dónde se presenta?", answer: "Por los canales electrónico o presencial publicados en la ficha oficial." },
  ],
});

export const MODEL_147_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "147",
  category: "IRPF · Trabajadores desplazados",
  statusLabel: "Comunicación de retenciones",
  statusTone: "current",
  effectiveYear: 2026,
  intro: [
    "El Modelo 147 permite a un trabajador por cuenta ajena desplazado a España anticipar el cambio de residencia fiscal a efectos de las retenciones de su nómina.",
    "No es la opción por el régimen especial de desplazados, no concede la llamada Ley Beckham y no sustituye el Modelo 149 ni el cambio censal del Modelo 030.",
  ],
  notices: [{ title: "No concede el régimen especial", paragraphs: ["Su finalidad es acreditar ante el pagador el tratamiento de retenciones cuando la permanencia prevista en España supera 183 días y se cumplen las condiciones del procedimiento."] }],
  type: "Comunicación anticipada para retenciones del trabajo.",
  presenter: "Trabajador por cuenta ajena desplazado a España con empleador residente o establecimiento permanente y permanencia prevista superior a 183 días.",
  nonPresenter: "Un autónomo, quien solicita la Ley Beckham o quien solo comunica un cambio de domicilio.",
  periodicity: "No periódica, vinculada al desplazamiento y al inicio de la relación laboral.",
  deadline: "Según las fechas de entrada e inicio de la relación; la AEAT dispone de hasta diez días hábiles para expedir el documento acreditativo cuando procede.",
  channel: "Presentación electrónica o por los canales admitidos, con documento del empleador.",
  result: "Documento acreditativo que el trabajador entrega al pagador para ajustar retenciones.",
  included: ["Fecha de entrada en España e inicio del trabajo.", "Permanencia prevista superior a 183 días.", "Identificación y certificado del empleador español o establecimiento permanente.", "Expedición y entrega al pagador del documento acreditativo."],
  excluded: ["La opción por el régimen especial del Modelo 149.", "La declaración anual del Modelo 151.", "Un certificado general de residencia.", "El cambio censal del Modelo 030."],
  preparation: ["Obtener el documento del empleador.", "Acreditar fechas de entrada e inicio laboral.", "Estimar la permanencia en el año natural.", "Entregar al pagador el documento emitido y comunicar cambios."],
  correction: "Si cambia la permanencia, la relación laboral o el empleador, informa a la AEAT y al pagador; el documento inicial no debe seguir aplicándose si sus hechos dejan de ser ciertos.",
  procedureSourceId: "aeat.model-147.procedure-home.2026-06-09",
  recordSourceId: "aeat.model-147.procedure-record.2026-06-09",
  helpSourceId: "aeat.model-147.help.2026-06-19",
  document: { label: "Descargar formulario oficial Modelo 147", sourceId: "aeat.model-147.form-pdf.captured-2026-07-13" },
  legalSourceIds: ["boe.model-147.order-hac-117-2003"],
  related: [
    { code: "030", href: "/consultor-fiscal/modelos/030", description: "Comunicación censal de domicilio y residencia." },
    { code: "149", href: "/consultor-fiscal/modelos/149", description: "Opción y comunicaciones del régimen especial de desplazados." },
    { code: "151", href: "/consultor-fiscal/modelos/151", description: "Declaración anual de quienes tributan por el régimen especial vigente." },
  ],
  faq: [
    { question: "¿Lo utiliza un autónomo?", answer: "No. El procedimiento se dirige a trabajadores por cuenta ajena." },
    { question: "¿Es la Ley Beckham?", answer: "No. La opción por ese régimen se comunica mediante el Modelo 149." },
    { question: "¿Me convierte automáticamente en residente?", answer: "No. Anticipa el tratamiento de retenciones sobre una previsión que debe cumplirse." },
    { question: "¿Qué debe certificar el empleador?", answer: "Los datos y fechas de la relación laboral y su condición de residente o establecimiento permanente, según el procedimiento." },
    { question: "¿Qué documento emite Hacienda?", answer: "Un documento acreditativo para que el pagador practique las retenciones correspondientes." },
    { question: "¿A quién se entrega?", answer: "Al pagador de los rendimientos del trabajo." },
    { question: "¿Qué plazo tiene la AEAT?", answer: "La ficha del procedimiento prevé hasta diez días hábiles para la expedición." },
    { question: "¿Qué ocurre si finalmente no permanezco 183 días?", answer: "Debe comunicarse el cambio y revisarse la residencia y las retenciones; no se mantiene la previsión como si se hubiera cumplido." },
  ],
});

export const MODEL_150_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "150",
  category: "IRPF · Régimen de desplazados",
  statusLabel: "Histórico · Régimen anterior a 2015",
  statusTone: "historical",
  intro: [
    "El Modelo 150 fue la declaración anual de quienes optaron por el régimen especial de trabajadores desplazados conforme a la normativa anterior al 1 de enero de 2015.",
    "No se utiliza para nuevas opciones ni para una declaración actual: el régimen vigente emplea los Modelos 149 y 151.",
  ],
  notices: [{ title: "No admite nuevas opciones", paragraphs: ["No presentes un Modelo 150 de 2026. La documentación y los PDFs de esta ficha sirven para consultas, rectificaciones o devoluciones de periodos históricos."] }],
  type: "Declaración anual histórica del antiguo régimen de desplazados.",
  presenter: "Contribuyente que aplicó válidamente el régimen anterior a 2015 para un periodo histórico afectado.",
  nonPresenter: "Una persona desplazada actualmente o quien desea optar ahora por el régimen especial.",
  periodicity: "Histórica; no existen nuevas campañas corrientes.",
  deadline: "Solo los plazos de rectificación, devolución o revisión del ejercicio antiguo que corresponda.",
  channel: "Consulta y gestiones históricas de la AEAT; no existe presentación corriente para 2026.",
  result: "Resultado histórico del IRPF del régimen anterior.",
  included: ["Declaraciones presentadas bajo opciones anteriores al 1 de enero de 2015.", "Consulta de justificantes y datos antiguos.", "Rectificación o devolución de ingresos de periodos no prescritos cuando proceda.", "Conservación de formularios e instrucciones históricas."],
  excluded: ["Nuevas opciones por el régimen especial.", "Declaraciones del régimen vigente, que usan el Modelo 151.", "Comunicaciones actuales de opción o renuncia, que usan el Modelo 149."],
  preparation: ["Identificar ejercicio y opción histórica.", "Recuperar declaración, justificante y documentación del periodo.", "Comprobar prescripción y procedimiento aplicable.", "No reutilizar el PDF antiguo para una campaña actual."],
  correction: "Una declaración histórica se corrige por el cauce de rectificación del ejercicio afectado. No se presenta un nuevo 150 corriente ni se convierte automáticamente en 151.",
  procedureSourceId: "aeat.model-150.procedure-home.2022-06-03",
  recordSourceId: "aeat.model-150.procedure-record.2026-06-09",
  document: { label: "Consultar instrucciones históricas del Modelo 150", sourceId: "aeat.model-150.instructions-pdf.2016-04-15" },
  legalSourceIds: ["boe.order-eha-848-2008", "boe.order-hap-2783-2015"],
  related: [
    { code: "149", href: "/consultor-fiscal/modelos/149", description: "Comunicaciones actuales de opción, renuncia y exclusión." },
    { code: "151", href: "/consultor-fiscal/modelos/151", description: "Declaración anual vigente del régimen especial de desplazados." },
  ],
  allowProcedureAction: false,
  externalActionNotice: "Ficha histórica. No ofrece una nueva presentación, alta ni opción por el régimen especial.",
  faq: [
    { question: "¿Sigue vigente para nuevas solicitudes?", answer: "No. Las nuevas situaciones utilizan los Modelos 149 y 151." },
    { question: "¿Puedo presentar un Modelo 150 de 2026?", answer: "No. Es un modelo histórico del régimen anterior a 2015." },
    { question: "¿Qué modelo se utiliza actualmente?", answer: "El 149 para comunicaciones del régimen y el 151 para la declaración anual vigente." },
    { question: "¿Puedo consultar una declaración antigua?", answer: "Sí, mediante los servicios de consulta y el área personal de la AEAT cuando esté disponible." },
    { question: "¿Cómo se corrige un ejercicio antiguo?", answer: "Por el procedimiento de rectificación del ejercicio concreto, comprobando prescripción y documentación." },
    { question: "¿Es lo mismo que el Modelo 151?", answer: "No. El 151 pertenece al régimen vigente; el 150 documenta el régimen anterior." },
    { question: "¿Puedo usar el PDF para darme de alta?", answer: "No. El PDF es histórico y no sirve como opción actual." },
    { question: "¿Dónde conservo el justificante?", answer: "Con la declaración y la documentación fiscal del periodo histórico durante el plazo legal aplicable." },
  ],
});
