import { createBatch1PracticalGuideV1 } from "./create-batch-1-practical-guide.v1";

export const MODEL_206_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "206",
  category: "IRNR · Establecimientos permanentes",
  statusLabel: "Documento auxiliar del Modelo 200",
  statusTone: "auxiliary",
  effectiveYear: 2026,
  taxPeriodYear: 2025,
  filingYear: 2026,
  intro: [
    "El Modelo 206 es el documento de ingreso o devolución asociado al Modelo 200 de determinados contribuyentes del Impuesto sobre la Renta de no Residentes.",
    "No es una declaración anual independiente: se genera dentro de Sociedades WEB para establecimientos permanentes y determinadas entidades extranjeras en atribución con presencia en España.",
  ],
  notices: [{ title: "No se presenta de forma aislada", paragraphs: ["El cálculo, la corrección y el plazo proceden del Modelo 200. No debe ofrecerse un botón de presentación independiente del 206."] }],
  type: "Documento auxiliar de ingreso o devolución.",
  presenter: "Determinado establecimiento permanente o entidad extranjera en atribución con presencia en España a través del flujo del Modelo 200.",
  nonPresenter: "Un no residente que declara rentas sin establecimiento permanente mediante el Modelo 210.",
  periodicity: "Anual, unido a la declaración del Modelo 200.",
  deadline: "El mismo plazo aplicable al Modelo 200 del periodo y cierre de la entidad.",
  channel: "Se genera en Sociedades WEB junto al Modelo 200; no se cumplimenta ni presenta solo.",
  result: "A ingresar, devolver o el resultado asociado a la declaración anual.",
  included: ["Identificación del contribuyente IRNR afectado.", "Resultado a ingresar o devolver del Modelo 200.", "Cuenta bancaria, NRC, domiciliación o reconocimiento de deuda cuando proceda.", "Justificante generado dentro de Sociedades WEB."],
  excluded: ["Una declaración anual independiente.", "Rentas de no residentes sin establecimiento permanente del Modelo 210.", "Retenciones por pagos a no residentes del Modelo 216.", "Pagos fraccionados del Modelo 202."],
  preparation: ["Completar primero la declaración del Modelo 200.", "Confirmar condición de establecimiento permanente o entidad afectada.", "Elegir el medio de pago o devolución dentro de Sociedades WEB.", "Conservar declaración y documento 206 conjuntamente."],
  correction: "Corrige el Modelo 200 por el procedimiento aplicable; no edites o presentes aisladamente un nuevo 206 para alterar el resultado.",
  procedureSourceId: "aeat.models-200-206.procedure-home.2026-07-01",
  recordSourceId: "aeat.models-200-206.procedure-record.2026-07-01",
  helpSourceId: "aeat.corporate-tax-2025.manual.2026-07-02",
  document: { label: "Consultar documento oficial Modelo 206", sourceId: "aeat.model-206.form-pdf.2026-06-22" },
  legalSourceIds: ["boe.models-200-206.order-hac-529-2026"],
  related: [
    { code: "200", href: "/consultor-fiscal/modelos/200", description: "Declaración anual que genera el documento 206." },
    { code: "202", href: "/consultor-fiscal/modelos/202", description: "Pagos fraccionados de Sociedades y determinados establecimientos permanentes." },
    { code: "210", href: "/consultor-fiscal/modelos/210", description: "Rentas de no residentes sin establecimiento permanente." },
  ],
  allowProcedureAction: false,
  externalActionNotice: "El Modelo 206 no tiene presentación independiente: se genera dentro del Modelo 200. Factu no firma, paga ni solicita devoluciones.",
  faq: [
    { question: "¿Se presenta separado del Modelo 200?", answer: "No. Se genera y tramita como documento asociado." },
    { question: "¿Quién lo utiliza?", answer: "Determinados establecimientos permanentes y entidades extranjeras en atribución con presencia en España." },
    { question: "¿Es para cualquier no residente?", answer: "No. Las rentas sin establecimiento permanente suelen utilizar el Modelo 210." },
    { question: "¿Cómo se genera?", answer: "Dentro de Sociedades WEB al preparar el Modelo 200." },
    { question: "¿Puede salir a devolver?", answer: "Sí, si el resultado asociado al Modelo 200 es a devolver." },
    { question: "¿Qué plazo tiene?", answer: "El mismo que la declaración anual del Modelo 200 aplicable." },
    { question: "¿Cómo se corrige?", answer: "Corrigiendo el Modelo 200, no el documento de forma aislada." },
    { question: "¿Qué diferencia hay con el 210?", answer: "El 206 acompaña al 200 de establecimientos permanentes; el 210 declara rentas sin establecimiento permanente." },
  ],
});

export const MODEL_213_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "213",
  category: "IRNR · Bienes inmuebles",
  statusLabel: "Autoliquidación anual",
  statusTone: "current",
  effectiveYear: 2026,
  intro: [
    "El Modelo 213 autoliquida el gravamen especial sobre inmuebles o derechos reales de goce en España de determinadas entidades residentes en jurisdicciones no cooperativas.",
    "No lo presenta una persona física no residente. El tipo general es del 3 %, se devenga el 31 de diciembre y se presenta en enero del año siguiente.",
  ],
  notices: [{ title: "Solo determinadas entidades", paragraphs: ["Deben comprobarse residencia, jurisdicción, inmueble y posibles exenciones. La denominación correcta es jurisdicción no cooperativa."] }],
  type: "Autoliquidación anual del gravamen especial sobre inmuebles.",
  presenter: "Entidad residente en jurisdicción no cooperativa que posee o disfruta inmuebles en España y no queda exenta.",
  nonPresenter: "Una persona física no residente o una entidad que no encaja en el supuesto o cumple una exención.",
  periodicity: "Anual, con devengo el 31 de diciembre.",
  deadline: "Durante enero del año siguiente; la domiciliación tiene su propio límite dentro de la campaña.",
  channel: "Presentación electrónica o predeclaración cuando esté admitida por el procedimiento vigente.",
  result: "Ingreso del 3 % sobre la base aplicable, salvo exención.",
  included: ["Entidad, jurisdicción e identificación del inmueble.", "Propiedad o derecho real de goce o disfrute.", "Valor catastral o valor alternativo cuando no exista.", "Tipo del 3 %, exenciones y representante.", "Agrupación de inmuebles según el ámbito territorial de la Delegación."],
  excluded: ["Una declaración de persona física.", "Rentas ordinarias del inmueble declaradas en el Modelo 210.", "Inmuebles de entidades fuera del supuesto legal.", "Exenciones sin documentación que las acredite."],
  preparation: ["Comprobar residencia y jurisdicción.", "Relacionar inmuebles por Delegación competente.", "Obtener valor catastral o base alternativa.", "Documentar cualquier exención y representante."],
  correction: "Presenta complementaria si falta cuota o solicita rectificación si se ingresó de más. Identifica la Delegación y el inmueble correctos.",
  procedureSourceId: "aeat.model-213.procedure-home.2026-07-02",
  recordSourceId: "aeat.model-213.procedure-record.2026-06-23",
  helpSourceId: "aeat.model-213.instructions.2026-07-01",
  legalSourceIds: ["boe.models-210-211-213.order-eha-3316-2010", "boe.models-210-213.order-hac-623-2026"],
  related: [
    { code: "210", href: "/consultor-fiscal/modelos/210", description: "Declaración de rentas de no residentes sin establecimiento permanente." },
    { code: "200", href: "/consultor-fiscal/modelos/200", description: "Impuesto sobre Sociedades o declaración de establecimientos permanentes cuando corresponda." },
  ],
  faq: [
    { question: "¿Lo presenta una persona física?", answer: "No. El gravamen se dirige a determinadas entidades." },
    { question: "¿Qué entidades están afectadas?", answer: "Las residentes en jurisdicciones no cooperativas con inmuebles o derechos en España, salvo exención." },
    { question: "¿Qué tipo se aplica?", answer: "El 3 % sobre la base correspondiente." },
    { question: "¿Qué valor se utiliza?", answer: "El valor catastral o la alternativa prevista si no existe." },
    { question: "¿Se presenta uno por inmueble?", answer: "Pueden agruparse los situados en el ámbito de una misma Delegación según las instrucciones." },
    { question: "¿Qué ocurre si existen inmuebles en varias provincias?", answer: "Debe respetarse el ámbito territorial de cada Delegación y presentar las declaraciones necesarias." },
    { question: "¿Qué exenciones existen?", answer: "Las previstas para ciertos Estados, organismos, actividad económica continuada, cotizadas y demás supuestos legales; requieren comprobación." },
    { question: "¿Cuándo se presenta?", answer: "Durante enero siguiente al devengo del 31 de diciembre." },
  ],
});

export const MODEL_217_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "217",
  category: "SOCIMI · Gravamen especial",
  statusLabel: "19 % · Plazo de dos meses",
  statusTone: "current",
  effectiveYear: 2026,
  intro: [
    "El Modelo 217 autoliquida el gravamen especial del 19 % sobre determinados dividendos o participaciones en beneficios distribuidos por una SOCIMI.",
    "Se devenga el día del acuerdo de distribución y se presenta dentro de los dos meses siguientes. No es la retención ordinaria del socio ni sustituye el Modelo 123.",
  ],
  notices: [{ title: "Regla exacta de devengo y plazo", paragraphs: ["El plazo se cuenta desde el acuerdo de distribución, no desde el pago material del dividendo. Conserva el acuerdo y la identificación fiscal de los socios afectados."] }],
  type: "Autoliquidación del gravamen especial SOCIMI.",
  presenter: "SOCIMI a la que resulta aplicable el gravamen especial por los dividendos distribuidos.",
  nonPresenter: "Cualquier sociedad inmobiliaria o el socio que recibe un dividendo ordinario.",
  periodicity: "No periódica: por cada acuerdo de distribución sujeto.",
  deadline: "Dentro de los dos meses siguientes al día del acuerdo de distribución.",
  channel: "Presentación electrónica del Modelo 217 y pago de la cuota.",
  result: "Ingreso del 19 % sobre los dividendos o participaciones afectados.",
  included: ["Acuerdo y fecha de distribución.", "Dividendos o participaciones en beneficios sujetos.", "Socios con participación igual o superior al 5 % cuando concurren las condiciones del régimen.", "Importe íntegro, tributación del socio, excepciones y cuota del 19 %.", "Tributación estatal o foral y documentación por perceptor."],
  excluded: ["Retención ordinaria sobre dividendos del Modelo 123.", "Resumen anual de dividendos del Modelo 193.", "Cualquier sociedad inmobiliaria no acogida al régimen SOCIMI.", "Gravamen del 15 % sobre beneficios no distribuidos, que usa el Modelo 237."],
  preparation: ["Conservar el acuerdo y su fecha.", "Identificar socios y porcentajes.", "Verificar tributación o exención de cada perceptor.", "Separar gravamen especial, retención ordinaria y gravamen del Modelo 237."],
  correction: "Presenta complementaria si falta cuota o solicita rectificación si se ingresó de más, manteniendo trazabilidad con el acuerdo y los perceptores.",
  procedureSourceId: "aeat.model-217.procedure-home.2026-07-01",
  recordSourceId: "aeat.model-217.procedure-record.2026-06-10",
  helpSourceId: "aeat.model-217.instructions.2026-06-10",
  legalSourceIds: ["boe.socimi.law-11-2009", "boe.model-217.order-hfp-1922-2016"],
  related: [
    { code: "123", href: "/consultor-fiscal/modelos/123", description: "Retenciones e ingresos a cuenta ordinarios sobre dividendos y otras rentas." },
    { code: "193", href: "/consultor-fiscal/modelos/193", description: "Resumen anual de determinados dividendos, intereses y retenciones." },
    { code: "237", href: "/consultor-fiscal/modelos/237", description: "Gravamen especial del 15 % sobre beneficios no distribuidos en los supuestos previstos." },
  ],
  faq: [
    { question: "¿Lo presenta cualquier sociedad inmobiliaria?", answer: "No. Solo una SOCIMI en los supuestos específicos de su régimen." },
    { question: "¿Es una retención al socio?", answer: "No. Es un gravamen especial de la SOCIMI, distinto de la retención ordinaria." },
    { question: "¿Cuál es el tipo?", answer: "El 19 %." },
    { question: "¿Cuándo se devenga?", answer: "El día del acuerdo de distribución de beneficios." },
    { question: "¿Cuál es el plazo?", answer: "Los dos meses siguientes al acuerdo." },
    { question: "¿Qué socios generan el gravamen?", answer: "Los que cumplen los porcentajes y condiciones de tributación definidos en el régimen; debe revisarse cada perceptor." },
    { question: "¿Qué diferencia hay con el 237?", answer: "El 217 grava determinados dividendos distribuidos al 19 %; el 237 atiende el gravamen del 15 % sobre beneficios no distribuidos." },
    { question: "¿Cómo se corrige?", answer: "Con complementaria o rectificación del periodo vinculado al acuerdo." },
  ],
});

export const MODEL_220_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "220",
  category: "Impuesto sobre Sociedades · Consolidación fiscal",
  statusLabel: "Declaración anual del grupo",
  statusTone: "current",
  effectiveYear: 2026,
  taxPeriodYear: 2025,
  filingYear: 2026,
  intro: [
    "El Modelo 220 es la declaración anual del Impuesto sobre Sociedades de los grupos acogidos al régimen de consolidación fiscal.",
    "Lo presenta la entidad representante del grupo fiscal; un grupo mercantil no queda automáticamente acogido y cada entidad integrante conserva las obligaciones individuales previstas.",
  ],
  notices: [{ title: "Grupo mercantil y grupo fiscal no son idénticos", paragraphs: ["Deben existir opción, número de grupo, participación y control suficientes. El grupo de IVA del Modelo 039 es también un régimen diferente."] }],
  type: "Autoliquidación anual consolidada del Impuesto sobre Sociedades.",
  presenter: "Entidad representante o dominante del grupo fiscal acogido válidamente al régimen.",
  nonPresenter: "Cualquier grupo mercantil sin opción fiscal o cada dependiente como si presentara otro 220 separado.",
  periodicity: "Anual, por el periodo impositivo del grupo.",
  deadline: "Se calcula desde el cierre del ejercicio conforme a la regla anual del Impuesto sobre Sociedades.",
  channel: "Presentación electrónica mediante Sociedades WEB.",
  result: "A ingresar, devolver o cero para el grupo fiscal.",
  included: ["Dominante, representante, dependientes y número de grupo.", "Bases individuales, suma, eliminaciones e incorporaciones.", "Bases negativas, reservas, deducciones, retenciones y pagos del Modelo 222.", "Entradas, salidas, operaciones internas y estados contables del grupo.", "Formularios individuales y conciliación con los Modelos 200."],
  excluded: ["La consolidación contable sin opción fiscal.", "Sustituir todas las obligaciones individuales de los miembros.", "Pagos fraccionados, que utilizan el Modelo 222.", "El grupo de entidades de IVA del Modelo 039."],
  preparation: ["Confirmar opción, composición y número de grupo.", "Cerrar formularios individuales de las entidades.", "Conciliar eliminaciones e incorporaciones.", "Cuadrar bases, deducciones, retenciones y pagos 222.", "Documentar entradas, salidas y cambios del ejercicio."],
  correction: "La corrección del grupo debe coordinarse con los Modelos 200 individuales afectados. No se cambia una eliminación o base consolidada sin revisar su contrapartida.",
  procedureSourceId: "aeat.model-220.procedure-home.2026-07-01",
  recordSourceId: "aeat.model-220.procedure-record.2026-06-23",
  helpSourceId: "aeat.model-220.help.2026-06-30",
  document: { label: "Descargar instrucciones oficiales del Modelo 220", sourceId: "aeat.model-220.instructions-pdf.2026-06-23" },
  legalSourceIds: ["boe.corporate-tax.law-27-2014", "boe.models-200-220.order-hac-529-2026"],
  related: [
    { code: "200", href: "/consultor-fiscal/modelos/200", description: "Declaración individual de las entidades y base del proceso consolidado." },
    { code: "222", href: "/consultor-fiscal/modelos/222", description: "Pagos fraccionados del grupo fiscal." },
    { code: "036", href: "/consultor-fiscal/modelos/036", description: "Comunicaciones censales y opción por regímenes cuando corresponda." },
    { code: "039", href: "/consultor-fiscal/modelos/039", description: "Grupo de entidades de IVA, distinto de la consolidación fiscal de Sociedades." },
  ],
  faq: [
    { question: "¿Lo presenta cualquier grupo de empresas?", answer: "No. Solo un grupo acogido válidamente al régimen de consolidación fiscal." },
    { question: "¿Quién firma la declaración?", answer: "La entidad representante del grupo fiscal." },
    { question: "¿Cada sociedad presenta también el Modelo 200?", answer: "Mantiene los formularios y obligaciones individuales que exige el régimen; deben coordinarse con el 220." },
    { question: "¿Qué son eliminaciones e incorporaciones?", answer: "Ajustes para neutralizar operaciones internas y reincorporarlas cuando corresponde según la normativa." },
    { question: "¿Qué modelo se usa para pagos fraccionados?", answer: "El Modelo 222." },
    { question: "¿Cuál es el plazo?", answer: "El anual de Sociedades calculado desde el cierre del ejercicio." },
    { question: "¿Puede salir a devolver?", answer: "Sí, además de ingresar o resultar cero." },
    { question: "¿Cómo se corrige una declaración del grupo?", answer: "Mediante el cauce oficial del 220 y revisando las declaraciones individuales afectadas." },
  ],
});
