import type { FiscalModelPracticalGuideV1 } from "./fiscal-model-practical-guide.types";

export const MODEL_196_GUIDE_V1 = {
  code: "196",
  editorialCategory: "Retenciones e información financiera especializada",
  effectiveYear: 2026,
  monthlyFromYear: 2026,
  firstMonthlyFiling: "2026-02",
  lastAnnualOnlyYear: 2025,
  lastVerifiedAt: "2026-07-15",
  requiresAnnualReview: true,
  intro: [
    "El Modelo 196 es la declaración informativa de cuentas en toda clase de instituciones financieras. Desde la información de enero de 2026 tiene periodicidad mensual y se presenta durante el mes natural siguiente mediante servicio web.",
    "Lo presentan las entidades de crédito y demás entidades expresamente obligadas. El titular, autorizado, beneficiario o representante aparece como declarado, pero no presenta el 196 por tener una cuenta.",
  ],
  notices: [
    { title: "Cambio estructural desde enero de 2026", paragraphs: ["La primera declaración mensual correspondió a enero de 2026 y se presentó en febrero. El régimen anual anterior queda como referencia de ejercicios hasta 2025; no debe aplicarse al nuevo flujo mensual."] },
    { title: "Cada periodo es autónomo", paragraphs: ["Corregir un registro de un mes no corrige automáticamente el mismo dato en otros meses. Deben revisarse todos los periodos afectados."] },
  ],
  actions: [
    { label: "Abrir gestiones oficiales del Modelo 196", sourceId: "aeat.model-196.procedure-home.2026-07-08", primary: true },
    { label: "Consultar preguntas frecuentes oficiales", sourceId: "aeat.model-196.faq.2026-07-08", primary: true },
    { label: "Consultar los plazos oficiales", href: "https://sede.agenciatributaria.gob.es/Sede/todas-gestiones/impuestos-tasas/declaraciones-informativas/modelo-196-decla_____uentas-toda-clase-financieras_/plazos-presentacion.html" },
  ],
  quickSummaryTitle: "El Modelo 196 en pocas palabras",
  quickFacts: [
    { label: "Qué es", value: "Una declaración informativa mensual de cuentas y personas relacionadas desde 2026." },
    { label: "Quién lo presenta", value: "Entidades de crédito, pago, dinero electrónico y demás entidades obligadas; no el titular ordinario." },
    { label: "Primer periodo mensual", value: "Enero de 2026, presentado en febrero de 2026." },
    { label: "Canal", value: "Servicio web; la AEAT ofrece cliente para envíos de menos de 10.000 registros." },
    { label: "Enero a noviembre", value: "Todas las cuentas mantenidas y las personas relacionadas, aunque no exista remuneración." },
    { label: "Diciembre", value: "Añade saldos, cargos, abonos, rendimientos, retenciones y otros datos anuales." },
  ],
  sections: [
    { id: "model-196-obliged", title: "Quién está obligado y quién solo figura informado", cards: [
      { title: "Entidades declarantes", bullets: ["Entidades de crédito y otras dedicadas al tráfico bancario o crediticio.", "Entidades de pago y de dinero electrónico.", "Sucursales españolas y determinadas entidades que operan en libre prestación de servicios, dentro del ámbito oficial."] },
      { title: "Personas declaradas", paragraphs: ["Titulares, titulares reales, representantes, autorizados, beneficiarios y otras personas con poderes de disposición pueden figurar en los registros. Esa inclusión no les convierte en declarantes."] },
    ] },
    { id: "model-196-monthly-content", title: "Qué se informa cada mes", cards: [
      { title: "Todas las cuentas", paragraphs: ["Cuentas bancarias y no bancarias, corrientes, de ahorro, imposiciones a plazo, crédito, pago y otras, aunque no generen remuneración ni retención."] },
      { title: "Enero a noviembre", paragraphs: ["Identificación completa de las cuentas y de las personas relacionadas. Se incluyen abiertas anteriormente, abiertas en el mes, mantenidas y canceladas durante el periodo."] },
      { title: "Declaración de diciembre", paragraphs: ["Además de lo mensual, incorpora saldos a 31 de diciembre, saldo medio del último trimestre, cargos y abonos anuales, rendimientos, retenciones, dirección de comunicaciones y, en su caso, presunción de abandono."] },
    ] },
    { id: "model-196-corrections", title: "Altas, modificaciones y bajas", cards: [
      { title: "A0 · alta", paragraphs: ["Es el tipo ordinario para comunicar un registro nuevo del periodo."] },
      { title: "A1 · modificación", paragraphs: ["Sustituye completamente el registro anterior; deben enviarse todos sus campos, no solo el dato corregido."] },
      { title: "A2 · baja", paragraphs: ["Anula el registro identificado conforme al esquema oficial. Se utiliza para corregir registros ya declarados, no para omitir silenciosamente información."] },
    ], note: "Si un error aparece en varios meses, hay que corregir cada declaración afectada. Los periodos son independientes." },
    { id: "model-196-relations", title: "Relación con otros modelos", cards: [
      { title: "Modelo 126", paragraphs: ["Ingresa periódicamente determinadas retenciones sobre rendimientos de cuentas."], links: [{ label: "Ver Modelo 126", href: "/consultor-fiscal/modelos/126" }] },
      { title: "Modelo 198", paragraphs: ["Informa de otras operaciones con activos financieros y valores mobiliarios."], links: [{ label: "Ver Modelo 198", href: "/consultor-fiscal/modelos/198" }] },
      { title: "Modelo 189", paragraphs: ["Recoge determinada información anual sobre valores, seguros y rentas."], links: [{ label: "Ver Modelo 189", href: "/consultor-fiscal/modelos/189" }] },
    ] },
  ],
  fillingTitle: "Cómo preparar el Modelo 196 mensual",
  fillingSteps: [
    { title: "1. Cierra el inventario del mes", paragraphs: ["Incluye todas las cuentas mantenidas y las altas, bajas o cancelaciones del periodo."] },
    { title: "2. Valida personas y roles", paragraphs: ["Comprueba titulares, titulares reales, representantes, autorizados y beneficiarios sin inferir identidades."] },
    { title: "3. Genera identificadores estables", paragraphs: ["Mantén el identificador del registro de detalle necesario para trazabilidad y correcciones."] },
    { title: "4. Selecciona A0, A1 o A2", paragraphs: ["Utiliza el tipo de comunicación según sea alta, sustitución completa o baja de un registro previamente declarado."] },
    { title: "5. Envía y concilia la respuesta", paragraphs: ["Distingue registros aceptados, aceptados parcialmente o rechazados y conserva la evidencia oficial."] },
    { title: "6. Completa diciembre", paragraphs: ["Añade los datos de cierre anual exigidos sin omitir la información mensual ordinaria."] },
  ],
  afterTitle: "Qué ocurre después",
  afterSteps: [
    { title: "Respuesta por registro", description: "Revisa aceptación total, parcial o rechazo y actúa solo sobre los registros afectados." },
    { title: "Corrección por periodos", description: "Repite A1 o A2 en cada mes donde exista el error." },
    { title: "Conciliación financiera", description: "Contrasta cuentas, rendimientos, retenciones y Modelos 126 sin mezclar sus finalidades." },
  ],
  comparison: {
    title: "Modelo 196 y Modelo 126",
    current: { title: "Modelo 196", description: "Información mensual detallada de cuentas y personas relacionadas desde 2026." },
    related: { title: "Modelo 126", description: "Autoliquidación periódica de determinadas retenciones sobre rendimientos de cuentas.", href: "/consultor-fiscal/modelos/126", label: "Ver Modelo 126" },
    additional: [
      { title: "Modelo 198", description: "Otras operaciones con activos financieros y valores mobiliarios.", href: "/consultor-fiscal/modelos/198", label: "Ver Modelo 198" },
      { title: "Modelo 189", description: "Determinada información anual sobre valores, seguros y rentas.", href: "/consultor-fiscal/modelos/189", label: "Ver Modelo 189" },
    ],
    conclusion: "El 196 informa cuentas cada mes; el 126 ingresa retenciones cuando existen rendimientos sometidos a ellas.",
  },
  pdfNotice: ["El diseño de 2023 y la ayuda TGVI de 2025 son documentación histórica. Para 2026 deben utilizarse los esquemas, WSDL, descripción y validaciones del servicio web vigente."],
  documents: [
    { label: "Descripción del servicio web · versión 1.3", sourceId: "aeat.model-196.web-service-description-pdf.v1-3.2026-05-28" },
    { label: "Validaciones y errores · versión 1.0", sourceId: "aeat.model-196.validations-pdf.v1-0.2026-05-27" },
  ],
  officialLinks: [
    { label: "Esquemas del servicio web", sourceId: "aeat.model-196.schemas.2026-05-28" },
    { label: "WSDL del servicio web", sourceId: "aeat.model-196.wsdl.2026-05-28" },
    { label: "Ficha del procedimiento", sourceId: "aeat.model-196.procedure-record.2026-05-27" },
  ],
  legalLinks: [{ label: "Orden HAC/747/2025", sourceId: "boe.model-196.order-hac-747-2025" }],
  faq: [
    { question: "¿Quién presenta el Modelo 196?", answer: "Las entidades financieras y demás entidades expresamente obligadas por la normativa, no los titulares ordinarios de las cuentas." },
    { question: "¿Desde cuándo es mensual?", answer: "Desde la información de enero de 2026; la primera presentación mensual se realizó en febrero de 2026." },
    { question: "¿Cuándo se presenta?", answer: "Durante el mes natural siguiente al periodo al que se refiere la información." },
    { question: "¿Qué cuentas se incluyen?", answer: "Todo tipo de cuentas bancarias y no bancarias, aunque no generen remuneración, retención o ingreso a cuenta." },
    { question: "¿Se informan todas las cuentas cada mes?", answer: "Sí. Se incluyen cuentas abiertas antes, abiertas en el periodo, mantenidas y canceladas durante ese mes." },
    { question: "¿Qué añade diciembre?", answer: "Saldos, saldo medio, cargos, abonos, rendimientos, retenciones y otros datos anuales, además de la información mensual." },
    { question: "¿Qué significa A0?", answer: "El alta ordinaria de un registro del periodo." },
    { question: "¿Qué significa A1?", answer: "Una modificación que sustituye por completo el registro anterior y debe incluir todos sus campos." },
    { question: "¿Qué significa A2?", answer: "La baja de un registro previamente declarado, identificada conforme al esquema oficial." },
    { question: "¿Corregir enero corrige febrero?", answer: "No. Cada periodo es autónomo y deben corregirse todos los meses afectados." },
    { question: "¿Cómo se presenta?", answer: "Mediante servicio web; la AEAT ofrece un cliente para pequeños declarantes con menos de 10.000 registros por envío." },
    { question: "¿Qué diferencia hay con el Modelo 126?", answer: "El 196 informa cuentas y personas; el 126 ingresa determinadas retenciones sobre rendimientos de esas cuentas." },
    { question: "¿El titular de la cuenta presenta el 196?", answer: "No por ser titular. Puede figurar como declarado, pero la obligación de presentación recae en la entidad." },
    { question: "¿Se puede reutilizar el fichero anual de 2025?", answer: "No como regla. El sistema de 2026 es mensual y utiliza el servicio web y sus esquemas vigentes." },
    { question: "¿Factu conecta con el servicio web?", answer: "No. Esta ficha es informativa y no transmite datos financieros ni credenciales." },
  ],
  sourceIds: [
    "aeat.model-196.procedure-home.2026-07-08",
    "aeat.model-196.procedure-record.2026-05-27",
    "aeat.model-196.faq.2026-07-08",
    "aeat.model-196.schemas.2026-05-28",
    "aeat.model-196.wsdl.2026-05-28",
    "aeat.model-196.web-service-description-pdf.v1-3.2026-05-28",
    "aeat.model-196.validations-pdf.v1-0.2026-05-27",
    "boe.model-196.order-hac-747-2025",
  ],
} as const satisfies FiscalModelPracticalGuideV1;
