import { createBatch1PracticalGuideV1 } from "./create-batch-1-practical-guide.v1";

export const MODEL_181_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "181",
  category: "Financiación inmobiliaria · Información",
  statusLabel: "Declaración anual",
  statusTone: "current",
  effectiveYear: 2026,
  intro: ["El Modelo 181 informa anualmente de préstamos, créditos y operaciones financieras relacionadas con bienes inmuebles.", "Lo presentan las entidades obligadas, no el prestatario; la información no concede por sí sola una deducción ni es una solicitud de préstamo."],
  notices: [{ title: "Campos versionados por ejercicio", paragraphs: ["El diseño se ha actualizado recientemente. Referencia catastral, destino, saldos, intereses y demás campos deben validarse contra el diseño del ejercicio informado."] }],
  type: "Declaración informativa anual de financiación inmobiliaria.",
  presenter: "Entidades financieras y demás prestamistas obligados por la normativa.",
  nonPresenter: "La persona que paga la hipoteca o solicita el préstamo.",
  periodicity: "Anual respecto de préstamos y operaciones del ejercicio.",
  deadline: "Durante enero del año siguiente, conforme al calendario vigente.",
  channel: "Presentación electrónica mediante fichero y diseño de registro.",
  result: "Informativo: no concede deducción ni genera un pago.",
  included: ["Préstamos, créditos e hipotecas incluidos.", "Titulares, inmueble y referencia catastral.", "Capital inicial, saldo, intereses, amortización y cantidades satisfechas.", "Destino de la financiación y movimientos previstos."],
  excluded: ["Una solicitud de financiación.", "El cálculo automático de la deducción por vivienda.", "La declaración de Renta o Sociedades.", "Operaciones no vinculadas a los supuestos del diseño."],
  preparation: ["Conciliar contrato, titulares e inmueble.", "Validar referencia catastral y destino.", "Cuadrar saldo inicial, amortización, intereses y saldo final.", "Aplicar el diseño del ejercicio y corregir duplicados."],
  correction: "La entidad informante rectifica el registro. El prestatario debe pedirle la corrección y conservar contrato y extractos para contrastar sus datos fiscales.",
  procedureSourceId: "aeat.model-181.procedure-home.2026-07-08",
  recordSourceId: "aeat.model-181.procedure-record.2026-07-08",
  helpSourceId: "aeat.model-181.file-help.2026-02-05",
  document: { label: "Descargar diseño de registro del Modelo 181", sourceId: "aeat.model-181.register-design.pdf" },
  legalSourceIds: ["boe.model-181.order-eha-3514-2009", "boe.model-181.order-hac-747-2025"],
  related: [
    { code: "100", href: "/consultor-fiscal/modelos/100", description: "Declaración anual del prestatario cuando es persona física." },
    { code: "200", href: "/consultor-fiscal/modelos/200", description: "Declaración anual de Sociedades." },
    { code: "347", href: "/consultor-fiscal/modelos/347", description: "Información de operaciones con terceros bajo reglas diferentes." },
  ],
  faq: [
    { question: "¿Lo presenta quien paga una hipoteca?", answer: "No. Lo presenta la entidad obligada que concedió o gestiona la financiación." },
    { question: "¿Qué entidad lo presenta?", answer: "La entidad financiera u otro prestamista obligado por la norma." },
    { question: "¿Qué datos del inmueble incluye?", answer: "Dirección, referencia catastral, destino y los demás campos del diseño vigente." },
    { question: "¿Concede una deducción?", answer: "No. Solo suministra información; la deducción exige sus propios requisitos." },
    { question: "¿Incluye préstamos no hipotecarios?", answer: "Incluye los préstamos y créditos que encajen en las operaciones inmobiliarias definidas por el modelo." },
    { question: "¿Cuándo se presenta?", answer: "Anualmente, durante enero según el calendario vigente." },
    { question: "¿Qué hago si el saldo es incorrecto?", answer: "Solicita la corrección a la entidad informante." },
    { question: "¿Genera un pago?", answer: "No. Es informativo." },
  ],
});

export const MODEL_182_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "182",
  category: "Donativos y aportaciones · Información",
  statusLabel: "Declaración anual",
  statusTone: "current",
  effectiveYear: 2026,
  intro: ["El Modelo 182 declara anualmente los donativos, donaciones y aportaciones recibidos por las entidades beneficiarias obligadas.", "Lo presenta la entidad receptora, no el donante; el certificado debe coincidir con la declaración y ninguno garantiza por sí solo la deducción."],
  notices: [{ title: "Certificado y declaración deben coincidir", paragraphs: ["Importe, naturaleza, fecha, identidad, recurrencia, revocaciones y devoluciones deben ser coherentes. Los porcentajes de deducción se revisan por ejercicio."] }],
  type: "Declaración informativa anual de donativos.",
  presenter: "Entidad beneficiaria que recibe aportaciones y está obligada a certificarlas e informarlas.",
  nonPresenter: "El donante, aunque sea quien aplica una posible deducción.",
  periodicity: "Anual respecto de las aportaciones recibidas en el ejercicio.",
  deadline: "Durante enero, conforme al calendario anual y al canal aplicable por volumen.",
  channel: "Formulario web dentro del límite vigente o presentación mediante fichero.",
  result: "Informativo: no concede automáticamente la deducción.",
  included: ["Donante, NIF, fecha e importe.", "Donativos dinerarios y en especie con su valoración.", "Recurrencia y régimen fiscal aplicable.", "Revocaciones, devoluciones y certificados rectificados."],
  excluded: ["Aportaciones a entidades sin derecho a certificación bajo este modelo.", "El cálculo final de la deducción del donante.", "La declaración de Renta o Sociedades del donante.", "Una valoración sin soporte de bienes donados."],
  preparation: ["Conciliar cobros, bienes recibidos y libro de donantes.", "Validar NIF y régimen de la entidad.", "Emitir certificados coherentes.", "Registrar revocaciones y devoluciones en el ejercicio correcto."],
  correction: "La entidad debe corregir el Modelo 182 y, si afecta al donante, emitir un certificado rectificado. No basta con cambiar solo uno de los dos documentos.",
  procedureSourceId: "aeat.model-182.procedure-home.2026-07-08",
  recordSourceId: "aeat.model-182.procedure-record.2026-07-08",
  helpSourceId: "aeat.model-182.browser-form-help.2026-06-19",
  document: { label: "Descargar diseño de registro del Modelo 182", sourceId: "aeat.model-182.register-design.pdf" },
  legalSourceIds: ["boe.model-182.order-eha-3021-2007", "boe.models-182-184.order-hac-1430-2025"],
  related: [
    { code: "100", href: "/consultor-fiscal/modelos/100", description: "Declaración del donante persona física." },
    { code: "200", href: "/consultor-fiscal/modelos/200", description: "Declaración de Sociedades de entidad o donante cuando corresponda." },
  ],
  faq: [
    { question: "¿Lo presenta el donante?", answer: "No. Lo presenta la entidad beneficiaria." },
    { question: "¿Quién debe emitir el certificado?", answer: "La entidad que recibe el donativo y cumple los requisitos legales." },
    { question: "¿Todo donativo desgrava?", answer: "No. Entidad, aportación y donante deben cumplir los requisitos del ejercicio." },
    { question: "¿Se incluyen donativos en especie?", answer: "Sí cuando estén admitidos y correctamente valorados y documentados." },
    { question: "¿Qué ocurre si se devuelve?", answer: "La devolución o revocación debe comunicarse y puede afectar a la deducción." },
    { question: "¿Qué significa donación recurrente?", answer: "Una aportación que cumple la continuidad exigida por la norma; no se presume por repetirse una vez." },
    { question: "¿Cuándo se presenta?", answer: "Anualmente, durante enero según el calendario oficial." },
    { question: "¿Cómo corrijo el NIF del donante?", answer: "La entidad rectifica el registro y, si procede, el certificado entregado." },
  ],
});

export const MODEL_185_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "185",
  category: "Seguridad Social y mutualidades · Información",
  statusLabel: "Mensual y electrónico desde 2026",
  statusTone: "current",
  effectiveYear: 2026,
  monthlyFromYear: 2026,
  firstMonthlyFiling: "2026-02",
  intro: ["Desde la información de enero de 2026, el Modelo 185 es una declaración mensual y electrónica de los órganos gestores de la Seguridad Social y mutualidades.", "No lo presenta el afiliado ni el autónomo: su función es suministrar afiliación y cotizaciones para los fines previstos, incluida la comprobación de deducciones."],
  notices: [
    { title: "El afiliado nunca es el declarante", paragraphs: ["Los organismos gestores y mutualidades presentan la información. Si hay un error, el interesado debe solicitarles la corrección."] },
    { title: "Procedimiento electrónico vigente desde enero de 2026", paragraphs: ["Las declaraciones de cada mes se presentan dentro de los diez días naturales siguientes al final del mes. Antes de iniciar cualquier envío debe comprobarse que la acción oficial está habilitada para el organismo obligado."] },
  ],
  type: "Declaración informativa mensual electrónica.",
  presenter: "Órganos y entidades gestores de la Seguridad Social y mutualidades obligadas.",
  nonPresenter: "El afiliado, mutualista o trabajador autónomo sobre sus propias cotizaciones.",
  periodicity: "Mensual desde enero de 2026.",
  deadline: "Dentro de los diez días naturales siguientes a la finalización de cada mes.",
  channel: "Presentación electrónica mediante fichero; el organismo debe comprobar la disponibilidad real del trámite.",
  result: "Informativo: no es un recibo ni concede automáticamente una deducción.",
  included: ["Afiliados, mutualistas, régimen y periodo de alta.", "Días, cotizaciones y bases o campos exigidos por el diseño.", "Información mensual desde enero de 2026.", "Correcciones por el organismo informante."],
  excluded: ["Una declaración del afiliado.", "El recibo o pago de la cuota.", "El resumen anual del Modelo 156.", "La solicitud de maternidad del Modelo 140."],
  preparation: ["Conciliar afiliación, mutualidad y periodo.", "Validar días, bases y cotizaciones.", "Separar cada mes y aplicar el diseño vigente.", "Comprobar habilitación, respuesta y registros rechazados."],
  correction: "El organismo o mutualidad corrige la declaración. El afiliado aporta vida laboral, recibos o certificados al organismo, pero no envía un 185 personal.",
  procedureSourceId: "aeat.model-185.procedure-home.2026-07-08",
  recordSourceId: "aeat.model-185.procedure-record.2026-07-08",
  helpSourceId: "aeat.model-185.file-upload-help.2026-06-19",
  document: { label: "Descargar diseño de registro del Modelo 185", sourceId: "aeat.model-185.register-design.pdf" },
  legalSourceIds: ["boe.model-185.order-hac-1197-2025", "boe.model-185.order-hac-96-2003"],
  related: [
    { code: "156", href: "/consultor-fiscal/modelos/156", description: "Resumen anual de cotizaciones para la deducción por maternidad." },
    { code: "140", href: "/consultor-fiscal/modelos/140", description: "Solicitud y variaciones del abono anticipado por maternidad." },
    { code: "100", href: "/consultor-fiscal/modelos/100", description: "Declaración anual del afiliado cuando corresponda." },
  ],
  faq: [
    { question: "¿Lo presenta el autónomo?", answer: "No. Lo presenta el organismo gestor o mutualidad." },
    { question: "¿Quién comunica mis cotizaciones?", answer: "La Seguridad Social, mutualidad u órgano gestor obligado." },
    { question: "¿Es mensual?", answer: "Sí, desde la información de enero de 2026." },
    { question: "¿Desde cuándo es electrónica?", answer: "La nueva presentación electrónica se aplica a enero de 2026, presentado en febrero." },
    { question: "¿Qué diferencia existe con el 156?", answer: "El 185 es mensual; el 156 es el resumen anual para su finalidad específica." },
    { question: "¿Afecta a la deducción por maternidad?", answer: "Puede servir para contrastarla, pero no la concede por sí solo." },
    { question: "¿Cómo se corrige?", answer: "La corrección corresponde al organismo informante." },
    { question: "¿Puedo consultar la declaración?", answer: "El organismo usa los servicios oficiales disponibles; el afiliado consulta sus datos por los canales personales, no como presentador del 185." },
  ],
});

export const MODEL_186_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "186",
  category: "Registro Civil · Información de terceros",
  statusLabel: "Suministro mensual",
  statusTone: "current",
  effectiveYear: 2026,
  intro: ["El Modelo 186 es el suministro mensual de información sobre nacimientos y defunciones que realizan los órganos del Registro Civil.", "No lo presentan los padres, la familia ni un heredero, y no sustituye un certificado registral ni los trámites sucesorios."],
  notices: [{ title: "No existe un formulario personal", paragraphs: ["El ciudadano no descarga ni presenta su propio Modelo 186. Si hay un dato registral erróneo, debe corregirse en el Registro Civil que lo suministra."] }],
  type: "Suministro informativo mensual entre administraciones.",
  presenter: "Órganos del Registro Civil obligados a suministrar la información.",
  nonPresenter: "Padres, familiares, herederos o la persona inscrita.",
  periodicity: "Mensual.",
  deadline: "Conforme al suministro periódico previsto para los órganos registrales.",
  channel: "Canal institucional; no hay un trámite ordinario de presentación para ciudadanos.",
  result: "Informativo: no expide certificados ni resuelve sucesiones.",
  included: ["Identidad, fecha y lugar de nacimiento.", "Identidad, fecha y lugar de defunción.", "Datos registrales previstos por la norma.", "Correcciones efectuadas por el Registro Civil."],
  excluded: ["Certificado de nacimiento o defunción.", "Declaración de herederos o sucesiones.", "Solicitud de deducciones familiares.", "Un trámite personal ante la AEAT."],
  preparation: ["Validar asiento registral e identidad.", "Separar nacimientos y defunciones por periodo.", "Proteger los datos durante el suministro.", "Corregir en origen cualquier fecha o identificación errónea."],
  correction: "Solicita la rectificación al Registro Civil. Una vez corregido el asiento, el órgano responsable debe actualizar el suministro cuando corresponda.",
  procedureSourceId: "aeat.model-186.procedure-home.2025-12-12",
  recordSourceId: "aeat.model-186.procedure-record.2026-07-08",
  legalSourceIds: ["boe.model-186.order-hac-539-2003"],
  related: [
    { code: "100", href: "/consultor-fiscal/modelos/100", description: "Declaración anual que puede reflejar circunstancias familiares." },
    { code: "140", href: "/consultor-fiscal/modelos/140", description: "Abono anticipado por maternidad, con requisitos propios." },
    { code: "143", href: "/consultor-fiscal/modelos/143", description: "Abonos anticipados de determinadas deducciones familiares." },
  ],
  allowProcedureAction: false,
  externalActionNotice: "No hay un formulario ciudadano. Factu no recoge ni consulta datos del Registro Civil.",
  faq: [
    { question: "¿Lo presentan los padres?", answer: "No. Lo presenta el Registro Civil." },
    { question: "¿Lo presenta un heredero?", answer: "No." },
    { question: "¿Es un certificado?", answer: "No. Es un suministro de información entre administraciones." },
    { question: "¿Quién comunica los datos?", answer: "El órgano competente del Registro Civil." },
    { question: "¿Para qué utiliza Hacienda la información?", answer: "Para contrastes censales y tributarios previstos legalmente." },
    { question: "¿Es mensual?", answer: "Sí." },
    { question: "¿Qué hago si la fecha es incorrecta?", answer: "Solicita la corrección del asiento en el Registro Civil." },
    { question: "¿Puedo descargar un Modelo 186 personal?", answer: "No existe un formulario personal equivalente." },
  ],
});

export const MODEL_189_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "189",
  category: "Valores, seguros y rentas · Información",
  statusLabel: "Declaración anual",
  statusTone: "current",
  effectiveYear: 2026,
  intro: ["El Modelo 189 informa anualmente de valores, seguros y rentas, normalmente con la posición o valoración a 31 de diciembre.", "Lo presentan entidades financieras, aseguradoras y otros obligados; no el inversor ni el asegurado."],
  notices: [{ title: "Posiciones, no solo operaciones", paragraphs: ["El 189 se centra en valores y posiciones; el 198 informa operaciones del año. Los campos del ejercicio 2026 incorporan novedades que deben revisarse en el diseño vigente."] }],
  type: "Declaración informativa anual de valores, seguros y rentas.",
  presenter: "Entidades financieras, aseguradoras, depositarias y demás obligados.",
  nonPresenter: "El inversor, partícipe, rentista o asegurado.",
  periodicity: "Anual, con referencia habitual a 31 de diciembre.",
  deadline: "En el plazo anual publicado por la AEAT.",
  channel: "Presentación electrónica mediante fichero.",
  result: "Informativo: no liquida Patrimonio, Renta ni Sociedades.",
  included: ["Acciones, participaciones y valores incluidos.", "Seguros de vida y valor de rescate.", "Rentas temporales y vitalicias.", "Titular, participación y valor a 31 de diciembre."],
  excluded: ["Operaciones anuales del Modelo 198.", "Rendimientos y retenciones del Modelo 188.", "Bienes en el extranjero del Modelo 720.", "Autoliquidación de Patrimonio del Modelo 714."],
  preparation: ["Conciliar titulares y porcentajes.", "Aplicar la valoración exigida a 31 de diciembre.", "Separar valores, seguros y rentas.", "Validar diseño y novedades del ejercicio."],
  correction: "La entidad informante rectifica el valor, titular o clave. El cliente debe pedirle la corrección y contrastarla con sus justificantes.",
  procedureSourceId: "aeat.model-189.procedure-home.2026-07-08",
  recordSourceId: "aeat.model-189.procedure-record.2026-07-08",
  helpSourceId: "aeat.model-189.file-upload-help.2026-03-02",
  document: { label: "Descargar diseño de registro del Modelo 189", sourceId: "aeat.model-189.register-design.pdf" },
  legalSourceIds: ["boe.model-189.order-eha-3481-2008", "boe.model-189.order-hac-132-2026"],
  related: [
    { code: "188", href: "/consultor-fiscal/modelos/188", description: "Rendimientos y retenciones de seguros y capitalización." },
    { code: "198", href: "/consultor-fiscal/modelos/198", description: "Operaciones con activos financieros durante el año." },
    { code: "714", href: "/consultor-fiscal/modelos/714", description: "Autoliquidación personal del Impuesto sobre el Patrimonio." },
    { code: "720", href: "/consultor-fiscal/modelos/720", description: "Información sobre determinados bienes y derechos en el extranjero." },
  ],
  faq: [
    { question: "¿Lo presenta el inversor?", answer: "No. Lo presenta la entidad obligada." },
    { question: "¿Qué diferencia hay con el 198?", answer: "El 189 informa posiciones o valores; el 198, operaciones del ejercicio." },
    { question: "¿Qué diferencia hay con el 188?", answer: "El 188 resume rendimientos y retenciones de seguros; el 189 informa valores y posiciones." },
    { question: "¿Incluye seguros?", answer: "Sí, los seguros y valores de rescate previstos por el diseño." },
    { question: "¿Qué fecha se utiliza?", answer: "Habitualmente el 31 de diciembre, según el campo y el diseño." },
    { question: "¿Genera un pago?", answer: "No." },
    { question: "¿Cuándo se presenta?", answer: "Anualmente en el plazo oficial." },
    { question: "¿Cómo se corrige un valor incorrecto?", answer: "La entidad que informó la posición debe rectificarla." },
  ],
});

export const MODEL_192_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "192",
  category: "Deuda pública · Letras del Tesoro",
  statusLabel: "Declaración anual",
  statusTone: "current",
  effectiveYear: 2026,
  intro: ["El Modelo 192 informa anualmente de determinadas adquisiciones, transmisiones y amortizaciones de Letras del Tesoro.", "Lo presentan intermediarios y entidades obligadas, no el inversor ordinario, y no incluye automáticamente bonos, obligaciones u otros activos."],
  notices: [{ title: "Solo Letras del Tesoro", paragraphs: ["No debe convertirse en un resumen genérico de deuda pública. Para otros activos existen modelos como 194 o 198."] }],
  type: "Declaración informativa anual de operaciones con Letras del Tesoro.",
  presenter: "Intermediarios y entidades obligadas que intervienen en las operaciones.",
  nonPresenter: "El titular inversor por el mero hecho de comprar o vender Letras.",
  periodicity: "Anual.",
  deadline: "En el plazo anual oficial del ejercicio.",
  channel: "Presentación electrónica mediante fichero.",
  result: "Informativo: no genera cuota.",
  included: ["Adquisición, transmisión y amortización de Letras incluidas.", "Titular, NIF, fecha, nominal e importe.", "Rendimiento implícito e intermediario.", "Claves y diseños del ejercicio."],
  excluded: ["Bonos y obligaciones del Estado.", "Otros activos financieros del Modelo 198.", "Rendimientos y retenciones del Modelo 194.", "Posiciones finales del Modelo 189."],
  preparation: ["Identificar cada Letra y operación.", "Conciliar nominal, efectivo y fecha.", "Validar titular e intermediario.", "Aplicar el diseño vigente."],
  correction: "El intermediario rectifica la operación o titular en el fichero. El inversor solicita la subsanación con su justificante de compra, venta o amortización.",
  procedureSourceId: "aeat.model-192.procedure-home.2026-03-01",
  recordSourceId: "aeat.model-192.procedure-record.2026-07-08",
  helpSourceId: "aeat.model-192.file-upload-help.2026-04-22",
  document: { label: "Descargar diseño de registro del Modelo 192", sourceId: "aeat.model-192.register-design-pdf.2026-07-13" },
  legalSourceIds: ["boe.model-192.order-2001-10-04", "boe.models-192-193.order-hac-1504-2024"],
  related: [
    { code: "194", href: "/consultor-fiscal/modelos/194", description: "Rendimientos y retenciones de determinados activos de deuda." },
    { code: "198", href: "/consultor-fiscal/modelos/198", description: "Operaciones con otros activos financieros y valores." },
    { code: "189", href: "/consultor-fiscal/modelos/189", description: "Valores y posiciones a final de año." },
  ],
  faq: [
    { question: "¿Lo presenta el titular de las Letras?", answer: "No. Lo presenta el intermediario obligado." },
    { question: "¿Incluye bonos del Estado?", answer: "No por el mero hecho de ser deuda pública." },
    { question: "¿Incluye obligaciones?", answer: "No; el modelo se limita a Letras del Tesoro y operaciones definidas." },
    { question: "¿Qué operaciones comunica?", answer: "Adquisiciones, transmisiones y amortizaciones incluidas." },
    { question: "¿Genera un pago?", answer: "No." },
    { question: "¿Qué diferencia existe con el 198?", answer: "El 192 es específico de Letras; el 198 abarca otras operaciones financieras." },
    { question: "¿Cuándo se presenta?", answer: "Anualmente." },
    { question: "¿Cómo se corrige?", answer: "La entidad informante rectifica el registro." },
  ],
});

export const MODEL_195_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "195",
  category: "Cuentas bancarias · Identificación",
  statusLabel: "Declaración trimestral",
  statusTone: "current",
  effectiveYear: 2026,
  intro: ["El Modelo 195 informa trimestralmente de cuentas u operaciones cuyos titulares no facilitaron el NIF a la entidad de crédito dentro del plazo establecido.", "Lo presenta la entidad, no el cliente, y no autoriza cuentas anónimas ni sustituye la identificación exigida por otras normas."],
  notices: [{ title: "La falta temporal de NIF debe resolverse", paragraphs: ["El modelo informa la incidencia, pero no permite mantener indefinidamente una cuenta sin identificar. Cuando se obtiene el NIF, la entidad debe actualizar y corregir lo comunicado."] }],
  type: "Declaración informativa trimestral de cuentas sin NIF comunicado en plazo.",
  presenter: "Entidades de crédito obligadas.",
  nonPresenter: "El titular de la cuenta o quien realiza la operación.",
  periodicity: "Trimestral.",
  deadline: "En el plazo trimestral publicado para el periodo.",
  channel: "Presentación electrónica mediante fichero.",
  result: "Informativo: no genera un pago ni legitima el anonimato.",
  included: ["Cuenta u operación afectada.", "Titulares sin NIF en plazo y datos disponibles.", "Fecha de apertura, saldo u operación según el diseño.", "Actualización, corrección o baja cuando se obtiene el NIF."],
  excluded: ["Una autorización para operar anónimamente.", "La información ordinaria de cuentas del Modelo 196.", "La identificación de cheques del Modelo 199.", "Un trámite personal del cliente."],
  preparation: ["Controlar el plazo para obtener el NIF.", "Identificar cuenta, titular y fecha.", "Evitar duplicados entre trimestres.", "Actualizar el registro en cuanto se obtenga la identificación."],
  correction: "La entidad comunica el NIF obtenido y corrige o da de baja el registro según el diseño. El cliente debe facilitar la identificación a la entidad.",
  procedureSourceId: "aeat.model-195.procedure-home.2026-03-01",
  recordSourceId: "aeat.model-195.procedure-record.2026-07-08",
  helpSourceId: "aeat.model-195.file-upload-help.2026-04-22",
  document: { label: "Descargar diseño de registro del Modelo 195", sourceId: "aeat.model-195.register-design-pdf.2025-12-12" },
  legalSourceIds: ["boe.model-195.order-2001-12-21", "boe.model-195.order-hac-1430-2025"],
  related: [{ code: "196", href: "/consultor-fiscal/modelos/196", description: "Información ordinaria de cuentas, titulares, saldos y rendimientos." }],
  faq: [
    { question: "¿Lo presenta el titular?", answer: "No. Lo presenta la entidad de crédito." },
    { question: "¿Por qué una cuenta aparece sin NIF?", answer: "Porque el titular no lo facilitó dentro del plazo exigido o existió una incidencia de identificación." },
    { question: "¿Puede mantenerse sin identificar?", answer: "No como regla permanente; la entidad debe cumplir sus obligaciones de identificación." },
    { question: "¿Es anual?", answer: "No. Es trimestral." },
    { question: "¿Qué ocurre cuando se facilita el NIF?", answer: "La entidad actualiza o corrige la información." },
    { question: "¿Qué diferencia hay con el 196?", answer: "El 195 trata la falta de NIF; el 196 informa ordinariamente de cuentas y rendimientos." },
    { question: "¿Genera un pago?", answer: "No." },
    { question: "¿Cómo se corrige?", answer: "La entidad presenta la corrección o baja conforme al diseño." },
  ],
});

export const MODEL_198_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "198",
  category: "Activos financieros · Operaciones",
  statusLabel: "Declaración anual",
  statusTone: "current",
  effectiveYear: 2026,
  intro: ["El Modelo 198 informa anualmente de operaciones con activos financieros y otros valores mobiliarios.", "Lo presentan intermediarios, emisores y demás entidades obligadas; informa operaciones, no solo posiciones, y excluye supuestos cubiertos por modelos más específicos."],
  notices: [{ title: "Clasifica antes de informar", paragraphs: ["Adquisición, transmisión, amortización, reembolso, canje, conversión, préstamo de valores y otras operaciones tienen claves propias. Letras, IIC y otros activos pueden pertenecer a modelos específicos."] }],
  type: "Declaración informativa anual de operaciones financieras.",
  presenter: "Intermediarios, entidades emisoras, financieras y demás obligados.",
  nonPresenter: "El inversor por el mero hecho de comprar, vender o mantener valores.",
  periodicity: "Anual.",
  deadline: "En el plazo anual oficial, con las reglas de formulario o fichero vigentes.",
  channel: "Formulario dentro del límite publicado o fichero; puede admitir presentación parcial según el procedimiento.",
  result: "Informativo: no calcula la ganancia fiscal del inversor.",
  included: ["Adquisiciones, transmisiones, amortizaciones y reembolsos.", "Canjes, conversiones, préstamos de valores y operaciones incluidas.", "Titular, intermediario, ISIN, fecha, unidades, importe y gastos.", "Clave de operación, presentaciones parciales y corrección consolidada."],
  excluded: ["Operaciones de IIC propias del Modelo 187.", "Letras del Tesoro del Modelo 192.", "Rendimientos de deuda del Modelo 194.", "Posiciones a 31 de diciembre del Modelo 189."],
  preparation: ["Clasificar cada operación y activo.", "Conciliar ISIN, fechas, unidades, efectivo y gastos.", "Excluir operaciones cubiertas por modelos específicos.", "Validar parciales y consolidado para evitar duplicados."],
  correction: "La entidad debe rectificar la operación con la clave y procedimiento del diseño. Si hubo envíos parciales, la corrección debe preservar una visión consolidada sin duplicar registros.",
  procedureSourceId: "aeat.model-198.procedure-home.2026-07-08",
  recordSourceId: "aeat.model-198.procedure-record.2026-07-08",
  helpSourceId: "aeat.model-198.browser-form-help.2026-06-19",
  document: { label: "Descargar diseño de registro del Modelo 198", sourceId: "aeat.model-198.register-design-pdf.2026-07-13" },
  legalSourceIds: ["boe.model-198.order-eha-3895-2004", "boe.model-198.order-hac-1504-2024"],
  related: [
    { code: "187", href: "/consultor-fiscal/modelos/187", description: "Operaciones con acciones y participaciones de instituciones de inversión colectiva." },
    { code: "189", href: "/consultor-fiscal/modelos/189", description: "Valores, seguros y rentas a cierre del ejercicio." },
    { code: "192", href: "/consultor-fiscal/modelos/192", description: "Operaciones específicas con Letras del Tesoro." },
    { code: "194", href: "/consultor-fiscal/modelos/194", description: "Rendimientos y retenciones de determinados activos de deuda." },
  ],
  faq: [
    { question: "¿Lo presenta el inversor?", answer: "No. Lo presenta la entidad o intermediario obligado." },
    { question: "¿Incluye cualquier compra de acciones?", answer: "Incluye las operaciones que encajan en el diseño y no están atribuidas a otro modelo específico." },
    { question: "¿Qué diferencia tiene con el 189?", answer: "El 198 informa operaciones; el 189 posiciones y valores." },
    { question: "¿Qué diferencia tiene con el 187?", answer: "El 187 es específico de instituciones de inversión colectiva." },
    { question: "¿Incluye Letras del Tesoro?", answer: "Estas cuentan con el Modelo 192 específico." },
    { question: "¿Qué límite tiene el formulario?", answer: "Debe comprobarse en la ayuda vigente; por encima se usa fichero." },
    { question: "¿Puede presentarse parcialmente?", answer: "El procedimiento puede admitir parciales, pero deben controlarse para no duplicar el consolidado." },
    { question: "¿Cómo se corrige?", answer: "Con las claves y servicios de corrección oficiales del Modelo 198." },
  ],
});

export const MODEL_199_GUIDE_V1 = createBatch1PracticalGuideV1({
  code: "199",
  category: "Cheques · Información bancaria",
  statusLabel: "Declaración anual",
  statusTone: "current",
  effectiveYear: 2026,
  intro: ["El Modelo 199 identifica anualmente determinadas operaciones con cheques que comunican las entidades de crédito.", "No lo presenta quien emite o cobra el cheque y no es una autoliquidación."],
  notices: [{ title: "La entidad identifica la operación", paragraphs: ["Emisor, librador, beneficiario, persona que cobra, cuenta, importe y país deben seguir el diseño vigente. Informar no determina por sí solo la tributación de la operación."] }],
  type: "Declaración informativa anual de operaciones con cheques.",
  presenter: "Entidades de crédito obligadas.",
  nonPresenter: "Quien emite, recibe o cobra el cheque.",
  periodicity: "Anual.",
  deadline: "En el plazo anual oficial.",
  channel: "Presentación electrónica mediante fichero.",
  result: "Informativo: no genera cuota.",
  included: ["Cheques bancarios y contra cuenta incluidos.", "Cheques nominativos o al portador cuando proceda.", "Emisor, librador, beneficiario y persona que cobra.", "Cuenta, fecha, importe, país e identificación."],
  excluded: ["La declaración personal del beneficiario.", "Operaciones de efectivo del Modelo 171.", "Información general de cuentas del Modelo 196.", "Operaciones con valores del Modelo 198."],
  preparation: ["Identificar tipo de cheque e intervinientes.", "Conciliar cuenta, fecha e importe.", "Validar NIF o identificación extranjera.", "Aplicar exclusiones y diseño vigente."],
  correction: "La entidad de crédito corrige la identificación o la operación. El cliente aporta el cheque y justificante, pero no presenta un Modelo 199 propio.",
  procedureSourceId: "aeat.model-199.procedure-home.2026-03-01",
  recordSourceId: "aeat.model-199.procedure-record.2026-07-08",
  helpSourceId: "aeat.model-199.file-upload-help.2026-04-22",
  document: { label: "Descargar diseño de registro del Modelo 199", sourceId: "aeat.model-199.register-design-pdf.2026-07-13" },
  legalSourceIds: ["boe.model-199.order-2001-12-21", "boe.model-199.order-hac-1430-2025"],
  related: [
    { code: "171", href: "/consultor-fiscal/modelos/171", description: "Imposiciones, disposiciones y cobros de documentos." },
    { code: "196", href: "/consultor-fiscal/modelos/196", description: "Cuentas, saldos y rendimientos financieros." },
  ],
  faq: [
    { question: "¿Lo presenta quien cobra un cheque?", answer: "No. Lo presenta la entidad de crédito." },
    { question: "¿Quién presenta la información?", answer: "La entidad financiera obligada que interviene." },
    { question: "¿Qué cheques se incluyen?", answer: "Los tipos y operaciones definidos en el diseño vigente." },
    { question: "¿Incluye cheques al portador?", answer: "Sí cuando la operación está incluida y se cumplen los campos exigidos." },
    { question: "¿Genera un impuesto?", answer: "No. Es informativo." },
    { question: "¿Qué diferencia hay con el 171?", answer: "El 171 cubre determinadas imposiciones, retiradas y cobros de documentos; el 199 identifica operaciones con cheques." },
    { question: "¿Cuándo se presenta?", answer: "Anualmente." },
    { question: "¿Cómo se corrige una identificación?", answer: "La entidad rectifica el registro con la identificación correcta." },
  ],
});
