import type { FiscalModelPracticalGuideV1 } from "./fiscal-model-practical-guide.types";

export const MODEL_190_GUIDE_V1 = {
  code: "190",
  effectiveYear: 2026,
  lastVerifiedAt: "2026-07-14",
  requiresAnnualReview: true,
  intro: [
    "El Modelo 190 es una declaración informativa anual que identifica a las personas que han recibido las rentas declaradas periódicamente mediante el Modelo 111.",
    "No vuelve a pagar las retenciones ni sustituye los 111 mensuales o trimestrales: detalla por perceptor lo que el retenedor declaró durante el año.",
  ],
  notices: [
    { title: "Es informativo, pero exige conciliación", paragraphs: ["Los importes anuales deben poder explicarse con los Modelos 111, nóminas, facturas y correcciones del ejercicio."] },
    { title: "Claves y subclaves cambian", paragraphs: ["Las claves describen la naturaleza de la renta, pero las subclaves y diseños deben comprobarse para el ejercicio disponible. No reutilices ciegamente un fichero anterior."] },
  ],
  actions: [
    { label: "Presentar Modelo 190 del ejercicio disponible", sourceId: "aeat.model-190.procedure-home.2026-07-08", primary: true },
    { label: "Ver ayuda del formulario", sourceId: "aeat.model-190.browser-form-help.2026-06-19", primary: true },
    { label: "Presentar mediante fichero", sourceId: "aeat.model-190.file-upload-help.2026-06-19" },
    { label: "Emitir certificados", sourceId: "aeat.model-190.certificate-help.2026-04-22" },
    { label: "Consultar preguntas frecuentes oficiales", sourceId: "aeat.model-190.faq.2026-07-08" },
    { label: "Consultar tipos de retención de 2026", href: "https://sede.agenciatributaria.gob.es/static_files/Sede/Programas_ayuda/Retenciones/2026/CUADRO_TIPOS_RETENCION_IRPF_2026.pdf" },
  ],
  quickSummaryTitle: "El Modelo 190 en pocas palabras",
  quickFacts: [
    { label: "Qué es", value: "El resumen anual informativo de retenciones incluidas principalmente en el Modelo 111." },
    { label: "Quién", value: "El retenedor o pagador que ha declarado esas retenciones periódicas." },
    { label: "Qué detalla", value: "Cada perceptor, su tipo de renta, importes satisfechos y retenciones." },
    { label: "Resultado", value: "No genera un nuevo pago." },
    { label: "Plazo general", value: "Del 1 al 31 de enero del año siguiente, con el calendario oficial aplicable." },
    { label: "Canales", value: "Formulario web hasta 40.000 registros y presentación mediante fichero cuando proceda." },
  ],
  sections: [
    {
      id: "model-190-relation",
      title: "Relación con el Modelo 111",
      cards: [
        { title: "Modelo 111", paragraphs: ["Contiene totales del mes o trimestre y sirve para ingresar la retención."], links: [{ label: "Ver la guía del Modelo 111", href: "/consultor-fiscal/modelos/111" }] },
        { title: "Modelo 190", paragraphs: ["Identifica anualmente a cada trabajador, profesional u otro perceptor y desglosa sus datos."] },
        { title: "Conciliación", paragraphs: ["La suma por categorías y perceptores debe explicar los 111 presentados, incluidas complementarias y rectificaciones."] },
      ],
    },
    {
      id: "model-190-included",
      title: "Personas y rentas que detalla",
      cards: [
        { title: "Trabajo", bullets: ["Trabajadores y otras personas con rendimientos del trabajo.", "Retribuciones dinerarias y en especie cuando correspondan."] },
        { title: "Actividades económicas", bullets: ["Profesionales.", "Determinadas actividades agrícolas, ganaderas y forestales.", "Determinadas actividades empresariales sujetas."] },
        { title: "Otras categorías", paragraphs: ["Determinados premios, ganancias patrimoniales e imputaciones de renta incluidas en el ámbito oficial."] },
      ],
      note: "No incluye los alquileres urbanos que se resumen mediante el Modelo 180 ni el IVA de las facturas.",
    },
    {
      id: "model-190-keys",
      title: "Claves habituales del perceptor",
      cards: [
        { title: "A · Trabajo", paragraphs: ["Rendimientos del trabajo de empleados por cuenta ajena, según el diseño del ejercicio."] },
        { title: "E · Consejeros y administradores", paragraphs: ["Retribuciones de consejeros y administradores."] },
        { title: "F · Cursos, conferencias y similares", paragraphs: ["Determinados rendimientos del trabajo por cursos, conferencias, seminarios y elaboración de obras en los supuestos previstos."] },
        { title: "G · Actividades profesionales", paragraphs: ["Rendimientos de actividades profesionales."] },
        { title: "H · Actividades agrícolas, ganaderas, forestales y empresariales", paragraphs: ["Rentas de las actividades que el diseño anual encuadra en esta clave."] },
        { title: "K · Premios y determinadas ganancias", paragraphs: ["Premios y determinadas ganancias patrimoniales e imputaciones de renta."] },
      ],
      note: "Las subclaves no son permanentes: revisa las instrucciones y el diseño de registro del ejercicio que vayas a presentar.",
    },
    {
      id: "model-190-preparation",
      title: "Datos y comprobaciones",
      cards: [
        { title: "Identificación", bullets: ["NIF y nombre del perceptor.", "Provincia y demás datos exigidos.", "Clave y subclave anual correctas."] },
        { title: "Importes", bullets: ["Percepciones íntegras dinerarias.", "Valoración e ingresos a cuenta de retribuciones en especie.", "Retenciones practicadas."] },
        { title: "Situaciones específicas", bullets: ["Datos de descendientes y ascendientes cuando los exige la clave.", "Pensiones compensatorias y anualidades.", "Reducciones y gastos deducibles cuando correspondan al diseño."] },
      ],
      note: "Comprueba el NIF de terceros antes de presentar y evita crear registros duplicados para un mismo perceptor y clave.",
    },
    {
      id: "model-190-channels",
      title: "Formulario, fichero y vista previa",
      cards: [
        { title: "Formulario web", paragraphs: ["Permite introducir o importar hasta 40.000 registros, validar, consultar errores y guardar la declaración."] },
        { title: "Presentación mediante fichero", paragraphs: ["Para declaraciones con más de 40.000 registros se utiliza el canal mediante fichero ajustado al diseño vigente."] },
        { title: "Vista previa", paragraphs: ["El PDF de vista previa sirve para revisar datos, pero no es válido para presentar. Solo la firma y envío generan justificante oficial."] },
      ],
      note: "El formulario puede permitir presentar registros correctos y dejar los erróneos pendientes. Es una opción avanzada: hay que controlar después qué perceptores quedaron realmente presentados.",
    },
    {
      id: "model-190-corrections",
      title: "Correcciones y declaraciones anteriores",
      intro: ["Si ya existe una declaración del ejercicio, el formulario permite cargarla para consultar y modificar registros."],
      accordions: [
        { question: "Alta de un perceptor omitido", paragraphs: ["Carga la declaración presentada y añade el registro que falta siguiendo la opción oficial de modificación."] },
        { question: "Modificación o baja", paragraphs: ["Corrige o elimina el registro afectado en la declaración cargada. No envíes otro 190 completo sin comprobar cómo trata la AEAT la declaración anterior."] },
        { question: "¿Y si también estaba mal el 111?", paragraphs: ["Corregir el 190 no corrige automáticamente la autoliquidación periódica. Revisa y corrige por separado el Modelo 111 afectado."] },
      ],
    },
    {
      id: "model-190-certificates",
      title: "Certificados y archivo",
      cards: [
        { title: "Certificados", paragraphs: ["La ayuda oficial permite generar certificados individuales o colectivos para los perceptores incluidos."] },
        { title: "Conservación", paragraphs: ["Guarda justificante, CSV, fichero presentado, certificados y la conciliación con los 111 y la contabilidad."] },
        { title: "Ejercicio disponible", paragraphs: ["Utiliza siempre formulario, instrucciones, claves y diseño del ejercicio que figure abierto en la AEAT; no dependas de un año hardcodeado."] },
      ],
    },
    {
      id: "model-190-mistakes",
      title: "Errores habituales",
      cards: [
        { title: "Contenido", bullets: ["Pensar que vuelve a pagar retenciones.", "Incluir alquileres del Modelo 180.", "Incluir el IVA de facturas profesionales.", "Elegir claves o subclaves por copia del año anterior.", "Duplicar perceptores."] },
        { title: "Proceso", bullets: ["No conciliar con los 111.", "Creer que la vista previa está presentada.", "Presentar solo los registros correctos y olvidar los pendientes.", "Modificar el 190 sin corregir un 111 erróneo.", "No emitir certificados."] },
      ],
    },
  ],
  fillingTitle: "Cómo preparar el resumen anual",
  fillingSteps: [
    { title: "1. Reúne los 111 y el detalle", paragraphs: ["Parte de las autoliquidaciones, nóminas, facturas y correcciones del ejercicio."] },
    { title: "2. Identifica a cada perceptor", paragraphs: ["Comprueba NIF y datos identificativos antes de asignar clave y subclave."] },
    { title: "3. Desglosa percepciones", paragraphs: ["Separa dinerarias y en especie, retenciones y restantes campos exigidos."] },
    { title: "4. Concilia y valida", paragraphs: ["Los totales deben explicar los 111 y los libros. Resuelve errores y advertencias del formulario."] },
    { title: "5. Firma, envía y certifica", paragraphs: ["Obtén el justificante oficial y genera los certificados de los perceptores."] },
  ],
  afterTitle: "Qué ocurre después",
  afterSteps: [
    { title: "Justificante", description: "Conserva la respuesta oficial y el CSV." },
    { title: "Certificados", description: "Entrega o pon a disposición de cada perceptor su certificado cuando corresponda." },
    { title: "Correcciones", description: "Si detectas un error, distingue el registro anual del 111 periódico afectado." },
  ],
  comparison: {
    title: "Relación con el Modelo 111",
    current: { title: "Modelo 190", description: "Detalle anual informativo por perceptor; no genera un nuevo pago." },
    related: { title: "Modelo 111", description: "Autoliquidación periódica que ingresa las retenciones.", href: "/consultor-fiscal/modelos/111", label: "Ver Modelo 111" },
    additional: [{ title: "Modelo 180", description: "Resumen anual específico para determinados alquileres urbanos.", href: "/consultor-fiscal/modelos/180", label: "Ver Modelo 180" }],
    conclusion: "El 190 resume el detalle personal de las rentas del 111; el 180 separa los alquileres urbanos.",
  },
  pdfNotice: ["Las instrucciones y diseños corresponden al ejercicio que indican. Un PDF de vista previa o un certificado no es la declaración presentada."],
  documents: [{ label: "Descargar instrucciones oficiales del Modelo 190", sourceId: "aeat.model-190.instructions-pdf.2026-07-13" }],
  officialLinks: [
    { label: "Ficha administrativa del procedimiento", sourceId: "aeat.model-190.procedure-record.2026-07-08" },
    { label: "Ayuda del formulario web", sourceId: "aeat.model-190.browser-form-help.2026-06-19" },
    { label: "Ayuda de presentación mediante fichero", sourceId: "aeat.model-190.file-upload-help.2026-06-19" },
    { label: "Preguntas frecuentes oficiales", sourceId: "aeat.model-190.faq.2026-07-08" },
    { label: "Ayuda para emitir certificados", sourceId: "aeat.model-190.certificate-help.2026-04-22" },
  ],
  legalLinks: [
    { label: "Orden EHA/3127/2009", sourceId: "boe.model-190.order-eha-3127-2009" },
    { label: "Orden HAC/1431/2025", sourceId: "boe.model-190.order-hac-1431-2025" },
    { label: "Ley 35/2006 del IRPF", href: "https://www.boe.es/buscar/act.php?id=BOE-A-2006-20764" },
    { label: "Reglamento del IRPF", href: "https://www.boe.es/buscar/act.php?id=BOE-A-2007-6820" },
  ],
  faq: [
    { question: "¿Tengo que presentar el 190 si presenté el 111?", answer: "Con carácter general, sí: es el resumen anual de las rentas incluidas en el 111." },
    { question: "¿El Modelo 190 vuelve a pagar retenciones?", answer: "No. Es una declaración informativa anual." },
    { question: "¿Incluye un registro por cada persona?", answer: "Sí, con el detalle exigido por perceptor, clave y subclave." },
    { question: "¿Incluye trabajadores y profesionales?", answer: "Sí, cuando sus rentas fueron declaradas mediante el Modelo 111." },
    { question: "¿Incluye el alquiler de un local?", answer: "No. Ese alquiler se resume mediante el Modelo 180." },
    { question: "¿Tiene que coincidir con el Modelo 111?", answer: "Sus totales deben poder conciliarse con los 111 presentados y corregidos." },
    { question: "¿Cuándo se presenta?", answer: "Con carácter general, del 1 al 31 de enero del año siguiente." },
    { question: "¿Qué canal uso con más de 40.000 registros?", answer: "La presentación mediante fichero ajustado al diseño vigente." },
    { question: "¿La vista previa es válida para presentar?", answer: "No. Debes firmar y enviar y obtener el justificante oficial." },
    { question: "¿Puedo generar certificados?", answer: "Sí. El formulario permite generar certificados individuales o colectivos." },
    { question: "¿Cómo corrijo una declaración presentada?", answer: "Carga la declaración del ejercicio y realiza las altas, modificaciones o bajas necesarias." },
  ],
  sourceIds: [
    "aeat.model-190.procedure-home.2026-07-08",
    "aeat.model-190.procedure-record.2026-07-08",
    "aeat.model-190.browser-form-help.2026-06-19",
    "aeat.model-190.file-upload-help.2026-06-19",
    "aeat.model-190.certificate-help.2026-04-22",
    "aeat.model-190.faq.2026-07-08",
    "aeat.model-190.instructions-pdf.2026-07-13",
    "boe.model-190.order-eha-3127-2009",
    "boe.model-190.order-hac-1431-2025",
  ],
} as const satisfies FiscalModelPracticalGuideV1;
