import type { FiscalModelPracticalGuideV1 } from "./fiscal-model-practical-guide.types";

export const MODEL_347_GUIDE_V1 = {
  code: "347",
  lastVerifiedAt: "2026-07-14",
  requiresAnnualReview: true,
  intro: [
    "El Modelo 347 sirve para informar anualmente a la Agencia Tributaria de determinadas operaciones realizadas con una misma persona o entidad cuando superan el límite establecido.",
    "No es un impuesto ni genera un nuevo pago. Informa sobre clientes, proveedores y otras operaciones relevantes del ejercicio.",
  ],
  notices: [
    { title: "El límite general no se calcula factura por factura", paragraphs: ["Se comprueba si el total anual de operaciones declarables con una misma persona o entidad supera 3.005,06 €, con IVA y recargo de equivalencia incluidos con carácter general."] },
    { title: "Compras y ventas no se compensan", paragraphs: ["Se declaran separadamente con sus claves. Una compra a un tercero no reduce una venta realizada al mismo tercero."] },
    { title: "Superar el límite no basta por sí solo", paragraphs: ["Existen operaciones excluidas, regímenes especiales y datos ya informados mediante otra declaración específica que no deben duplicarse automáticamente."] },
  ],
  actions: [
    { label: "Presentar Modelo 347 del ejercicio disponible", sourceId: "aeat.model-347.procedure-home.2026-07-08", primary: true },
    { label: "Comprobar NIF de terceros", href: "https://sede.agenciatributaria.gob.es/Sede/procedimientoini/GZ28.shtml", primary: true },
    { label: "Ver ayuda del formulario", sourceId: "aeat.model-347.form-help.2026-06-19" },
    { label: "Presentar mediante fichero", sourceId: "aeat.model-347.file-help.2026-06-19" },
    { label: "Consultar preguntas frecuentes", sourceId: "aeat.model-347.faq.2026-07-08" },
    { label: "Consultar instrucciones y operaciones excluidas", sourceId: "aeat.model-347.instructions.2026-07-08" },
  ],
  quickSummaryTitle: "El Modelo 347 en pocas palabras",
  quickFacts: [
    { label: "Qué es", value: "Una declaración informativa anual de operaciones con terceras personas." },
    { label: "Límite general", value: "Más de 3.005,06 € anuales con una misma persona o entidad." },
    { label: "Incluye IVA", value: "Sí, con carácter general; también el recargo de equivalencia que corresponda." },
    { label: "Se calcula por factura", value: "No. Se utiliza el total anual de las operaciones declarables." },
    { label: "Desglose", value: "Generalmente por trimestres, aunque el límite es anual." },
    { label: "Plazo general", value: "Durante el mes de febrero del año siguiente." },
    { label: "Genera un pago", value: "No." },
    { label: "Presentación", value: "Por internet; formulario web hasta 40.000 registros o mediante fichero." },
  ],
  sections: [
    {
      id: "model-347-decision",
      title: "¿Tengo que presentarlo?",
      cards: [
        { title: "1. Actividad", paragraphs: ["Comprueba que las operaciones se realizan dentro de tu actividad empresarial o profesional. Esta guía no cubre todos los supuestos especiales de Administraciones, comunidades de propietarios y otras entidades."] },
        { title: "2. Límite anual", paragraphs: ["Calcula por cada persona o entidad las operaciones computables del año. Si no superan 3.005,06 €, no existe obligación por ese tercero."] },
        { title: "3. Exclusiones", paragraphs: ["Revisa si la operación está excluida o ya se informa mediante otra declaración específica con contenido coincidente."] },
        { title: "4. SII", paragraphs: ["Quienes estuvieron obligados durante todo el ejercicio al Suministro Inmediato de Información (SII) no presentan, con carácter general, el 347."] },
      ],
      note: "La obligación se comprueba por cada tercero y por la naturaleza real de la operación; no es un modelo obligatorio para todo autónomo.",
    },
    {
      id: "model-347-threshold",
      title: "Cómo funciona el límite",
      cards: [
        { title: "Varias facturas pequeñas", bullets: ["Cuatro facturas de 800 € IVA incluido al mismo cliente.", "Total anual: 3.200 €.", "Se supera el límite aunque ninguna factura individual lo haga."] },
        { title: "El IVA puede hacer que se supere", bullets: ["Base anual: 2.600 €.", "IVA del 21 %: 546 €.", "Total: 3.146 €.", "Se supera el límite general."] },
        { title: "Compras y ventas con la misma persona", paragraphs: ["Se registran por separado. No se obtiene un saldo neto restando compras de ventas."] },
      ],
      note: "El umbral exige superar 3.005,06 €: un total exactamente igual no lo supera. Devoluciones, descuentos y rectificaciones modifican el total anual.",
    },
    {
      id: "model-347-operations",
      title: "Operaciones que pueden incluirse",
      cards: [
        { title: "Compras y gastos", bullets: ["Compras de bienes.", "Compras de servicios.", "Anticipos entregados a proveedores."] },
        { title: "Ventas e ingresos", bullets: ["Ventas de bienes.", "Prestaciones de servicios.", "Anticipos de clientes.", "Determinadas subvenciones recibidas."] },
        { title: "Otras operaciones", bullets: ["Determinados arrendamientos.", "Operaciones exentas o no sujetas no excluidas.", "Inversión del sujeto pasivo cuando deba informarse.", "Criterio de caja y determinadas transmisiones de inmuebles."] },
      ],
      note: "Que una operación no lleve IVA no significa automáticamente que quede fuera del Modelo 347.",
    },
    {
      id: "model-347-exclusions",
      title: "Operaciones que no deben incluirse automáticamente",
      accordions: [
        { question: "Operaciones internacionales", paragraphs: ["Se excluyen, entre otras, importaciones y exportaciones de mercancías y envíos entre Península o Baleares y Canarias, Ceuta o Melilla. No descartes una factura solo por ser extranjera: distingue importación, exportación, intracomunitaria o servicio internacional."] },
        { question: "Información ya comunicada", paragraphs: ["No debe duplicarse información ya suministrada mediante el 180, 190, 349, SII u otra declaración específica cuando el contenido coincida. La exclusión exige comprobar la operación concreta."], bullets: ["Facturas profesionales incluidas en el Modelo 190.", "Alquileres sujetos informados en el Modelo 180.", "Operaciones intracomunitarias incluidas en el Modelo 349."] },
        { question: "Operaciones fuera de la actividad o sin factura", paragraphs: ["Existen exclusiones para operaciones fuera de la actividad, determinadas operaciones sin obligación de expedir factura y otros supuestos expresamente previstos."] },
      ],
    },
    {
      id: "model-347-special",
      title: "Módulos, SII y REDEME",
      accordions: [
        { question: "¿Qué ocurre si tributo por módulos?", paragraphs: ["No es correcto afirmar que todos los autónomos en módulos están exonerados. Las personas en estimación objetiva y determinados regímenes especiales de IVA pueden quedar fuera respecto de parte de sus operaciones, pero deben revisar las operaciones por las que expiden factura y, en régimen simplificado, determinadas adquisiciones anotadas."] },
        { question: "¿Y si estoy en SII o REDEME?", paragraphs: ["La exoneración general exige haber estado obligado durante todo el ejercicio a llevar los libros mediante SII. Afecta a muchos inscritos en el Registro de Devolución Mensual (REDEME), pero presentar IVA mensualmente no exime por sí solo. Si el SII solo se aplicó parte del año, revisa el caso."] },
      ],
    },
    {
      id: "model-347-amounts",
      title: "Importes, rectificaciones y anticipos",
      cards: [
        { title: "Importe declarado", paragraphs: ["Se utiliza la contraprestación total según las reglas del IVA: base, IVA, recargo de equivalencia y, cuando proceda, compensaciones agrarias."] },
        { title: "Importe negativo", paragraphs: ["Puede existir si las devoluciones o rectificaciones superan las operaciones positivas. Se declara cuando su valor absoluto anual supera 3.005,06 €; por ejemplo, una devolución de −4.000 € de una venta anterior."] },
        { title: "Anticipos", paragraphs: ["Se declaran. Si hubo un anticipo de 2.000 € y la operación final asciende a 8.000 €, se evita duplicarlo declarando 6.000 € restantes al realizarse la operación definitiva."] },
      ],
    },
    {
      id: "model-347-quarters",
      title: "Desglose trimestral y diferencias entre partes",
      cards: [
        { title: "Regla general", paragraphs: ["Aunque el modelo es anual, los importes se distribuyen normalmente por trimestres según cuándo la factura debe anotarse en el libro registro."] },
        { title: "Diferencia legítima", paragraphs: ["Una factura emitida el 25 de marzo puede figurar en el primer trimestre del proveedor y en el segundo del cliente si este la recibe y registra el 4 de abril."] },
        { title: "Datos anuales especiales", paragraphs: ["Efectivo, criterio de caja y determinados supuestos de comunidades de propietarios pueden informarse de forma anual."] },
      ],
      note: "El límite se comprueba sobre el año completo, nunca por cada trimestre.",
    },
    {
      id: "model-347-cash-rentals",
      title: "Efectivo y arrendamientos",
      cards: [
        { title: "Cobros en efectivo", paragraphs: ["Se informan separadamente las cantidades superiores a 6.000 € recibidas en efectivo de una misma persona o entidad. No son transferencias ni cualquier pago realizado en metálico, y el dato no autoriza pagos en efectivo."] },
        { title: "Arrendamiento de local", paragraphs: ["Cuando deba incluirse, el arrendador identifica referencia catastral, dirección, situación e importe anual. Los alquileres sujetos a retención ya informados en el 180 no se duplican automáticamente."], links: [{ label: "Ver Modelo 180", href: "/consultor-fiscal/modelos/180" }] },
      ],
    },
    {
      id: "model-347-keys",
      title: "Claves principales",
      cards: [
        { title: "A · Compras", paragraphs: ["Adquisiciones de bienes y servicios declarables."] },
        { title: "B · Ventas", paragraphs: ["Entregas de bienes y prestaciones de servicios declarables; también determinadas subvenciones recibidas."] },
      ],
      accordions: [{ question: "Claves menos habituales", paragraphs: ["C se refiere a cobros por cuenta de terceros; D y E a supuestos específicos de entidades y Administraciones; F y G a operaciones de agencias de viajes. La mayoría de autónomos utilizará principalmente A y B."] }],
    },
    {
      id: "model-347-filing",
      title: "Formulario, fichero y correcciones",
      cards: [
        { title: "Formulario web", paragraphs: ["Admite hasta 40.000 registros, guardado, importación, validación y recuperación de declaraciones presentadas."] },
        { title: "Presentación mediante fichero", paragraphs: ["Puede utilizarse con menos registros y resulta necesaria cuando se supera el límite del formulario. El archivo debe cumplir el diseño vigente."] },
        { title: "Vista previa", paragraphs: ["El PDF no es una declaración presentada. Solo la firma y envío y el justificante con Código Seguro de Verificación (CSV) completan la presentación."] },
      ],
      note: "El formulario puede presentar registros correctos dejando otros pendientes, pero no es la opción habitual. Para corregir una declaración cargada, añade, modifica o elimina registros, valida y presenta de nuevo el conjunto completo; esa nueva presentación deja sin efecto la anterior. En el formulario actual no se utiliza el antiguo flujo de complementaria o sustitutiva. La vía mediante fichero tiene reglas propias.",
    },
    {
      id: "model-347-related",
      title: "Relación con otros modelos",
      cards: [
        { title: "Modelo 036", paragraphs: ["Comunica altas, modificaciones y bajas censales."], links: [{ label: "Ver Modelo 036", href: "/consultor-fiscal/modelos/036" }] },
        { title: "Modelo 303", paragraphs: ["Declara el IVA del periodo. El 347 informa anualmente de terceros."], links: [{ label: "Ver Modelo 303", href: "/consultor-fiscal/modelos/303" }] },
        { title: "Modelos 190 y 349", paragraphs: ["Evita duplicar información ya comunicada con contenido coincidente."], links: [{ label: "Ver Modelo 190", href: "/consultor-fiscal/modelos/190" }, { label: "Ver Modelo 349", href: "/consultor-fiscal/modelos/349" }] },
      ],
    },
    {
      id: "model-347-territory",
      title: "Ámbito territorial",
      note: "Esta guía se refiere principalmente a la AEAT estatal y al territorio de aplicación del IVA español formado por Península y Baleares. Canarias, Ceuta y Melilla tienen particularidades y no forman parte de ese territorio. En País Vasco o Navarra también puede corresponder la Hacienda foral.",
    },
  ],
  fillingTitle: "Cómo preparar y presentar el Modelo 347",
  fillingSteps: [
    { title: "1. Reúne libros y facturas", paragraphs: ["Cruza facturas expedidas y recibidas, devoluciones, anticipos, modelos específicos y datos del SII."] },
    { title: "2. Agrupa por tercero y clave", paragraphs: ["Comprueba NIF y nombre; separa compras A de ventas B y calcula el total anual con IVA."] },
    { title: "3. Aplica exclusiones", paragraphs: ["Revisa operaciones internacionales, retenciones, SII y declaraciones informativas coincidentes."] },
    { title: "4. Desglosa por trimestres", paragraphs: ["Distribuye según la anotación registral y cumplimenta efectivo, criterio de caja o inmuebles cuando corresponda."] },
    { title: "5. Valida, firma y conserva", paragraphs: ["Corrige errores, firma, envía y guarda justificante, número de registro y CSV."] },
  ],
  afterTitle: "Qué ocurre después",
  afterSteps: [
    { title: "Contraste", description: "La AEAT puede comparar la información de ambas partes; una diferencia trimestral no implica por sí sola un error." },
    { title: "Corrección", description: "Recupera la declaración, modifica el conjunto completo y vuelve a presentarlo según la ayuda vigente." },
    { title: "Archivo", description: "Conserva facturas, libros, cálculos del límite, justificante y consultas de NIF." },
  ],
  comparison: {
    title: "¿Necesitas el Modelo 347 o el Modelo 349?",
    current: { title: "Modelo 347", description: "Declara anualmente determinadas operaciones con terceros cuando se supera el límite y no existe exclusión o declaración específica coincidente." },
    related: { title: "Modelo 349", description: "Declara operaciones intracomunitarias con empresas o profesionales de otros países de la Unión Europea, sin importe mínimo general.", href: "/consultor-fiscal/modelos/349", label: "Ver Modelo 349" },
    additional: [
      { title: "Modelo 303", description: "Declara el IVA del periodo y puede coexistir con información del 347 o 349.", href: "/consultor-fiscal/modelos/303", label: "Ver Modelo 303" },
      { title: "Modelo 036", description: "Comunica obligaciones censales y el alta en el ROI.", href: "/consultor-fiscal/modelos/036", label: "Ver Modelo 036" },
    ],
    conclusion: "El 347 tiene límite general anual; el 349 no tiene importe mínimo y sus 50.000 € solo determinan periodicidad.",
  },
  pdfNotice: ["La vista previa no es válida para presentar. Debes firmar y enviar en la sede oficial y obtener el justificante con CSV."],
  documents: [],
  officialLinks: [
    { label: "Ficha administrativa del procedimiento", sourceId: "aeat.model-347.procedure-record.2026-07-08" },
    { label: "Ayuda del formulario web", sourceId: "aeat.model-347.form-help.2026-06-19" },
    { label: "Ayuda de presentación mediante fichero", sourceId: "aeat.model-347.file-help.2026-06-19" },
    { label: "Preguntas frecuentes oficiales", sourceId: "aeat.model-347.faq.2026-07-08" },
  ],
  legalLinks: [
    { label: "Orden EHA/3012/2008", sourceId: "boe.model-347.order-eha-3012-2008.original" },
    { label: "Real Decreto 1065/2007", href: "https://www.boe.es/buscar/act.php?id=BOE-A-2007-15984" },
  ],
  faq: [
    { question: "¿El Modelo 347 sirve para pagar un impuesto?", answer: "No. Es una declaración informativa." },
    { question: "¿Cuál es el límite general?", answer: "Más de 3.005,06 € anuales con una misma persona o entidad, en operaciones declarables." },
    { question: "¿El límite incluye IVA?", answer: "Sí, con carácter general." },
    { question: "¿Se calcula por factura?", answer: "No. Se utiliza el total anual." },
    { question: "¿Se calcula por trimestre?", answer: "No. El límite es anual, aunque normalmente se desglose por trimestres." },
    { question: "¿Debo sumar compras y ventas?", answer: "No deben compensarse; se declaran en registros separados." },
    { question: "¿Incluyo operaciones intracomunitarias?", answer: "Las incluidas en el 349 no deben duplicarse automáticamente en el 347." },
    { question: "¿Incluyo facturas profesionales con retención?", answer: "Comprueba si ya se informan mediante el 190 y si coincide el contenido comunicado." },
    { question: "¿Incluyo el alquiler de mi local?", answer: "Revisa si está sujeto a retención e incluido en el 180 o si corresponde informarlo en el 347." },
    { question: "¿Qué pasa si estoy en módulos?", answer: "Existen reglas especiales; no todos los autónomos en módulos están totalmente exonerados." },
    { question: "¿Qué pasa si estoy en SII?", answer: "Quien estuvo obligado todo el ejercicio al SII no presenta, con carácter general, el 347." },
    { question: "¿Puede haber diferencias de trimestre?", answer: "Sí. La recepción y anotación de la factura puede provocar diferencias legítimas." },
    { question: "¿Puede declararse un importe negativo?", answer: "Sí, cuando el valor absoluto anual supera el límite." },
    { question: "¿Se presentan los anticipos?", answer: "Sí, evitando duplicarlos cuando se realiza la operación definitiva." },
    { question: "¿Se presenta si no supero el límite con nadie?", answer: "No se presenta una declaración sin registros por ese motivo." },
    { question: "¿Cuándo se presenta?", answer: "Durante el mes de febrero del año siguiente." },
    { question: "¿Cómo corrijo un error?", answer: "Carga la declaración, modifica los registros y vuelve a presentar el conjunto completo." },
    { question: "¿La vista previa en PDF es válida?", answer: "No." },
  ],
  sourceIds: [
    "aeat.model-347.procedure-home.2026-07-08",
    "aeat.model-347.procedure-record.2026-07-08",
    "aeat.model-347.form-help.2026-06-19",
    "aeat.model-347.file-help.2026-06-19",
    "aeat.model-347.instructions.2026-07-08",
    "aeat.model-347.faq.2026-07-08",
    "boe.model-347.order-eha-3012-2008.original",
  ],
} as const satisfies FiscalModelPracticalGuideV1;
